### DISCUSSION TITLE
set up locale keyboard ?

### DISCUSSION THREAD

**Discussion by poblin-orange** [kairos-io/kairos#1177] [Q&A] [answered]
Hello Friends,
currently testing kairos k8s os builder to generate ISO. Very nice experience so far.

Im not testing the ISO on my environnement (vsphere 7, booting on ISO, only console mode avaible wrt / network constraint).

Is there a way to configure the keyboard for my local (fr).
Maybe with cloud-init syntax ?

- https://kairos.io/docs/architecture/cloud-init/
  - https://cloudinit.readthedocs.io/en/latest/reference/modules.html#keyboard
  - https://cloudinit.readthedocs.io/en/latest/reference/examples.html#cloud-config-examples

```
...
apiVersion: build.kairos.io/v1alpha1
kind: OSArtifact
metadata:
  name: ubuntu-k3s-v2
spec:
  imageName: quay.io/kairos/core-ubuntu-22-lts-k3s:v1.25.2-k3s1_v1.2.3
  iso: true
  bundles:
  # Bundles available at: https://packages.kairos.io/Kairos/
  - quay.io/kairos/packages:helm-utils-3.10.1
  - quay.io/kairos/packages:k9s-utils-0.26.7
  cloudConfig: |
    #cloud-config
    hostname: k3s-{{ trunc 4 .MachineID }}
....    
    #set keyboard locale
    # Set keyboard layout to "us"
    keyboard:
      layout: fr
...
```

**Comment by Itxaka** [comment, marked as answer]
Bonjour!

If you are using a systemd-based derivative (All flavors except alpine) you should be able to use the `systemd-firstboot key to set the keyboard `https://github.com/mudler/yip#stagesstageidstepnsystemd_firstboot`

so for example you would set this in your config to have it run and set the keyboard:

```
stages:
  initramfs:
    - name: "Setup locale"
      systemd_firstboot:
        keymap: fr
```


For **Ubuntu** systems which dont have the systemd-firstboot service, a simple `loadkeys` in the boot stage to load the keymap should work:

```
stages:
  boot:
    - name:
      commands:
        - loadkeys fr
```

**Reply by Itxaka** [reply]
Confirmed, initramfs stage is the expected one, just checked this to set up my spanish keyboard :=)

**Reply by poblin-orange** [reply]
thks @ltxaka

**Comment by poblin-orange** [comment]
Merci @Itxaka  :-)
Unfortunatly, i had no luck with initramfs. Still english. Im on quay.io/kairos/core-ubuntu-22-lts-k3s:v1.25.2-k3s1_v1.2.3, so i have systemd i guess.
Any reason to use the same instruction in other phases ? (say boot )

**Reply by Itxaka** [reply]
Umm, weird, can you show me your config yaml?

The one I tested was:

```
#cloud-config

install:
  auto: true
  reboot: true
  device: /dev/vda

stages:
   initramfs:
     - name: "Set user and password"
       users:
        kairos:
          passwd: "kairos"
       hostname: kairos-{{ trunc 4 .Random }}
     - name: "Setup locale"
       systemd_firstboot:
         keymap: es

```

And I got the correct spanish keyboard

**Comment by poblin-orange** [comment]
Here is my OsArtifact:
```
apiVersion: build.kairos.io/v1alpha1
kind: OSArtifact
metadata:
  name: ubuntu-22-lts
spec:
  imageName: quay.io/kairos/kairos-ubuntu-22-lts:v1.6.1-k3sv1.26.1-k3s1
  iso: true
  bundles:
  # Bundles available at: https://packages.kairos.io/Kairos/
  - quay.io/kairos/packages:helm-utils-3.10.1
  - quay.io/kairos/packages:k9s-utils-0.26.7

    #cloud-config
    hostname: k3s-{{ trunc 4 .MachineID }}
    users:
    - name: "kairos"
      passwd: "kairos"
    install:
      device: "auto"
      reboot: true
      poweroff: false
      auto: true # Required, for automated installations
     # install stages, yip definitions. https://github.com/mudler/yip
     # available stages https://kairos.io/docs/architecture/cloud-init/#boot-stages
    stages:
      initramfs:
        - name: "Setup locale"
          systemd_firstboot:
            keymap: fr
```

**Reply by Itxaka** [reply]
Weird, jsut tested this with my iso, and got the proper FR keyboard. Maybe its an ubuntu thing!

**Reply by Itxaka** [reply]
well crap, ubuntu just doesnt seem to have the systemd-firstboot service! No wonder it didnt work for you :D

**Reply by Itxaka** [reply]
Im expanding my first answer :D

**Reply by poblin-orange** [reply]
thks @Itxaka . Testing this evening

**Comment by codecrafter404** [comment]
For everyone finding this in the future, on **alpine** this works:
```yaml
stages:
    boot:
        - name: Setup Keymap
          commands:
            - echo 'KEYMAP="/usr/share/bkeymaps/de/de.bmap.gz"' > /etc/conf.d/loadkmap && rc-service loadkmap restart
```
just look up your keymap in `/usr/share/bkeymaps/` :)
