### DISCUSSION TITLE
Kairos upgrade via kubernetes specifying custom image

### DISCUSSION THREAD

**Discussion by cristian98149** [kairos-io/kairos#1366] [Q&A] [answered]
Hi all,
is it possible to upgrade kairos via kubernetes specifying a custom image stored on private/public registry?

From docs I've seen that using manual upgrade this is possible but it's not clear if it can be done also via k8s.

Thank you

**Comment by Itxaka** [comment, marked as answer]
Hi!

As long as the registry its accessible by the node and has no auth you can just follow up the docs: https://kairos.io/docs/upgrade/kubernetes/

If it has auth then its not supported and being tracked on https://github.com/kairos-io/kairos/issues/513

**Reply by cristian98149** [reply]
Hi @Itxaka,
form Plan manifest it is not clear for me where custom image must be specified.

What does spec.version fied mean? Current kairos release, so before upgrade?

What does spec.upgrade.image field mean? Is it a container that upgrades kairos? I also see "# Currently can pick between opensuse and alpine" this comment.

Thank you

**Reply by Itxaka** [reply]
`spec.version` is the tag of the image to upgrade to.
`spec.upgrade.image` is the image that it will be upgraded to.

So if you wanted to upgrade to an image that was `myregistry.com/myimage:v5.0.0` you would set the following spec:

```
spec:
  concurrency: 1
  version: "v5.0.0"
  nodeSelector:
    matchExpressions:
      - {key: kubernetes.io/hostname, operator: Exists}
  serviceAccountName: system-upgrade
  cordon: false
  drain:
    force: false
    disableEviction: true
  upgrade:
    image: "myregistry.com/myimage"
    command:
    - "/usr/sbin/suc-upgrade"
```

The comment "# Currently can pick between opensuse and alpine" seems to be al old comment, when there was only opensuse and alpine images published for Kairos, so our example mentioned only those :)
