### DISCUSSION TITLE
Assistance with getting Auroraboot custom ubuntu image with bind_mounts and k3s working

### DISCUSSION THREAD

**Discussion by mod35** [kairos-io/kairos#1724] [Q&A] [answered]
Hello everyone. Really struggling with getting a kairos custom image setup working. I think I'm close but would massively appreciate any assistance here - been struggling on and off for weeks I'm ashamed to admit.

## The Setup
I'm trying to get a custom image setup working using the following base image with k3s.
```dockerfile
FROM quay.io/kairos/kairos-ubuntu:v2.3.1-k3sv1.27.3-k3s1
# I don't need htop, but I can imagine as I go forward that there will be software I want - so this is just a PoC
RUN apt update && apt install htop
# Note this is pushed to my gitlab registry and is referred to below as $CI_REGISTRY_IMAGE/kairos_ubuntu$tag
```
Next I do the following to create a bootable iso in a gitlab runner, it uses the auroraboot image, and actually just saves to my gitlab runners passed in volume - that way I can grab it off that vm and upload it to my proxmox server for installation (I failed to get netboot going!). basically it just pulls the above image that's built in an earlier step down, and calls auroraboot directly with a cloud-config file.

```yaml
  # Use the official docker image.
  stage: build
  image: quay.io/kairos/auroraboot
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # Note this image is the ubuntu image above that I've created in a previous runner step that's pushed to registry
    - export IMAGE=$CI_REGISTRY_IMAGE/kairos_ubuntu$tag
    - docker pull $IMAGE
    # We don't need to push to external state, we have a mount point /home/modes/gitlab-runner-state that can be copied to
    # First let's clear anything that's in there
    - ls -alh /home/modes/gitlab-runner-state/
    - rm -rf /home/modes/gitlab-runner-state/*
    - >
      /usr/bin/auroraboot --debug
      --set container_image=docker://$IMAGE
      --set "disable_http_server=true" 
      --set "disable_netboot=true" 
      --cloud-config cloud_init.yaml
      --set "state_dir=/home/modes/gitlab-runner-state"
    - chown --recursive 1000:1000 /home/modes/gitlab-runner-state/iso
```

The `cloud_init.yaml` file mentioned above is the following:
```yaml
#cloud-config

hostname: kairos
users:
- name: kairos
  # Change to your pass here
  passwd: redacted
  ssh_authorized_keys:
  # Replace with your github user and un-comment the line below:
  - redacted

# The install block is to drive automatic installations without user interaction.
install:
  # Make sure the installer won't delete our custom partitions
  no-format: true
  # Device for automated installs
  device: "/dev/sda"
  # Reboot after installation
  reboot: true
  # Power off after installation
  poweroff: false
  # This is true as otherwise this doesn't install on startup
  auto: true
  # These specify folders where data will persist between reboots
  # This combined with extra-dirs-rootfs is how you create mount points that are persistent!
  # Note: the bind_mounts you need to specify each level - otherwise only the deepest one will be rw
  bind_mounts:
    - /mnt/state
  extra-dirs-rootfs:
    - /mnt/state

# Specify the bundle to use
bundles:
- targets:
  - run://quay.io/kairos/community-bundles:system-upgrade-controller_latest

# Specify system-upgrade-controller settings
suc:
  version: v0.10.0

k3s:
  enabled: true

stages:
  kairos-install.pre.before:
  - if:  '[ -e /dev/sdb ]'
    name: "Create partitions"
    commands:
      - |
        parted --script --machine -- /dev/sdb mklabel gpt
    layout:
      device:
        path: /dev/sdb
      expand_partition:
        size: 0 # All available space
      add_partitions:
        # all sizes bellow are in MB
        - fsLabel: COS_PERSISTANT_USER
          pLabel: persistent
          filesystem: "ext4"
  boot:
    - name: "mount folders on startup"
      commands:
        - sudo mount /dev/sdb1 /mnt/state
```

It might be best to explain what I'm trying to achieve at this point. I would like:
1. A second disk (sdb) on install to be formatted with a single partition taking all available space - `sdb1`
2. That disk to mount on startup to /mnt/state

## The problem
The above manages to:
1. Create the sdb1 partion
2. Not create /mnt at all
3. Fail at mounting the sdb1 partion to /mnt/state
4. k3s is however available for use.
5. htop is available.

If I change the Dockerfile that auroraboot uses to build the iso to the following:
```dockerfile
FROM quay.io/kairos/kairos-ubuntu:v2.3.3-rc1
RUN apt update && apt install htop
```
and use auroraboot in the gitlab runner to create another iso, with an identical cloud_init.yaml file I get:
1. The sdb1 partiton
2. /mnt/state created and can be written to
3. The sdb1 partition successfully mounts on startup
4. **k3s** is however NOT available for use, as its not in that image
5. htop is available.

Questions:
1. Is this a bug? 
2. Are the stage names I'm using correct? I started using those names as I saw them in the `INFO` output when I couldn't get mounts working, but now I think that's actually due to issues with any image I use that has k3s inbuilt. Perhaps if I'd started with the standard non k3s image the standard stage names would have worked too.

Any pointers at all would be welcome. Happy to try anything.

**Comment by mauromorales** [comment]
I think the issues with k3s are unrelated to your changes, I'm QAing now the latest RCs and see the same issue, could you try with v2.3.2?

Regarding the partitions, maybe @Itxaka knows best

**Reply by mod35** [reply]
Thanks for getting back to me.
Any chance I can trouble you for a link to the docker image you want me to try?
I can only see 2.3.1 style images on the 3 different ubuntu variants listed here:

https://kairos.io/docs/reference/image_matrix/

For example:
https://quay.io/repository/kairos/kairos-ubuntu?tab=tags

I've attempted it with 2.3.1x, 2.2.2x (the k3s variants) and the 2.3.x release candidate ones which worked well, but don't have k3s.

**Reply by mauromorales** [reply]
Sorry, you're right, there's no v2.3.2 release for standard images, it would need to be one of the 2.3.1 e.g. `quay.io/kairos/kairos-ubuntu:v2.3.1-k3sv1.27.3-k3s1`

**Reply by mauromorales** [reply]
ah I see from your first message you actually had tried that ... so just to clarify, I think k3s might be broken with the RCs and should be working properly with 2.3.1-x ... but that doesn't address any of the other issues you're mentioning

**Comment by Itxaka** [comment, marked as answer]
**Note that the `extra-dirs-rootfs` option will only available in Kairos 2.4.X so this will only work with an image built from master** 

Unfortunately our docs are not versioned yet and the latest ones being served currently on kairos.io/docs refer to master :man_facepalming: so this is not valid for 2.3.X versions. You would need to build an iso from master directly to get that option...


Otherwise:

Umm, this is an interesting use of the layout plugin :D
It was never intended to be used in a different disk than the actual install disk so Im not sure how would it behave in that scenario to be honest.

@mod35 some questions:
 - Im guessing your /dev/sda has already all the kairos partitions prepared already?
 - is /dev/sda being shared with something else? Why the no-format?
 - Do you need /dev/sdb to have 1 partition or can use the full disk? 


You should be pretty close here to make it work for your scenario, I would not use the layout plugin as that was meant just for modification of the first so no idea if that would work. 

Here is a cloud-config that might work:


```
#cloud-config

hostname: kairos
users:
- name: kairos
  # Change to your pass here
  passwd: redacted
  ssh_authorized_keys:
  # Replace with your github user and un-comment the line below:
  - redacted

# The install block is to drive automatic installations without user interaction.
install:
  # Make sure the installer won't delete our custom partitions
  no-format: true
  # Device for automated installs
  device: "/dev/sda"
  # Reboot after installation
  reboot: true
  # Power off after installation
  poweroff: false
  # This is true as otherwise this doesn't install on startup
  auto: true
  # These creates dirs in the rootfs during install
  extra-dirs-rootfs:
    - /mnt/state

# Needed here so they will be created during upgrade as well
upgrade:
  extra-dirs-rootfs:
    - /mnt/state

# Needed here so they will be created during reset as well
reset:
  extra-dirs-rootfs:
    - /mnt/state
 
# Specify the bundle to use
bundles:
- targets:
  - run://quay.io/kairos/community-bundles:system-upgrade-controller_latest

# Specify system-upgrade-controller settings
suc:
  version: v0.10.0

k3s:
  enabled: true

stages:
  after-install: # Wipes extra disk and creates the data dir after install inside the final system chroot
    - name: "Wipe the extra disk, used for data"
      commands:
        - wipefs -a /dev/sdb
    # Formats the disk ONLY after-install and just once. Extra checks can be added here, so we don't reformat it
    - name: "Format the extra disk"
      commands:
        - mkfs.ext4 -F /dev/sdb
  boot:
    # Mounts the disk under the /mnt/state dir during boot with RW. Extra options can be added to the mount here
    - name: "Mount /dev/sdb under /mnt/state"
      commands:
        - mount -o rw /dev/sdb /mnt/state
```


This will wipe the disk and format it in ext4 just after install, so its just done once. Then on each boot it will mount it.
This has been tested before so it should work as expected. This just uses the full disk as block device, no partitions on it.
