### DISCUSSION TITLE
failed to build custom image for RPI4

### DISCUSSION THREAD

**Discussion by fafarun** [kairos-io/kairos#1815] [Q&A] [answered]
Hi,

I tried to build custom image for RPI4, but I hase some issues. 
My RPI4 node is used a 1To SSD disk (usb-data connector). 

I follow the documentation : https://kairos.io/docs/installation/raspberry/
In the example, the partition size are too small to start k3s server. 

I tried to change this value, with a cloud-init config like here :  
But nothing append on the node. 
Where Can I find logs about cloud-init on kairos ? 

Next, I tried to change the value in the osbuilder-tools : like this
```
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Script header accepted.
#!/bin/bash

#download kairosctl
curl -L https://github.com/kairos-io/provider-kairos/releases/download/v2.2.1/kairosctl-.v2.2.1-.linux-.amd64.tar.gz -o - | tar -xvzf - -C .
sudo install kairosctl /usr/bin/kairosctl

# Download the Kairos image locally
#IMAGE=quay.io/kairos/kairos-alpine-arm-rpi-img:v2.3.1-k3sv1.27.3-k3s1
IMAGE=quay.io/kairos/kairos-opensuse-leap-arm-rpi:v2.2.1-k3sv1.26.4-k3s1
docker pull $IMAGE
# Validate the configuration file
kairosctl validate cloud-config.yaml
# Customize it
mkdir -p build
docker run -v $PWD:/HERE \
 -v /var/run/docker.sock:/var/run/docker.sock \
 --privileged -i --rm \
 --entrypoint=/build-arm-image.sh quay.io/kairos/osbuilder-tools:v0.8.6 \
 --use-lvm \
 --model rpi4 \
 --state-partition-size 26200 \
 --recovery-partition-size 4200 \
 --size 15200 \
 --images-size 200000 \
 --local \
 --config /HERE/cloud-config.yaml \
 --docker-image $IMAGE /HERE/build/out.img
```

But with this configuration, the build job failed : 
```

New situation:
Disklabel type: gpt
Disk identifier: C726A424-964A-8E4A-87CF-E26C34151BEE

The partition table has been altered.
Syncing disks.
+ sgdisk -n 1:8192:+96M -c 1:EFI -t 1:0c00 /HERE/build/out.img
Setting name!
partNum is 0
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
+ sgdisk -n 2:0:+26200M -c 2:state -t 2:8300 /HERE/build/out.img
Setting name!
partNum is 1
Could not create partition 2 from 204800 to 53862399
Unable to set partition 2's name to 'state'!
Could not change partition 2's type code to 8300!
Error encountered; not saving changes.
+ cleanup
+ sync
+ sync
+ sleep 5
+ sync
+ '[' -n /tmp/arm-builder.UDnCTvoMXS ']'
+ rm -rf /tmp/arm-builder.UDnCTvoMXS
+ '[' -n /tmp/arm-builder.wINEuGvEXE ']'
+ rm -rf /tmp/arm-builder.wINEuGvEXE
+ '[' -n /tmp/arm-builder.hv55mE6U0a ']'
+ rm -rf /tmp/arm-builder.hv55mE6U0a
+ '[' -n /tmp/arm-builder.jJBR9rn5tL ']'
+ umount /tmp/arm-builder.jJBR9rn5tL
umount: /tmp/arm-builder.jJBR9rn5tL: not mounted.
+ true
+ umount /dev/loop2
umount: /dev/loop2: not mounted.
+ true
+ rm -rf /tmp/arm-builder.jJBR9rn5tL
+ '[' -n /tmp/arm-builder.mrn9t3F16W ']'
+ rm -rf /tmp/arm-builder.mrn9t3F16W
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ losetup -D /dev/loop2
+ dmsetup remove KairosVG-oem
device-mapper: remove ioctl on KairosVG-oem  failed: No such device or address
Command failed.
+ true
+ dmsetup remove KairosVG-recovery
device-mapper: remove ioctl on KairosVG-recovery  failed: No such device or address
Command failed.
+ true
```

Here my cloud-init file : 
```
#cloud-config

install:
  auto: true
  device: "auto"
  extra-partitions:
    - name: storage
      label: storage
      size: 0
      fs: ext4

  reboot: true
# bundles:
  # This bundle needs to run after-install as it consumes assets from the LiveCD
  # which is not accessible otherwise at the first boot (there is no live-cd with any bundle.tar)
 #- targets:
 #  - run:///run/initramfs/live/bundle.tar
 #  local_file: true

# Define the user accounts on the node.
users:
  - name: "kairos"                       # The username for the user.
    passwd: "kairos"                      # The password for the user.
    ssh_authorized_keys:                  # A list of SSH keys to add to the user's authorized keys.
      - 'ssh-rsa remove_key             # A key from the user's GitHub account.
ssh_pwauth: False  ## This line enables ssh password authentication
k3s:
  enabled: true
```

Someone can help me to understand how I can generate a custom image to RPI4.

**Comment by jimmykarily** [comment, marked as answer]
rpi4 automatic partition expansion will be fixed in the upcoming 2.4.0 release. The relevant PR: https://github.com/kairos-io/packages/pull/398

You build may be failing because of garbage devices left behind from previous builds or you may needs to reboot or run partprobe or something.

**Comment by fafarun** [comment]
Thanks for your response. 
I need to wait the 2.4 to extend a partition? 
Finally with this new build, I build my image with a large partition. 
```
docker run -v $PWD:/HERE \
 -v $PWD/tmp:/tmp \
 -v /var/run/docker.sock:/var/run/docker.sock \
 --privileged -i --rm \
 --entrypoint=/build-arm-image.sh quay.io/kairos/osbuilder-tools:v0.8.6 \
 --use-lvm \
 --model rpi4 \
 --state-partition-size 26200 \
 --recovery-partition-size 4200 \
 --size 35000 \
 --images-size 30000 \
 --local \
 --config /HERE/cloud-config.yaml \
 --docker-image $IMAGE /HERE/build/out.img
```
But the overlay /var is steel with 2go. How can I manage this partition ? 

The cloud-init with extend partition still not working : 
```
install:
  auto: true
  device: "auto"
  extra-partitions:
    - name: storage
      label: storage
      size: 0
      fs: ext4
```
