### DISCUSSION TITLE
Allow the kairos config to specify configuration for specific nodes

### DISCUSSION THREAD

**Discussion by jimmykarily** [kairos-io/kairos#1980] [Ideas]
Using edgevpn, it's possible to have a fully automated HA installation of a Kairos cluster. The alternative is described here: https://kairos.io/docs/examples/ha/ and it requires a different kairos config per node. It would be possible and maybe better if the kairos-config could include the configuration for more than one node, by allowing each node to select their own section. E.g.

```
mynode:
  k3s:
    enabled: true
mynode2:
  k3s-agent:
    enabled: true
```

where mynode and mynode2 would be either hostnames or ip addresses or something else that would allow each node to figure out which configuration applies to them. The rest of the config would stay the same. I'm just suggesting that we can introduce an additional section that will only be merged with the rest of the config using something unique to each host. It should be easy to implement and would allow us to have one config file for the whole cluster, even if specific to those nodes.

We could make the selection even smarter so that it's not hardcoded. E.g. instead of a key like mynode we could have a heuristic like:

```
if: "script that checks if the IP address is in a specific range"
  k3s:
    enabled: true
```
(pseudo code)

This way, one could use custom scripts and cloud provider configuration to decide which nodes are masters and which workers. But that can be done later

**Comment by mauromorales** [comment]
My yip skills are subpar so I'm not sure if what I will say makes sense, but couldn't we already do that by using an `if` statement? Something like:

```
- if $hostname == mynode || $ip == 1.1.1.1
   k3s:
     enabled: true
- if $hostname == myothernode || $ip == 1.0.1.0
   k3s-agent:
     enabled: true
```
