### DISCUSSION TITLE
How add bundles on raspberry pi K3s

### DISCUSSION THREAD

**Discussion by fafarun** [kairos-io/kairos#2016] [Q&A]
I deploy a K3s cluster on rpi4 with cloud-init. 
The cluster work. I want to add a bundle on my cluster. 

I edit the `/oem/userdata.yaml`file to add : 

I tried with `install`or `after-install`, I didn't see any pod cert-manager on my cluster. 

```
# Specify the bundle to use
  after-install:
    bundles:
      - targets:
        - run://quay.io/kairos/community-bundles:cert-manager_latest

# Specify cert-manager settings
certManager:
  version: v1.11.0
```

Why this not works ? How can I add a bundle during the day-2 of my RPI4 cluster K3s ? 

I use kairos 2.4.1 on opensuse. 

I tried to find some logs, but I  didn't see nothing in the. `/var/log/kairos/kairos-agent`.
