### DISCUSSION TITLE
Stuck on creating iso file (not seeing changes from cloud-config

### DISCUSSION THREAD

**Discussion by andre-passos-asml** [kairos-io/kairos#2254] [Q&A]
Hi all, 

I am trying to build an iso from an ubuntu with kairos. 
I use the following docker file: https://github.com/vadimzharov/k8s-kairos-deploy/blob/main/Dockerfile.00

Then I run the following commands:
docker build -t registry/kairos/kairos:v0.0.1 .

My config.yaml is like this: https://github.com/vadimzharov/k8s-kairos-deploy/blob/main/kairos_config_master.yaml
The last step should generate a file in /etc/kubernetes/kubeadm-config.yaml

```
docker run -v "$PWD"/config.yaml:/config.yaml \
                    -v "$PWD"/build:/tmp/auroraboot \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    --rm -ti quay.io/kairos/auroraboot \
                    --set container_image=docker://registry/kairos/kairos:v0.0.1 \
                    --set "disable_http_server=true" \
                    --set "disable_netboot=true" \
                    --cloud-config /config.yaml \
                    --set "state_dir=/tmp/auroraboot" -d
```

My iso file is generated. Then I copied to sudo cp build/iso/kairos.iso /var/lib/libvirt/images/
When I boot the machine using this command:
sudo virt-install --name k8s-master --memory 4096 --vcpus 2 --disk size=25 --cdrom /var/lib/libvirt/images/kairos.iso --os-variant ubuntu20.04 --nographics

I see that the file: /etc/kubernetes/kubeadm-config.yaml is not written like I specified on the cloud-config. 
Any idea of what I might be doing wrong? 

Also according to your documentation a .custom.iso should be generated. However I don't see it. Can that be the reason? 

Thanks in advance.

**Comment by HasseJohansen** [comment]
For me I see the customized iso(the one with the embedded cloud.config) in build/build/kairos.iso.custom.iso

**Reply by andre-passos-asml** [reply]
I guess the auroraboot container is responsible for this. This is the version I have:
adebrito@dev-adebrito:~/code/$ docker pull quay.io/kairos/auroraboot
Using default tag: latest
latest: Pulling from kairos/auroraboot
Digest: sha256:1d773955930a0bb40217005aa5dd8ff93eaa7e14991fa341eee682524ea2ada9
Status: Image is up to date for quay.io/kairos/auroraboot:latest
quay.io/kairos/auroraboot:latest

Is this the same version you have?

**Reply by HasseJohansen** [reply]
I am not sure of that, because I needed to build my own container with my own version of Auroraboot(I probably just picked latest from git). Because I needed a pixiecore with newer ipxe drivers to netboot

I am using this Auroraboot commit 4dc700c71230c1c5af379ab10b8364fdfcf7d8d5

As far as I remember I also had problem getting the kairos.iso.custom.iso to start with. I will just retest with the official container image

**Reply by HasseJohansen** [reply]
The command I use which does builds the custom.iso is this
```
docker run --rm -ti -v ./config.yaml:/config.yaml -v "$PWD"/2.5.0-ubuntu-23.10-build:/tmp/auroraboot --net host hassejohansen/auroraboot --set "artifact_version=v2.5.0-k3sv1.29.0+k3s1" --set "release_version=v2.5.0" --set "flavor=ubuntu" --set "flavor_release=23.10" --set "variant=standard" --set "repository=kairos-io/kairos" --set "state_dir=/tmp/auroraboot" --cloud-config /config.yaml
```

But you should probably not trust running my image

**Reply by andre-passos-asml** [reply]
Your settings and commands are completely different from mine. I am still  not able to get custom.iso.

**Reply by andre-passos-asml** [reply]
I can now reproduce it with an example on the documentation. I will create an issue.

**Reply by andre-passos-asml** [reply]
If I run the same example as here: https://kairos.io/docs/reference/auroraboot/#2-create-an-offline-iso

```
ls 
# config.yaml
Build the ISO:

docker run -v "$PWD"/config.yaml:/config.yaml \
                    -v "$PWD"/build:/tmp/auroraboot \
                    --rm -ti quay.io/kairos/auroraboot \
                    --set container_image=quay.io/kairos/opensuse:leap-15.5-core-amd64-generic-v2.5.0 \
                    --set "disable_http_server=true" \
                    --set "disable_netboot=true" \
                    --cloud-config /config.yaml \
                    --set "state_dir=/tmp/auroraboot"
Results should be available under build/ in the current directory:

sudo ls -liah build/iso
#
# total 778M
# 34648528 drwx------ 2 root root 4.0K Feb  8 16:39 .
# 34648526 drwxr-xr-x 5 root root 4.0K Feb  8 16:38 ..
# 34648529 -rw-r--r-- 1 root root  253 Feb  8 16:38 config.yaml
# 34649370 -rw-r--r-- 1 root root 389M Feb  8 16:38 kairos.iso
# 34649372 -rw-r--r-- 1 root root 389M Feb  8 16:39 kairos.iso.custom.iso
# 34649371 -rw-r--r-- 1 root root   76 Feb  8 16:39 kairos.iso.sha256
```
If I do the same on my machine I don't get the .custom.iso. 

Can someone help on this?

**Reply by HasseJohansen** [reply]
Yes. It is because I build from the official kairos GitHub artifacts instead of from the container image(that is because of caching of artifacts...it will skip if they are downloaded....the container image it will always pull because it is a new container every time). Also because I have tested all the different flavor's

I have just tried the same command you did with the official kairos ubuntu image instead. I don't a custom.iso either

So now I try the same with my newer build of Auroraboot

**Reply by HasseJohansen** [reply]
Hi Again

I just checked the generated kairos.iso doing `mount -o loop ./build/build/kairos.iso /mnt/temp/` looking at the /mnt/temp//config.yaml there has the correct content from my provided config.yaml. So I think it is a matter of outdated documentation

**Reply by HasseJohansen** [reply]
When that is said. When I am building from the official kairos GitHub artifacts(the command I use...I know you have a custom build - so another usecase).. I do get a custom.iso, and I see more steps in the process where it says that it is adding the config.yaml to the iso

I just looks like that happens in the 1 step where it generates the iso from the docker image if you use docker image artifacts

**Reply by HasseJohansen** [reply]
About it not writing the /etc/kubernetes/kubeadm-config.yaml file could be because you are writing to a readonly path

I would try something like this:
```
stages:
  after-install-chroot:
    - files:
       - content: LS0tCmFwaVNlcnZlcjoKICAgIGV4dHJhQXJnczoKICAgICAgYXV0aG9yaXphdGlvbi1tb2RlOiBOb2RlLFJCQUMKICAgIHRpbWVvdXRGb3JDb250cm9sUGxhbmU6IDRtMHMKYXBpVmVyc2lvbjoga3ViZWFkbS5rOHMuaW8vdjFiZXRhMwpjZXJ0aWZpY2F0ZXNEaXI6IC9ldGMva3ViZXJuZXRlcy9wa2kKY2x1c3Rlck5hbWU6IGs4cy11YnVudHUKY29udHJvbGxlck1hbmFnZXI6IHt9CmRuczoge30KZXRjZDoKICBsb2NhbDoKICAgIGRhdGFEaXI6IC92YXIvbGliL2V0Y2QKaW1hZ2VSZXBvc2l0b3J5OiByZWdpc3RyeS5rOHMuaW8Ka2luZDogQ2x1c3RlckNvbmZpZ3VyYXRpb24KbmV0d29ya2luZzoKICAgIGRuc0RvbWFpbjogY2x1c3Rlci5sb2NhbAogICAgcG9kU3VibmV0OiAxMC4yNDQuMC4wLzE2CiAgICBzZXJ2aWNlU3VibmV0OiAxMC45Ni4wLjAvMTgKc2NoZWR1bGVyOiB7fQotLS0KYXBpVmVyc2lvbjoga3ViZWxldC5jb25maWcuazhzLmlvL3YxYmV0YTEKa2luZDogS3ViZWxldENvbmZpZ3VyYXRpb24Kc2VydmVyVExTQm9vdHN0cmFwOiB0cnVlCi0tLQphcGlWZXJzaW9uOiBrdWJlYWRtLms4cy5pby92MWJldGEzCmtpbmQ6IEluaXRDb25maWd1cmF0aW9uCm5vZGVSZWdpc3RyYXRpb246CiAgY3JpU29ja2V0OiAiL3J1bi9jb250YWluZXJkL2NvbnRhaW5lcmQuc29jayIKLS0tCg==
         encoding: b64
         owner: root
         path: /etc/kubernetes/kubeadm-config.yaml
         permissions: "0644"
```

Formatting may be a little off

**Reply by andre-passos-asml** [reply]
Thanks. If I do the mount I also see the file. 
My file is pretty simple, it just creates a file in a folder. 
Should this be done during the boot of the iso or during the aurora build of the iso?

**Reply by HasseJohansen** [reply]
I don't think you can do while building this iso from the container image. You need to create it either in the docker image (I guess that makes sense if the content is something static)

Or else you can override it it in different stages initramfs,pre-install,after-install etc.

In the example it is after install and after chrooting to the installation(that is my guess by the name). I am using it for something entirely different:

```
stages:
  after-install-chroot:
    - files:
      - path: /etc/systemd/network/10-dhcp.network
        owner: 0
        group: 0
        permissions: 0644
        content: |
          [Match]
          Name=enp47s0
          [Link]
          Unmanaged=yes
      commands:
        - rm -f /var/lib/dbus/machine-id
        - rm -f /etc/machine-id
        - dbus-uuidgen --ensure
        - systemd-machine-id-setup
```

In my nodes there are 2 nics where I only have a cable in 1. This makes some of the kairos systems units fail(so k3s etc. won't startup). So I need to tell networkd to just ignore that interface so the systemd-netword-networkd-wait-online unit is coming up properly

The other thing is because in the official 2.5.0 artifacts there's is a hardcoded machine-id. This is troublesome if you name your nodes per the examples where they use machine-id. It makes all the nodes have the same name.  found that out the hard way when I didn't understand why edgevpn wouldn't work(for the automatic coordination of the cluster roles)
