### DISCUSSION TITLE
Is "install.image" the correct setting in a cloud-config file?

### DISCUSSION THREAD

**Discussion by bdalpe** [kairos-io/kairos#2525] [Q&A]
Something is not working correctly for me while following the [Using Kairos Core Images as an Installer
](https://kairos.io/docs/examples/core/) example guide or maybe I'm misunderstanding how to configure this setting? I am using iPXE to boot and download my cloud-config file.

Here is my iPXE file I am using to boot:
```
#!ipxe
set version v3.0.8
set flavor debian
set flavor_release bookworm
set variant core
set arch amd64
set device generic
set file_name kairos-${flavor}-${flavor_release}-${variant}-${arch}-${device}-${version}

set kernel ${file_name}-kernel
set initrd ${file_name}-initrd
set rootfs ${file_name}.squashfs
set url https://github.com/kairos-io/kairos/releases/download/${version}

# Configure interface
ifconf

imgfree
set config https://<hash>.ngrok.app/cloud-config.yaml
kernel ${url}/${kernel} initrd=${initrd} rd.neednet=1 ip=dhcp rd.live.overlay.overlayfs=1 rd.cos.disable root=live:${url}/${rootfs} netboot install-mode config_url=${config} console=tty1
initrd ${url}/${initrd}
boot
```

I set:

```
install:
  device: "auto"
  auto: true
  reboot: true
  image: "docker:ghcr.io/<repo>/<image>:<tag>"
...
```

But the installer installs the core version instead of the derivative image from `ghcr.io/<repo>/<image>:<tag>`.

If I change the `cloud-config` file to match the [Elemental docs](https://elemental.docs.rancher.com/machineregistration-reference#configelementalinstall), then everything works correctly and the system reboots into my derivative image. 🤔

```
install:
  device: "auto"
  auto: true
  reboot: true
  system:
    uri: "docker:ghcr.io/<repo>/<image>:<tag>"
...
```

Seeking some guidance here if this is a bug in Kairos or if the docs are out of date. Thanks!
