### DISCUSSION TITLE
Why Does Code Executed During the Boot Stage Run After the Network or runcmd Stages?

### DISCUSSION THREAD

**Discussion by ElectroshockGuy** [kairos-io/kairos#2570] [Q&A]
I encountered a strange issue where I found that the command code executed during the boot stage always runs after the runcmd and network stages.

Here are my experiment results:
cloud-config:

```yaml
runcmd:
    - echo "runCmd" >> /tmp/tmp
stages:
    boot:
        - commands:
          - echo "bootCmd" >> /tmp/tmp
          name: "Boot Stage"
    network:
        - commands:
          - echo "networkCmd" >> /tmp/tmp
          name: "Network Stage"
```

After the system starts, the `/tmp/tmp` file looks like this:
```
# cat /tmp/tmp
networkCmd
runCmd
bootCmd
```

os: ubuntu 22.04
kairos: 2.6.4
