### DISCUSSION TITLE
I want to install Tailscale in KairOS, what should I do?

### DISCUSSION THREAD

**Discussion by east4ming** [kairos-io/kairos#2674] [Q&A] [answered]
The distribution I chose is debian from the official kairos repositories. and tried to download and install tailscale directly from the web by installing cloud-config.yaml during the kairos installation.

yaml as follows:

```yaml
#cloud-config

hostname: "master-0"
# Define the user accounts on the node.
users:
  - name: "casey" # The username for the user.
     ...
  
stages:
  boot:
    - name: "Install tailscale"
      commands:
        - |
          set -ex
          curl -fsSL https://dl.tailscale.com/stable/tailscale_1.68.1_amd64.deb -o /tmp/tailscale.deb && dpkg -i /tmp/tailscale.deb
k3s:
  enabled: true # Set to true to enable K3s.
  args:
    - --disable "servicelb"
    - --disable-cloud-controller
    - --vpn-auth "name=tailscale,joinKey=tskey-auth-....."
```

However, the `boot` stages report an error that the relevant directory is read-only and the installation fails. What should I do?

> I've seen the author mention a tailscale success story, but I haven't found the details.

Thanks
