### DISCUSSION TITLE
Question About Custom Persistent/Mutable Root Directories and Resources for Kairos Cloud-Init (Yip)

### DISCUSSION THREAD

**Discussion by AlexanderTheGrey** [kairos-io/kairos#3236] [Q&A] [answered]
I'm working with Kairos and exploring its variant of Cloud-Init. I'm currently trying to set up a persistent read-write directory directly under the root filesystem (`/`). Given that Kairos' root filesystem is immutable, I'm struggling to figure out the correct method to persist a mutable directory in `/` across reboots.

Specifically, I have these questions:

What's the correct way to configure Cloud-Init to persist a custom, read-write directory in the root filesystem across reboots?

Are there comprehensive or detailed resources available specifically for Kairos' variant of Cloud-Init (Yip)? The official documentation seems limited regarding persistence mechanisms and other details.

**Comment by Itxaka** [comment, marked as answer]
Hey @AlexanderTheGrey 

you can get this by gollowing the https://kairos.io/docs/advanced/customizing/#customizing-the-file-system-hierarchy-using-cloud-config examples for creating the dir under the rootfs and then adding your extra bind with persistent with the https://kairos.io/docs/advanced/customizing/#customizing-the-file-system-hierarchy-using-custom-mounts part

Basically something like this in you cloud config would work:

```

#cloud-config

install:
  bind_mounts: # This adds extra bind paths that will be bind mounted to the COS_PERSISTENT partition
    - /data

stages:
  after-install-chroot: # Creates the data dir after install inside the final system chroot
    - &createdatadir
      name: "Create data dir"
      commands:
        - mkdir -p /data
  # Creates the data dir after reset inside the final system chroot, just in case it's not there
  after-reset-chroot:
    - <<: *createdatadir
  # Creates the data dir after upgrade inside the final system chroot, just in case it's not there
  after-upgrade-chroot:
    - <<: *createdatadir
```
