### DISCUSSION TITLE
It is possible to disable sshd?

### DISCUSSION THREAD

**Discussion by TueDissingWork** [kairos-io/kairos#3401] [Q&A] [answered]
Hey

It is possible to disable the sshd.service during install?
Looking to hardening the VM as much as possible - and sshd isnøt needed in this setup; hence the need to disable it.

/Tue

**Comment by TueDissingWork** [comment]
I can do it when building the ISO, but is it possible to control this through cloud init?

**Comment by Itxaka** [comment, marked as answer]
Yes you should be able to do it via cloud config by using the systemctl plugin or even the commands one


just add it in any phase that you want or if you want to avoid anything enabling it somehow just add it in several phases:

```

name: "Disable SSH in all stages"
stages:
  fs:
    - name: "Disable SSH in fs stage"
      commands:
        - "systemctl disable sshd"
        - "systemctl stop sshd"
  boot:
    - name: "Disable SSH in boot stage"
      commands:
        - "systemctl disable sshd"
        - "systemctl stop sshd"
  network:
    - name: "Disable SSH in network stage"
      commands:
        - "systemctl disable sshd"
        - "systemctl stop sshd"
  reconcile:
    - name: "Disable SSH in reconcile stage"
      commands:
        - "systemctl disable sshd"
        - "systemctl stop sshd"
   ```
