### DISCUSSION TITLE
Raspberry PI 3b+ offline CPUs

### DISCUSSION THREAD

**Discussion by mordax7** [kairos-io/kairos#415] [Q&A]
I have an performance issues with my Raspberry PI 3b+ because of offline CPUs.

My setup:
* Hardware: Raspberry PI 3b+
* Image: [kairos-alpine-arm-rpi-v1.1.6-k3sv1.25.3+k3s1.img](https://github.com/kairos-io/provider-kairos/releases/download/v1.1.6/kairos-alpine-arm-rpi-v1.1.6-k3sv1.25.3+k3s1.img.xz)
* cloud-config.yml:
```yaml
#node-config
install:
  # Device for automated installs
  device: /dev/sda
  # Reboot after installation
  reboot: true
stages:
  initramfs:
    - name: User settings and hostname
      hostname: kairos-controller
      users:
        kairos:
          passwd: DEDUCTED
  network:
    - name: User settings
      authorized_keys:
        kairos:
          - github:mordax7
k3s:
  enabled: true
  args:
    - --cluster-init
    - --etcd-snapshot-schedule-cron 0 */12 * * *
    - --etcd-snapshot-retention 14
    - --etcd-snapshot-dir /var/lib/rancher/k3s/server/db/snapshots/
  env:
    K3S_TOKEN: DEDUCTED
```

When I use `lscpu` I see that 3 of my 4 CPUs are offline for some reason.:
```
lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0
  Off-line CPU(s) list:  1-3
Vendor ID:               ARM
  BIOS Vendor ID:        Unknown
  Model name:            Cortex-A53
    BIOS Model name:     Unknown  CPU @ 0.0GHz
    BIOS CPU family:     2
    Model:               4
    Thread(s) per core:  1
    Core(s) per cluster: 1
    Socket(s):           1
    Cluster(s):          1
    Stepping:            r0p4
    CPU(s) scaling MHz:  100%
    CPU max MHz:         1400.0000
    CPU min MHz:         600.0000
    BogoMIPS:            38.40
    Flags:               fp asimd evtstrm crc32 cpuid
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Not affected
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

I tried enabling them by using this command but it fails with an permission denied:
```shell
sudo su -c "echo 1 > /sys/devices/system/cpu/cpu1/online"
ash: can't create /sys/devices/system/cpu/cpu1/online: Permission denied
```

I researched a little bit and found out that I would need to set a Kernal parameter in order to allow "hot enabling/disabling" the CPUs. Sadly I was not able to find the location where I could do so.

Would someone know more? 

EDIT: I also asked an acquaintance of mine to test this on his Raspberries. He experienced the same problems, so it is reproducible.
