### DISCUSSION TITLE
Kairos scope

### DISCUSSION THREAD

**Discussion by hailrend** [kairos-io/kairos#531] [Q&A] [answered]
Hi all, I have a question.
Is it possible to use Kairos to build a k8s cluster that lyes on a decentralized vpn (I saw you use edgevpn under the hood) over public internet? In other words, could I create a cluster between 2 nodes that are on different networks and can communicate only through public internet establishing in this way a vpn between these 2 nodes?

**Comment by mudler** [comment]
Hi @hailrend, yes it can!

Consider the feature is still experimental and documented [for installation is here](https://kairos.io/docs/installation/p2p/), you can find also notes on the advanced section over [here](https://kairos.io/docs/advanced/p2p/) with some (yet-to-complete) architectural notes over [here](https://kairos.io/docs/architecture/network/).

Generally, it's enough to specify a config file like the following:

```yaml
#cloud-config

hostname: "p2p-{{ trunc 4 .MachineID }}"

users:
- name: "kairos"
  passwd: "kairos"
  ssh_authorized_keys:
  - github:mudler

kairos:
 ## Generate a network token with the CLI as documented in https://kairos.io/docs/installation/p2p/#network_token
 network_token: ""
```

You can then specify the same file to multiple nodes. Nodes then will automatically connect even if in different networks and create a multi-node K3s cluster. HA is not supported yet (https://github.com/kairos-io/kairos/issues/2)
