### DISCUSSION TITLE
How to get real ip addresses?

### DISCUSSION THREAD

**Discussion by Ognian** [kairos-io/kairos#646] [Q&A]
I have a 2 node configuration: one raspberry pi 4 as worker and one amd64 node as master.
I have configured traefik the following way:
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entrypoints.web.proxyProtocol.insecure"
      - "--entrypoints.web.forwardedHeaders.insecure"
      - "--entrypoints.websecure.proxyProtocol.insecure"
      - "--entrypoints.websecure.forwardedHeaders.insecure"
    service:
      spec:
        externalTrafficPolicy: Local # default is Cluster see https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

```
and keycloak is also configured to trust the X-Forwarded-For header (by setting `proxy: edge`), but I still see all requests from 10.42.0.2...

Is there something else to configure, especially infront of traefik? p2p?

Thanks
Ognian
