### DISCUSSION TITLE
Issues with DNS configuration on Debian based release

### DISCUSSION THREAD

**Discussion by massimogallina** [kairos-io/kairos#901] [Q&A] [answered]
I am having issues using the DNS configuration option as per documentation with image kairos-debian-v1.5.1-k3sv1.26.1+k3s1.
Tested with two possible configurations:

```yaml

stages:
  initramfs:
    - files:
        - path: /etc/systemd/network/10-config.network
          permissions: 0644
          content: |
            [Match]
            Name=enp1s0

            [Network]
            Address=192.168.11.55/24
            Gateway=192.168.11.250
            DNS=192.168.1.181 8.8.8.8
```

```yaml
stages:
  boot:
    - name: "Setup dns"
      dns:
        nameservers:
        - 192.168.1.181
        - 8.8.8.8
        path: "/etc/resolv.conf"
```
 In both cases the file `/etc/resolv.conf` is not created. Instead it is a symbolic link another file (something like `run/systemd/resolve/...`) that does not exist.

**Comment by mudler** [comment]
:wave: this is due to the fact that systemd-based systems are using `systemd-resolved`, see also https://wiki.archlinux.org/title/systemd-resolved

**Comment by massimogallina** [comment]
Yes, this is what I think too. But `systemd-resolved` is disabled by default on the image.

**Reply by sdwilsh** [reply]
You should be able to enable it like the docs show for `timesyncd` as well: https://kairos.io/docs/reference/configuration/#timesyncd

If that works, a PR to update the docs would be great, but a confirmation will help confirm that worked so someone else can come along and update the docs :)

**Reply by massimogallina** [reply]
I finally had the chance to test it today, but also adding this piece of configuration it does not work:

```yaml
boot:
    - name: "Enable systemd-resolved"
       systemctl:
         enable:
         - systemd-resolved
```
