### ISSUE TITLE
:bug: Declarative vs imperative keys in the configuration

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1016]
I was using the following config and noticed that in some cases we use the declarative voice to define the state of the setup, while in others the imperative one. IMO all keys should be declarative, but the main issue is to have both mixed, because it makes it prone to errors when writing a config.

```
p2p:
  disable_dht: true #imperative
  auto:
    ha:
      enable: true #imperative
      master_nodes: 2
  network_token: "xxx"
k3s:
  enabled: true #declarative
```

**Kairos version:**
1.6.0
