### ISSUE TITLE
`kairos-agent state get boot` is "unknown" when netbooting

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1018]
Something like "netboot" would be more useful

Would be needed for this too: https://github.com/kairos-io/kairos/issues/391

I'm trying something like this:

```
stages:
  boot:
  - if:  '[ -f /dev/vda ] && (kairos-agent state get boot | grep -q livecd_boot)'
    name: "Create partitions"
    layout:
      device:
        path: /dev/vda
      add_partitions:
        - fsLabel: COS_STATE
          size: 16240 # At least 16gb
          pLabel: state
```

and I need something to filter out boot states in which we should recreate the partitions.
