### ISSUE TITLE
:book: Simplify and document use of bundles

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1020]
The current way of using bundles is not intuitive and missing documentation. One example is how the targets are an array inside of a bundle.

1. As a quick first step add the following example to the docs and maybe even extend with other parts that can be extended

```
bundles:
- targets:
  - run://quay.io/kairos/community-bundles:metallb_latest
# All the targets below are from local paths
- targets:
  - run:///run/... (from path)
  - run:///run/bundle2.tar
  local_file: true
# All the targets below are containers to be extracted to /tmp/somewhere
- targets:
  - container://...
  - container://..
  rootfs_path: /tmp/somewhere
# All the targets below are packages, taken from the kaiors repositories, extracted in /tmp/somewhere/else
- targets:
  - package://utils/k9s
    rootfs_path: "/tmp/somewhere/else"
  repository: "quay.io/kairos/packages"
```

2. Can we improve the UX of the targets installation to make it also more intuitive for v2?
