### ISSUE TITLE
Inconsistency in validation of user-groups in cloud-init

### ISSUE THREAD

**Issue by nano2007** [kairos-io/kairos#1083]
**Kairos version:**

Welcome to Kairos!

Refer to https://kairos.io for documentation.
Last login: Thu Mar  9 17:47:18 2023 from 10.61.1.75
rancher@cryptoflow:~$ cat  /etc/os-release
NAME="kairos-debian"
VERSION="v1.6.1-k3sv1.26.1+k3s1"
ID="kairos"
ID_LIKE="kairos-debian"
VERSION_ID="v1.6.1-k3sv1.26.1+k3s1"
PRETTY_NAME="kairos-debian v1.6.1-k3sv1.26.1+k3s1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
HOME_URL="https://github.com/kairos-io/provider-kairos"
IMAGE_REPO="quay.io/kairos/kairos-debian"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/provider-kairos"
VARIANT="core"
FLAVOR="opensuse-leap"

**CPU architecture, OS, and Version:**

Linux cryptoflow 6.1.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.8-1 (2023-01-29) x86_64 GNU/Linux

**Describe the bug**

I see an inconsistency in the cloud-init format for defining user-groups in kairos. As an example, if I have the following defined in /oem/66\_users.yaml:

```
#cloud-config
users:
  - name: "tester"
    passwd: "tester"
    shell: /bin/bash
    homedir: "/home/tester"
    groups: ["admin"]
```

On rebooting the box, the tester user gets created and is a member of the admin group. But if I try to validate the above yaml file using kairos-agent validate, the following error is seen:

> jsonschema: '/users/0/groups' does not validate with file:///home/tester/schema.json#/properties/users/items/$ref/properties/groups/type: expected string, but got array.

According to the kairos documentation, it should indeed be a string like below, but in this case the user is not getting added to the admin group.

```
#cloud-config
users:
  - name: "tester"
    passwd: "tester"
    shell: /bin/bash
    homedir: "/home/tester"
    groups: "admin"
```

**To Reproduce**

As described above.

**Expected behavior**

The schema used by kairos should be consistent with what cloud-init supports and it should be consistent in the system as well 

**Logs**

**Additional context**
