### ISSUE TITLE
QA kcrypt on kairos 1.5 and 1.6

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1248]
There was a report (on Slack) that kcrypt doesn't work.

Original report:
----------------------

I’m currently having issues with Encryption on both v1.5 and v1.6. We have tried v1.5 with Ubuntu and v1.6 with Open-suse and the same issue occurs. I will add the Cloud-Config to the thread.

```
#cloud-config

# Additional system users
users:
- name: "kairos"
  passwd: "kairos"
  lock_passwd: true
  groups: "admin"

# Enable K3s on the node.
k3s:
  enabled: true                         

# The install block is to drive automatic installations without user interaction.
install:
  # Device for automated installs
  # device: "/dev/nvme0n1"
  # Reboot after installation
  reboot: false
  # Power off after installation
  poweroff: true
  # Set to true when installing without Pairing
  auto: true
  # Label of partitions to encrypt
  # COS_PERSISTENT is the OS partition 
  # dedicated to user-persistent data
  encrypted_partitions:
  - COS_PERSISTENT
  grub_options:
    extra_cmdline: "rd.neednet=1"

# Kcrypt configuration block
kcrypt:
  challenger:
    challenger_server: "http://10.10.20.221:30000/"
    nv_index: ""
    c_index: ""
    tpm_device: ""

stages:
  initramfs:
    - users:
        kairos:
          groups:
            - sudo
          passwd: kairos
```

We are using kairos-challenger v0.2.3 and CRDs v0.0.13
Kcrypt logs show invalid Hash which doesnt make much sense, since the Hash is the exact same as the one configured

The TPM hash was obtained by running this
```
kairos@localhost:~> ID=$(sudo /system/discovery/kcrypt-discovery-challenger)
kairos@localhost:~> echo $ID
```

the SealedVolume:

```
apiVersion: keyserver.kairos.io/v1alpha1
kind: SealedVolume
metadata:
    name: encryption
    namespace: kairos
spec:
  TPMHash: "redacted"
  partitions:
    - label: COS_PERSISTENT
  quarantined: false
```

---------------------

let's try to reproduce on 1.5 and 1.6 . There is a chance that the kcrypt binaries being used are old ones because we failed to tag the packages.

**Comment by jimmykarily** [comment]
The challenger version used (0.2.3) has the sealed volume fix described in the commit message here: https://github.com/kairos-io/kcrypt/commit/018322ff009f36829083a1a8e8adc7e2b2219ecb
The kcrypt side of that fix was introduced in kcrypt tag 0.5.0 which is available since kairos v1.5.0 afaict.

So this should not be the reason for this issue here.

**Comment by mudler** [comment]
We can conclude that 1.5 and 1.6 had bugs around it? can we pinpoint to specific chart version that works? I guess this won't be relevant anymore with the 2.0 release, but we should be clear and close the card with what's the best course of action

**Comment by mudler** [comment]
Let's close this and track any other issue after 2.0 is released

**Comment by JPedro2** [comment]
@mudler @jimmykarily can we re-open this ticket? Still having issues encrypting the COS_PERSISTENT partition with kairos v2.0.3, using this ISO: `kairos-ubuntu-20-lts-v2.0.3-k3sv1.24.13+k3s1.iso`

We are seeing an error during install saying that the COS_PERSISTENT partition does not exist? No encryption takes place and after the machine powers off, it boots just fine without any encryption.

![1f28a02d-b155-45e2-85f3-d60717db1422](https://user-images.githubusercontent.com/22790804/236435101-03a4c26a-253d-435d-b9fe-a19026477ec5.JPG)


The cloud-init YAML is below:
```
#cloud-config

# Additional system users
users:
- name: "kairos"
  passwd: "kairos"
  lock_passwd: true

# Enable K3s on the node.
k3s:
  enabled: true                         

# The install block is to drive automatic installations without user interaction.
install:
  # Device for automated installs
  device: "/dev/nvme0n1"
  # Reboot after installation
  reboot: false
  # Power off after installation
  poweroff: true
  # Label of partitions to encrypt
  # COS_PERSISTENT is the OS partition 
  # dedicated to user-persistent data
  encrypted_partitions:
  - COS_PERSISTENT
  grub_options:
    extra_cmdline: "rd.neednet=1"

# Kcrypt configuration block
kcrypt:
  challenger:
    challenger_server: "http://10.10.20.221:30000/"
    nv_index: ""
    c_index: ""
    tpm_device: ""

stages:
  initramfs:
    - users:
        kairos:
          groups:
            - sudo
          passwd: kairos
```

There's connectivity between the node and challenger server:
```
root@localhost:/# curl -v http://10.10.20.221:30000/
*   Trying 10.10.20.221:30000...
* TCP_NODELAY set
* Connected to 10.10.20.221 (10.10.20.221) port 30000 (#0)
> GET / HTTP/1.1
> Host: 10.10.20.221:30000
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 05 May 2023 10:20:18 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host 10.10.20.221 left intact
```

**Comment by Itxaka** [comment]
2.0.3 migth have an issue identifying the proper partition due to a library update.

See, on https://github.com/jaypipes/ghw which we use to get info about partitions, there was a switch between partition.Label and partition.FilesystemLabel -> https://github.com/jaypipes/ghw/pull/316

```
The label entry in the Partition struct should correspond to the
partition label, but we were getting the FS label instead.

This patch fixes that by getting the actual partition label for the
label value and adding an extra field on the Partition struct to add the
fs label, so they are separated and clear on which is which.
```

So clearly the kcrypt binary is using `partition.Label` which used to return the proper partition `COS_PERSISTENT` but now reports a different one `persistent`

kcrypt was updated to ghw 0.10.0 during a normal bump of deps and that issue went undetected. The patch is present on [v0.5.2](https://github.com/kairos-io/kcrypt/releases/tag/v0.5.2).

So in this line: https://github.com/kairos-io/kcrypt/blob/v0.5.2/main.go#LL166C11-L166C11 we are checking `persistent` against `COS_PERSISTENT` so it will never find the persistent partition and will never encrypt.

@JPedro2 As a workaround, you migth be able to set the `persistent` value in your config and see if that matches correctly and encrypts the persistent partition:

```
install:
  encrypted_partitions:
  - persistent
```


Good news is that this should be fixed on `kcrypt 0.6.0-rc2` and everything up to date with the new label/filesystemlabel :D

**Comment by Itxaka** [comment]
@JPedro2 In any case, we DONT recommend you encrypt your partitions now, unless its for testing only.

Once 2.1.0 is released with this fixed, your partitions will have a passphrase that was generated with a wrong label and that wont work once we fix the label issue. So on upgrade, unlocking your partitions will fail and you would need to reinstall the whole thing.

**Comment by Itxaka** [comment]
@JPedro2 Seeing that this is a big issue as basically encryption is broken AND anything installed on 2.0.X would need an upgrade path to the fixed packages, I would say that the release will be closer than expected, even maybe with a backport and a minor patch release to 2.0.4 to fix this.

I will bring this on the meeting on monday to discuss with the team and update you when we know. Unfortunately kcrypt 0.6.0 brings too many changes to make it a patch release so probably a backport to fix that will be in the works and that should release pretty soon-ish :D

**Comment by JPedro2** [comment]
@Itxaka thank you! Appreciate it, please let me know and we can go from there :)
I will keep you posted on the workaround - most probably on Monday too

**Comment by JPedro2** [comment]
@Itxaka We've applied the workaround as recommended and tried the install again and we are now seeing another error:

![image (14)](https://user-images.githubusercontent.com/22790804/236675484-b2c6085e-fe3f-4a2e-84fc-c3bb5b7f0802.png)

This is weird because when running the command below on the node, we get the TPM hash without any issues:
```
ID=$(sudo /system/discovery/kcrypt-discovery-challenger)
```

Any recommendations?

**Comment by JPedro2** [comment]
@Itxaka another question, since kcrypt is reporting the `persistent` label instead of `COS_PERSISTENT`, I'm assuming that the `SealedVolume` on the KMS needs to change to the below?
```
apiVersion: keyserver.kairos.io/v1alpha1
kind: SealedVolume
metadata:
    name: test2
    namespace: default
spec:
  TPMHash: <redacted>
  partitions:
    - label: persistent
  quarantined: false
EOF
```
