### ISSUE TITLE
:bug: Validator shows warning on missing users, but it's present in the cloud-config

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#1254]
On installation using the Web UI (and I also think CLI) with the following cloud-config:

```
#cloud-config
hostname: nuc-{{ trunc 4 .MachineID }}
k3s:
    enabled: true
users:
    - name: kairos
      ssh_authorized_keys:
        - github:mudler
```

shows the following warning:

```
WARNING: jsonschema: '' does not validate with file:///schema.json#/required: missing properties: 'users'
```
