### ISSUE TITLE
:bug: Invalid configs with v2.0.0-rc*

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1255]
**Kairos version:**
v2.0.0-rc*

**CPU architecture, OS, and Version:**

**Describe the bug**
Seems installation with webui are broken (maybe not only affecting webui).

The collector seems to not write down correctly the config supplied by the user.

Input config for installation:

```yaml
#cloud-config
hostname: nuc-{{ trunc 4 .MachineID }}
k3s:
    enabled: true
users:
    - name: kairos
      ssh_authorized_keys:
        - github:mudler
 ```

The config file after install was the following (in `/oem`):

```yaml
#cloud-config

BOOT_IMAGE: (hd0)/boot/kernel
cdroot: true
console: ttyS0
net:
  ifnames: "1"
nodepair:
  enable: true
nomodeset: true
rd:
  cos:
    disable: true
  live:
    dir: /
    squashimg: rootfs.squashfs
root: live:CDLABEL=COS_LIVE
selinux: "0"
vga: "795"
```

few things to note here:
- the previous code (before the collector was introduced) was saving *only* what was mapped to the config structure from the cmdline, so you don't end up mixing bootargs in the cloud config file that are not in any structure (we can't set there k3s settings for instance, but it is enough specifying a remote `config_url` to fetch)
- there are ONLY cmdline configs in there now - the user config is completely discarded
- there are mixtures of extra cmdlines which are not pertinent to the installation

**To Reproduce**
Get an ISO (I've tested with  kairos-opensuse-leap-v2.0.0-rc4-k3sv1.23.17+k3s1.iso ) and try to install from the WebUI

**Expected behavior**
To have

```yaml
#cloud-config
hostname: nuc-{{ trunc 4 .MachineID }}
k3s:
    enabled: true
users:
    - name: kairos
      ssh_authorized_keys:
        - github:mudler
 ```

In the /oem files

**Logs**

**Additional context**
This is high prio, as currently blocks https://github.com/kairos-io/kairos/issues/754

**Comment by mauromorales** [comment]
It's worth noting that the installation via the UI as mentioned looses the specified cloud-config, but installing via registration or manual installation does include it. This means we probably have 2 bugs there, one for the cmdline and one for the WebUI

```
#cloud-config
BOOT_IMAGE: (cd)/boot/kernel
cdroot: true
console: ttyS0
hostname: nuc-{{ trunc 4 .MachineID }}
net:
  ifnames: "1"
nodepair:
  enable: true
nomodeset: true
rd:
  cos:
    disable: true
  live:
    dir: /
    squashimg: rootfs.squashfs
root: live:CDLABEL=COS_LIVE
selinux: "0"
users:
- name: kairos
  passwd: kairos
  ssh_authorized_keys:
  - github:mauromorales
vga: "795"
```
