### ISSUE TITLE
No disk space left on device even trying to change size in /etc/elemental/config.yaml

### ISSUE THREAD

**Issue by cristian98149** [kairos-io/kairos#1265]
**Kairos version:**

NAME="kairos-ubuntu"
VERSION="v1.6.1-k3sv1.26.1+k3s1"
ID="kairos"
ID_LIKE="kairos-ubuntu"
VERSION_ID="v1.6.1-k3sv1.26.1+k3s1"
PRETTY_NAME="kairos-ubuntu v1.6.1-k3sv1.26.1+k3s1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
HOME_URL="https://github.com/kairos-io/provider-kairos"
IMAGE_REPO="quay.io/kairos/kairos-ubuntu"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/provider-kairos"
VARIANT="core"
FLAVOR="opensuse-leap

**CPU architecture, OS, and Version:**

Linux localhost 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**

I've seen [here](https://github.com/kairos-io/kairos/issues/1025) that when the custom image to install is bigger than 3GB, size specified in /etc/elemental/config,yaml file needs to be modified.

I'm installing a 3.5GB custom image using image field in install cloud-init declaration. So, I've created an .iso image using aurora boot with a mounted cloud-init file that create a user and in before-install stage I've used files instruction in order to change /etc/elemental/config.yaml content but this doesn't work as expected and the error no disk space left on device is returned when image pulling is terminated and installation starts.

mounted cloud-init file:
```
#cloud-config

install:
  auto: true
  device: "auto"
  reboot: true
  image: "MYCUSTOMIMAGE"

stages:
  boot:
    - name: "Setup users"
      users:
        kairos:                       # The username for the user.
          passwd: "kairos"                      # The password for the user.
  before-install:
    - name: "Increase elemental image size"
      files:
        - path: /etc/elemental/config.yaml
          content: |
            install:
              grub-entry-name: "Kairos"
              system:
                size: 4000
              recovery-system:
                size: 4000
            upgrade:
              grub-entry-name: "Kairos"
              recovery-system:
                size: 4000
              system:
                size: 4000
            reset:
              grub-entry-name: "Kairos"
              system:
                size: 4000
``` 

**Expected behavior**

I need to have a .iso with 4GB size specified in /etc/elemental/config.yaml in order to install a 3.4GB custom image.

**Comment by cristian98149** [comment]
Hi @mudler,
I've tried to add the following configuration as indicated in #209 but I get the same error.

Lines added to cloud-init files (I've just changed the device that in my case is /dev/sda):
```
stages:
  boot:
  # TODO: check which device exists
  - if:  '[ -e /dev/sda ] && (kairos-agent state get boot | grep -q unknown)'
    name: "Create partitions"
    commands:
      - |
        parted --script --machine -- /dev/sda mklabel msdos
    layout:
      device:
        path: /dev/sda
      add_partitions:
        - fsLabel: COS_STATE
          size: 16240 # At least 16gb
          pLabel: state
```

**Comment by Itxaka** [comment]
You could try to override the config for elemental to set the partition sizes in order to increase the COS_STATE partition, see https://github.com/kairos-io/elemental-cli/blob/main/config.yaml.example#L26

And then  also override the image size https://github.com/kairos-io/elemental-cli/blob/main/config.yaml.example#L69

But, this file needs to be on the rootfs that its gonna be installed, as before-install runs as part of the elemental lifecicle, it means that it has loaded the values already in memory so even if you change it there, it wont work.


Let me have a quick look to see how if this can be overriden easily

**Comment by Itxaka** [comment]
blergh, no impossible because we pass our own custom elemental config to the installer.....this will go away once we merge the confgi and elemental back into the agent so we can have our default config and then users can override it somehow :/

**Comment by jimmykarily** [comment]
This PR should fix custom partitioning as soon as it's merged: https://github.com/kairos-io/kairos-agent/pull/32

**Comment by franzudev** [comment]
I've got the same problem, solved by using the elemental object `install.system` and set the partition size of 16GB in my case

```yaml
#cloud-config

install:
  system:
    label: COS_ACTIVE
    size: 16384
    fs: ext4
  auto: true
  device: "auto"
  reboot: true
  image: "MYCUSTOMIMAGE"
```
