### ISSUE TITLE
:bug: Reset doesnt work on rpi

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1486]
**Kairos version:**
master

**CPU architecture, OS, and Version:**
rpi

**Describe the bug**
Reset doesnt work on rpi as we cannot infer where the recovery/oem partitions are, becuase they are mounted on LVM and ghw doesnt work with lvm

**To Reproduce**
enter recovery on rpi and try to reset, it will fail

**Expected behavior**
it works

**Logs**

**Additional context**
there is also the state.yaml which hints the installer where the partitions are but that is generated on installation and Im not sure if that would work.

Fix is fixing the sdk so it searches for lvm partitions as well and tries to identify them

**Comment by jimmykarily** [comment]
With [this PR](https://github.com/kairos-io/kairos-sdk/pull/28) now merged, let's give it a retry (we need to bump kairos-agent to a version that includes the fix, or try that locally first).

**Comment by jimmykarily** [comment]
[`kairos` is using the `main` branch of kairos-agent](https://github.com/kairos-io/kairos/blob/1eaf89b66e12f549bf1aafade5ea0b4e9463a077/Earthfile#L310) by default. And `kairos-agent` `main` [already points to the kairos-sdk `0.0.7`](https://github.com/kairos-io/kairos-agent/blob/14e562bb169be9525b572f928ad6f74313ee7340/go.mod#L17) which has the fix. So building from `kairos` main branch should be enough to get the fix in. I'll give it a try.

**Comment by jimmykarily** [comment]
I see 3 issues:

1. The persistent partition didn't expand after first boot. The rootfs.after stage didn't seem to run at all (https://github.com/kairos-io/kairos/blob/b8c7f6dee46c1ec8ce3f4968c24c7c6ccbcf7925/overlay/files/system/oem/00_rootfs.yaml#L151)
2. When booting into recovery, I see an error about persistent partition not being found (I got to grab the text on the next try)
3. running `kairos-agent reset` produces errors:

```
WARNING: jsonschema: '' does not validate with file:///home/kairos/schema.json#/required: missing properties: 'users'
INFO[2023-06-13T09:55:05Z] kairos-agent version v2.1.3                  
WARN[2023-06-13T09:55:05Z] failed reading installation state: open /run/initramfs/cos-state/state.yaml: no such file or directory 
failed initializing reset spec: recovery partition not found
```

**Comment by Itxaka** [comment]
> I see 3 issues:
> 
>     1. The persistent partition didn't expand after first boot. The rootfs.after stage didn't seem to run at all (https://github.com/kairos-io/kairos/blob/b8c7f6dee46c1ec8ce3f4968c24c7c6ccbcf7925/overlay/files/system/oem/00_rootfs.yaml#L151
>        )
> 
>     2. When booting into recovery, I see an error about persistent partition not being found (I got to grab the text on the next try)
> 
>     3. running `kairos-agent reset` produces errors:
> 
> 
> ```
> WARNING: jsonschema: '' does not validate with file:///home/kairos/schema.json#/required: missing properties: 'users'
> INFO[2023-06-13T09:55:05Z] kairos-agent version v2.1.3                  
> WARN[2023-06-13T09:55:05Z] failed reading installation state: open /run/initramfs/cos-state/state.yaml: no such file or directory 
> failed initializing reset spec: recovery partition not found
> ```

For 1:
 Can you paste the /run/immucore/* logs?


For 3:

Can you paste the `kairos-agent state` output? I thougth this should be fixed as I tested it on an lvm system, and it returned the proper partition...:sob: also the `kairos-agent version --long` ?

**Comment by jimmykarily** [comment]
1. is actually [this known bug](https://github.com/kairos-io/kairos/issues/1448#issuecomment-1582369367) . I thought we merged a fix but turns out we didn't. Let's do that after the release.

I will try your suggestion for 3. now

**Comment by jimmykarily** [comment]
This is `kairos-agent state` output (while in normal boot):

```
kairos@localhost:~> kairos-agent state
uuid: c310be105cacb6597368ba9e642eb452-localhost
persistent:
    mounted: true
    name: /dev/mmcblk0p4
    label: unknown
    filesystemlabel: COS_PERSISTENT
    mount_point: /usr/local
    size_bytes: 67108864
    type: ext4
    read_only: false
    found: true
    uuid: unknown
recovery:
    mounted: false
    name: /dev/mapper/KairosVG-recovery
    label: ""
    filesystemlabel: COS_RECOVERY
    mount_point: ""
    size_bytes: 0
    type: ext4
    read_only: false
    found: true
    uuid: ""
oem:
    mounted: true
    name: /dev/mapper/KairosVG-oem
    label: ""
    filesystemlabel: COS_OEM
    mount_point: /oem
    size_bytes: 0
    type: ext4
    read_only: false
    found: true
    uuid: ""
state:
    mounted: true
    name: /dev/mmcblk0p2
    label: unknown
    filesystemlabel: COS_STATE
    mount_point: /run/initramfs/cos-state
    size_bytes: 6501171200
    type: ext4
    read_only: true
    found: true
    uuid: unknown
boot: active_boot
system:
    meta:
        version: 0.9.5
        timestamp: 2023-06-13T11:07:33.000187878Z
    node:
        hostname: localhost
        machineid: c310be105cacb6597368ba9e642eb452
        hypervisor: ""
        timezone: Etc/UTC
    os:
        name: openSUSE Leap 15.4
        vendor: opensuse-leap
        version: "15.4"
        release: ""
        architecture: ""
    kernel:
        release: 5.14.21-150400.24.63-default
        version: '#1 SMP PREEMPT_DYNAMIC Tue May 2 15:49:04 UTC 2023 (fd0cc4f)'
        architecture: aarch64
    product:
        name: rpi
        vendor: raspberrypi
        version: ""
        serial: ""
    board:
        name: rpi
        vendor: raspberrypi
        version: ""
        serial: ""
        assettag: ""
    chassis:
        type: 3
        vendor: raspberrypi
        version: ""
        serial: ""
        assettag: ""
    bios:
        vendor: U-Boot
        version: "2021.01"
        date: 04/19/2021
    cpu:
        vendor: ""
        model: ""
        speed: 0
        cache: 0
        cpus: 0
        cores: 0
        threads: 4
    memory:
        type: ""
        speed: 0
        size: 0
    storage:
        - name: mmcblk0
          driver: mmcblk
          vendor: ""
          model: ""
          serial: ""
          size: 64
    network:
        - name: eth0
          driver: bcmgenet
          macaddress: e4:5f:01:d9:c2:28
          port: tp/mii
          speed: 1000
        - name: wlan0
          driver: brcmfmac
          macaddress: e4:5f:01:d9:c2:2a
          port: ""
          speed: 0
kairos:
    flavor: opensuse-leap
    version: v2.2.0-rc7
```
and this is the version:

```
kairos@localhost:~> kairos-agent version --long
{Version:v2.1.3 GitCommit:none GoVersion:go1.20.2}
```

did you mean the `kairos-agent state` while in recovery? Does that make any difference?

**Comment by jimmykarily** [comment]
btw, while booting into recovery I grabbed the error for 2. It's about the recovery partition not persistent:

```
[   34.420177] immucore[662]:  <initramfs-hook> (background: false) (weak: false) (run: false)
[   34.450338] immucore[662]: <nil> INF Setting sentinel file to=recovery_mode
[   34.569816] immucore[662]: <nil> INF mount done options=["rw"] type=tmpfs what=tmpfs where=/tmp
[   34.683985] immucore[662]: <nil> ERR error="no such device" options=["ro"] type= what=/dev/disk/by-label/COS_RECOVERY where=/sysroot/run/initramfs/cos-state
[   36.038126][  T681] EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[   36.048711] immucore[662]: <nil> INF mount done options=["ro"] type= what=/dev/disk/by-label/COS_RECOVERY where=/sysroot/run/initramfs/cos-state
[   36.609127][  T776] loop: module loaded
[   36.620675][  T775] loop0: detected capacity change from 0 to 4096000

```

**Comment by jimmykarily** [comment]
And this is the output for `kairos-agent state` while booted into recovery:

```
kairos@cos-recovery:~> kairos-agent state
uuid: d6afb79d617105ad45af995d642eb459-cos-recovery
persistent:
    mounted: false
    name: /dev/mmcblk0p4
    label: unknown
    filesystemlabel: COS_PERSISTENT
    mount_point: ""
    size_bytes: 67108864
    type: ext4
    read_only: true
    found: true
    uuid: unknown
recovery:
    mounted: true
    name: /dev/mapper/KairosVG-recovery
    label: ""
    filesystemlabel: COS_RECOVERY
    mount_point: /run/initramfs/cos-state
    size_bytes: 0
    type: ext4
    read_only: false
    found: true
    uuid: ""
oem:
    mounted: true
    name: /dev/mapper/KairosVG-oem
    label: ""
    filesystemlabel: COS_OEM
    mount_point: /oem
    size_bytes: 0
    type: ext4
    read_only: false
    found: true
    uuid: ""
state:
    mounted: false
    name: /dev/mmcblk0p2
    label: unknown
    filesystemlabel: COS_STATE
    mount_point: ""
    size_bytes: 6501171200
    type: ext4
    read_only: true
    found: true
    uuid: unknown
boot: recovery_boot
system:
    meta:
        version: 0.9.5
        timestamp: 2023-06-13T11:13:15.000580415Z
    node:
        hostname: cos-recovery
        machineid: d6afb79d617105ad45af995d642eb459
        hypervisor: ""
        timezone: Etc/UTC
    os:
        name: openSUSE Leap 15.4
        vendor: opensuse-leap
        version: "15.4"
        release: ""
        architecture: ""
    kernel:
        release: 5.14.21-150400.24.63-default
        version: '#1 SMP PREEMPT_DYNAMIC Tue May 2 15:49:04 UTC 2023 (fd0cc4f)'
        architecture: aarch64
    product:
        name: rpi
        vendor: raspberrypi
        version: ""
        serial: ""
    board:
        name: rpi
        vendor: raspberrypi
        version: ""
        serial: ""
        assettag: ""
    chassis:
        type: 3
        vendor: raspberrypi
        version: ""
        serial: ""
        assettag: ""
    bios:
        vendor: U-Boot
        version: "2021.01"
        date: 04/19/2021
    cpu:
        vendor: ""
        model: ""
        speed: 0
        cache: 0
        cpus: 0
        cores: 0
        threads: 4
    memory:
        type: ""
        speed: 0
        size: 0
    storage:
        - name: mmcblk0
          driver: mmcblk
          vendor: ""
          model: ""
          serial: ""
          size: 64
    network:
        - name: eth0
          driver: bcmgenet
          macaddress: e4:5f:01:d9:c2:28
          port: tp/mii
          speed: 1000
        - name: wlan0
          driver: brcmfmac
          macaddress: e4:5f:01:d9:c2:2a
          port: ""
          speed: 0
kairos:
    flavor: opensuse-leap
    version: v2.2.0-rc7

```
