### ISSUE TITLE
:seedling:  Define behavior when `reboot` and `poweroff` are disabled

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1605]
**Kairos version:**
`2.3.0`

**CPU architecture, OS, and Version:**
All flavors

**Describe the enhancement**
IIRC we don't have any specific logic around when `poweroff` and `reboot` are set. And I think this causes the installer to loop indefinetly in the background. It is very confusing, because the user sees mounting/umounting messages but no clear clue of what's going on

**To Reproduce**
```yaml
#cloud-config

install:
  auto: true
  device: "auto"
  reboot: false
  
users:
- name: "kairos"
  passwd: "kairos"
  ssh_authorized_keys:
  
k3s:
  enabled: true
  args:
  - --disable=traefik,servicelb
```

**Expected behavior**
When finished, the installation should stop (and maybe print a message in the consoles?)

We can also be blocking and take the terminal and release it until the installation is finished, and display a message.

**Logs**
![image (1)](https://github.com/kairos-io/kairos/assets/2420543/8191e1bd-7593-44cd-a68c-5dc20fb69321)

**Additional context**
