### ISSUE TITLE
:seedling: CLI: apply states via API spec

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#166]
**Is your feature request related to a problem? Please describe.**
Currently Kairos has enough handles to perform state changes as: resetting, switching to a new system, push new changes and reboot, and so on so forth. But each of those has a different mechanism in place

**Describe the solution you'd like**
A common SDK/API that can be used to change state and report status from a simple API interface, similarly to Kubernetes. 
So we could do things like:

```
kairos-agent state apply -f <yaml>
```

Where the yaml could be among the lines of a kubernetes spec:
```
apiVersion: kairos/v1
kind: Configuration
spec:
  bootOptions: ["foo", "bar"]
---
apiVersion: kairos/v1
kind: Reset
spec:
  image: "image/foo/bar"
```

**Describe alternatives you've considered**
#34 

**Additional context**
#34 is similar, but applies to the config level (our current cloud-init support)
