### ISSUE TITLE
incorrect merging of cloud init files with same stages

### ISSUE THREAD

**Issue by kpiyush17** [kairos-io/kairos#1665]
**Kairos version:**

```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
KAIROS_NAME="kairos-core-ubuntu-22-lts"
KAIROS_VERSION="v2.3.0"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-core-ubuntu-22-lts"
KAIROS_VERSION_ID="v2.3.0"
KAIROS_PRETTY_NAME="kairos-core-ubuntu-22-lts v2.3.0"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/core-ubuntu-22-lts"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_VARIANT="core"
KAIROS_FLAVOR="ubuntu-22-lts"
```

**CPU architecture, OS, and Version:**

```
5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the bug**

We are seeing inconsistent behavior with the merging of cloud-init files when called through a bootstrap event.

We have two files:

80_stylus.yaml
```
stages:
  initramfs:
  - users:
      kairos:
        passwd: kairos
        groups:
        - admin
        - sudo
  - if: '[ ! -f /oem/80_stylus.yaml ]'
    name: set_inotify_max_values
    sysctl:
      fs.inotify.max_user_instances: "8192"
      fs.inotify.max_user_watches: "524288"
  - name: set_inotify_max_values
    sysctl:
      fs.inotify.max_user_instances: "8192"
      fs.inotify.max_user_watches: "524288"
```

See the if condition specifically, which is only present in this file and conditions the execution of sysctl commands:
```
  - if: '[ ! -f /oem/80_stylus.yaml ]'
    name: set_inotify_max_values
    sysctl:
      fs.inotify.max_user_instances: "8192"
      fs.inotify.max_user_watches: "524288"
``` 

Other file, 85_cluster_config.yaml
```
stages:
  initramfs:
  - commands:
    - ln -s /etc/kubernetes/admin.conf /run/kubeconfig
    files:
    - path: /etc/hosts
      permissions: 0
      owner: 0
      group: 0
      content: |
        127.0.0.1 localhost
      encoding: ""
      ownerstring: ""
    - path: /etc/kubernetes/audit-policy.yaml
      permissions: 0
      owner: 0
      group: 0
      content: |-
        apiVersion: audit.k8s.io/v1
        kind: Policy
        rules:
          - level: None
            users: ["system:kube-proxy"]
            verbs: ["watch"]
            resources:
              - group: "" # core
                resources: ["endpoints", "services", "services/status"]
          - level: None
            users: ["system:unsecured"]
            namespaces: ["kube-system"]
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["configmaps"]
          - level: None
            users: ["kubelet"] # legacy kubelet identity
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["nodes", "nodes/status"]
          - level: None
            userGroups: ["system:nodes"]
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["nodes", "nodes/status"]
          - level: None
            users:
              - system:kube-controller-manager
              - system:kube-scheduler
              - system:serviceaccount:kube-system:endpoint-controller
            verbs: ["get", "update"]
            namespaces: ["kube-system"]
            resources:
              - group: "" # core
                resources: ["endpoints"]
          - level: None
            users: ["system:apiserver"]
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["namespaces", "namespaces/status", "namespaces/finalize"]
          - level: None
            users: ["cluster-autoscaler"]
            verbs: ["get", "update"]
            namespaces: ["kube-system"]
            resources:
              - group: "" # core
                resources: ["configmaps", "endpoints"]
          # Don't log HPA fetching metrics.
          - level: None
            users:
              - system:kube-controller-manager
            verbs: ["get", "list"]
            resources:
              - group: "metrics.k8s.io"
          # Don't log these read-only URLs.
          - level: None
            nonResourceURLs:
              - /healthz*
              - /version
              - /swagger*
          # Don't log events requests.
          - level: None
            resources:
              - group: "" # core
                resources: ["events"]
          # node and pod status calls from nodes are high-volume and can be large, don't log responses for expected updates from nodes
          - level: Request
            users: ["kubelet", "system:node-problem-detector", "system:serviceaccount:kube-system:node-problem-detector"]
            verbs: ["update","patch"]
            resources:
              - group: "" # core
                resources: ["nodes/status", "pods/status"]
            omitStages:
              - "RequestReceived"
          - level: Request
            userGroups: ["system:nodes"]
            verbs: ["update","patch"]
            resources:
              - group: "" # core
                resources: ["nodes/status", "pods/status"]
            omitStages:
              - "RequestReceived"
          # deletecollection calls can be large, don't log responses for expected namespace deletions
          - level: Request
            users: ["system:serviceaccount:kube-system:namespace-controller"]
            verbs: ["deletecollection"]
            omitStages:
              - "RequestReceived"
          # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
          # so only log at the Metadata level.
          - level: Metadata
            resources:
              - group: "" # core
                resources: ["secrets", "configmaps"]
              - group: authentication.k8s.io
                resources: ["tokenreviews"]
            omitStages:
              - "RequestReceived"
          # Get repsonses can be large; skip them.
          - level: Request
            verbs: ["get", "list", "watch"]
            resources:
              - group: "" # core
              - group: "admissionregistration.k8s.io"
              - group: "apiextensions.k8s.io"
              - group: "apiregistration.k8s.io"
              - group: "apps"
              - group: "authentication.k8s.io"
              - group: "authorization.k8s.io"
              - group: "autoscaling"
              - group: "batch"
              - group: "certificates.k8s.io"
              - group: "extensions"
              - group: "metrics.k8s.io"
              - group: "networking.k8s.io"
              - group: "policy"
              - group: "rbac.authorization.k8s.io"
              - group: "settings.k8s.io"
              - group: "storage.k8s.io"
            omitStages:
              - "RequestReceived"
          # Default level for known APIs
          - level: RequestResponse
            resources:
              - group: "" # core
              - group: "admissionregistration.k8s.io"
              - group: "apiextensions.k8s.io"
              - group: "apiregistration.k8s.io"
              - group: "apps"
              - group: "authentication.k8s.io"
              - group: "authorization.k8s.io"
              - group: "autoscaling"
              - group: "batch"
              - group: "certificates.k8s.io"
              - group: "extensions"
              - group: "metrics.k8s.io"
              - group: "networking.k8s.io"
              - group: "policy"
              - group: "rbac.authorization.k8s.io"
              - group: "settings.k8s.io"
              - group: "storage.k8s.io"
            omitStages:
              - "RequestReceived"
          # Default level for all other requests.
          - level: Metadata
            omitStages:
              - "RequestReceived"
      encoding: ""
      ownerstring: ""
    sysctl:
      kernel.panic: "10"
      kernel.panic_on_oops: "1"
      vm.overcommit_memory: "1"
```

When called `kairos-agent notify agent.bootstrap` to get a event with merged data from both files, when printing the stage

```
initramfs:
  - commands:
    - ln -s /etc/kubernetes/admin.conf /run/kubeconfig
    files:
    - path: /etc/hosts
      permissions: 0
      owner: 0
      group: 0
      content: |
        127.0.0.1 localhost
      encoding: ""
      ownerstring: ""
    - path: /etc/kubernetes/audit-policy.yaml
      permissions: 0
      owner: 0
      group: 0
      content: |-
        apiVersion: audit.k8s.io/v1
        kind: Policy
        rules:
          - level: None
            users: ["system:kube-proxy"]
            verbs: ["watch"]
            resources:
              - group: "" # core
                resources: ["endpoints", "services", "services/status"]
          - level: None
            users: ["system:unsecured"]
            namespaces: ["kube-system"]
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["configmaps"]
          - level: None
            users: ["kubelet"] # legacy kubelet identity
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["nodes", "nodes/status"]
          - level: None
            userGroups: ["system:nodes"]
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["nodes", "nodes/status"]
          - level: None
            users:
              - system:kube-controller-manager
              - system:kube-scheduler
              - system:serviceaccount:kube-system:endpoint-controller
            verbs: ["get", "update"]
            namespaces: ["kube-system"]
            resources:
              - group: "" # core
                resources: ["endpoints"]
          - level: None
            users: ["system:apiserver"]
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["namespaces", "namespaces/status", "namespaces/finalize"]
          - level: None
            users: ["cluster-autoscaler"]
            verbs: ["get", "update"]
            namespaces: ["kube-system"]
            resources:
              - group: "" # core
                resources: ["configmaps", "endpoints"]
          # Don't log HPA fetching metrics.
          - level: None
            users:
              - system:kube-controller-manager
            verbs: ["get", "list"]
            resources:
              - group: "metrics.k8s.io"
          # Don't log these read-only URLs.
          - level: None
            nonResourceURLs:
              - /healthz*
              - /version
              - /swagger*
          # Don't log events requests.
          - level: None
            resources:
              - group: "" # core
                resources: ["events"]
          # node and pod status calls from nodes are high-volume and can be large, don't log responses for expected updates from nodes
          - level: Request
            users: ["kubelet", "system:node-problem-detector", "system:serviceaccount:kube-system:node-problem-detector"]
            verbs: ["update","patch"]
            resources:
              - group: "" # core
                resources: ["nodes/status", "pods/status"]
            omitStages:
              - "RequestReceived"
          - level: Request
            userGroups: ["system:nodes"]
            verbs: ["update","patch"]
            resources:
              - group: "" # core
                resources: ["nodes/status", "pods/status"]
            omitStages:
              - "RequestReceived"
          # deletecollection calls can be large, don't log responses for expected namespace deletions
          - level: Request
            users: ["system:serviceaccount:kube-system:namespace-controller"]
            verbs: ["deletecollection"]
            omitStages:
              - "RequestReceived"
          # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
          # so only log at the Metadata level.
          - level: Metadata
            resources:
              - group: "" # core
                resources: ["secrets", "configmaps"]
              - group: authentication.k8s.io
                resources: ["tokenreviews"]
            omitStages:
              - "RequestReceived"
          # Get repsonses can be large; skip them.
          - level: Request
            verbs: ["get", "list", "watch"]
            resources:
              - group: "" # core
              - group: "admissionregistration.k8s.io"
              - group: "apiextensions.k8s.io"
              - group: "apiregistration.k8s.io"
              - group: "apps"
              - group: "authentication.k8s.io"
              - group: "authorization.k8s.io"
              - group: "autoscaling"
              - group: "batch"
              - group: "certificates.k8s.io"
              - group: "extensions"
              - group: "metrics.k8s.io"
              - group: "networking.k8s.io"
              - group: "policy"
              - group: "rbac.authorization.k8s.io"
              - group: "settings.k8s.io"
              - group: "storage.k8s.io"
            omitStages:
              - "RequestReceived"
          # Default level for known APIs
          - level: RequestResponse
            resources:
              - group: "" # core
              - group: "admissionregistration.k8s.io"
              - group: "apiextensions.k8s.io"
              - group: "apiregistration.k8s.io"
              - group: "apps"
              - group: "authentication.k8s.io"
              - group: "authorization.k8s.io"
              - group: "autoscaling"
              - group: "batch"
              - group: "certificates.k8s.io"
              - group: "extensions"
              - group: "metrics.k8s.io"
              - group: "networking.k8s.io"
              - group: "policy"
              - group: "rbac.authorization.k8s.io"
              - group: "settings.k8s.io"
              - group: "storage.k8s.io"
            omitStages:
              - "RequestReceived"
          # Default level for all other requests.
          - level: Metadata
            omitStages:
              - "RequestReceived"
      encoding: ""
      ownerstring: ""
    if: '[ ! -f /oem/80_stylus.yaml ]'
    name: set_inotify_max_values
    sysctl:
      fs.inotify.max_user_instances: "8192"
      fs.inotify.max_user_watches: "524288"
      kernel.panic: "10"
      kernel.panic_on_oops: "1"
      vm.overcommit_memory: "1"
    users:
      kairos:
        passwd: kairos
        groups:
        - admin
        - sudo
  - name: set_inotify_max_values
    sysctl:
      fs.inotify.max_user_instances: "8192"
      fs.inotify.max_user_watches: "524288"
```

As seen from the output, the `if` yip condition now encapsulates every stage which was not present as part of the original files. Since now `/oem/80_stylus.yaml` is present, other stages like creating an audit-policy file didn't get executed.

Here, the kairos-agent version is 2.1.10

**To Reproduce**

**Expected behavior**

Expected behavior would be to keep the stages separate after merging also.

**Comment by Itxaka** [comment]
cc @mudler as this may have more to do with how yip and herd merge the stages together

**Comment by Itxaka** [comment]
@kpiyush17 Does the same happen if you give a name to the stage? i.e.:

```
    - name: "Kernel settings" 
      sysctl:
        kernel.panic: "10"
        kernel.panic_on_oops: "1"
        vm.overcommit_memory: "1"
```

**Comment by Itxaka** [comment]
Also, its jsut me or the whitespece of the 85 file is mangled?

You got `- files` a level under the `- commands` and `sysctl` has no `-` 

```
stages:
  initramfs:
  - commands:
    - ln -s /etc/kubernetes/admin.conf /run/kubeconfig
    files:
    ...
    sysctl:
    ...
``

**Comment by mauromorales** [comment]
the problem comes from the collector deepmerge for sure, not related to yip, I can reproduce, but I'm not exactly sure what the expected valid scenarios should be. This originated as the introduction of https://github.com/kairos-io/kairos/pull/1343/files which refrences this issue https://github.com/kairos-io/kairos/issues/1341

**Comment by mauromorales** [comment]
Here is a simpler version just to show the issue without focusing too much on the big file:

config1:

```
#cloud-config
stages:
  initramfs:
  - users:
      kairos:
        passwd: kairos
        groups:
        - admin
        - sudo
  - if: '[ ! -f /oem/80_stylus.yaml ]'
    name: set_inotify_max_values
    sysctl:
      fs.inotify.max_user_instances: "8192"
      fs.inotify.max_user_watches: "524288"
```

config2:
```
#cloud-config
stages:
  initramfs:
  - commands:
    - ln -s /etc/kubernetes/admin.conf /run/kubeconfig
    sysctl:
      kernel.panic: "10"
      kernel.panic_on_oops: "1"
      vm.overcommit_memory: "1"
```

resulting merge:

```
#cloud-config

stages:
    initramfs:
        - commands:
            - ln -s /etc/kubernetes/admin.conf /run/kubeconfig
          if: '[ ! -f /oem/80_stylus.yaml ]'
          name: set_inotify_max_values
          sysctl:
            fs.inotify.max_user_instances: "8192"
            fs.inotify.max_user_watches: "524288"
            kernel.panic: "10"
            kernel.panic_on_oops: "1"
            vm.overcommit_memory: "1"
          users:
            kairos:
                groups:
                    - admin
                    - sudo
                passwd: kairos
```

**Comment by mauromorales** [comment]
Ok, I managed to fix with simply concatenating them instead of trying to do anything more complex. I just have a question whether this is valid yip:

```
stages:
  initramfs:
    - users:
        kairos: ...
    - users:
        foo: ...
```

If it is, then #1341 would be covered and I just need to fix the tests
