### ISSUE TITLE
[Spike] Create a cloud-config that automatically resizes rpi3 and then integrate that in the rpi3 image

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1718]
Let try to automate this: https://github.com/kairos-io/kairos/issues/1637

**Comment by ci-robbot** [comment]
Triage: this landed at some point and the issue was never closed. Closing it as done, with the caveat at the end.

The cloud-config this spike asked for exists, and it is generic rather than rpi3-specific: `kairos-init/pkg/bundled/cloudconfigs/00_rootfs.yaml:96-104`.

```yaml
    - if: '[ ! -f /run/cos/recovery_mode ] && [ ! -f /run/cos/live_mode ]'
      name: "Grow persistent"
      layout:
        device:
          label: COS_PERSISTENT
        expand_partition:
          # Size 0 is required to specify all remaining space
          size: 0
```

It runs in the `rootfs` stage on every boot that is not recovery and not live, and yip's layout plugin takes `size: 0` as "all remaining space" (`Expand *Expand yaml:"expand_partition,omitempty"` in yip's schema).

And it is integrated into the rpi3 image, which was the second half of the ask. Everything under `kairos-init/pkg/bundled/cloudconfigs/` is embedded (`bundled.go:24-26`) and written into `/system/oem` by the `cloudconfigs` install step (`kairos-init/pkg/stages/steps_install.go:359-371`), which runs for every image kairos-init builds. `arm64-rpi3` is one of those, built with `raw: true` at `.github/workflows/master.yaml:160` and `.github/workflows/release.yaml:212`.

@Itxaka's 2023 objection on the sibling issue #1637, that the linked commands looked like GPT commands while "rpi supports dos only", is also void now. AuroraBoot writes raw disk images with a GPT table and a protective MBR, not msdos: `pkg/ops/rawDiskGeneration.go:758` (`// Create a GPT partition table`) and `:834-835` (`table = &gpt.Table{ProtectiveMBR: true`). So the expansion is operating on GPT on rpi too, and #1762 ("Persistent is not being expanded consistently") closed as completed back in 2023-08-29.

Caveat: this is a read of the code and the build matrix, not a boot test. I have no rpi3 to flash. If someone hits an SD card where persistent still does not fill the disk, that is a new bug in the "Grow persistent" stage rather than this missing spike, so please open it fresh with the immucore log rather than reopening here.

Related: #1637 (the docs half) closed as completed 2026-08-27.
