### ISSUE TITLE
Example wifi configuration for raspberry pi

### ISSUE THREAD

**Issue by jbalonso** [kairos-io/kairos#1729]
Wifi configuration is a common requirement `[citation needed]` for deploying kairos on raspberry pi devices. The documentation on https://kairos.io/docs/installation/raspberry/ and https://kairos.io/docs/examples/ do not give adequate guidance on doing this.

I recognize that this may vary significantly depending on the underlying distribution used, but at least `systemd`-based systems could be addressed.

**Describe the solution you'd like**
An example of wifi configuration in https://kairos.io/docs/examples/, possibly with a link from https://kairos.io/docs/installation/raspberry/

**Additional context**
The following are the pieces of my `cloud-config.yaml` that configured wifi (additional network configuration, like static IP addresses, are entirely omitted):

```yaml
stages:
  initramfs:
      - path: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
        content: |
          # This file should be generated using wpa_passphrase
          ctrl_interface=/var/run/wpa_supplicant
          ctrl_interface_group=admin
          network={
                  ssid="$SSID_GOES_HERE"
                  psk=$PSK_GOES_HERE
          }
        permissions: 0600
        owner: 0
        group: 0

  boot:
    - name: "Enabling wireless"
      commands:
      - |
          systemctl enable wpa_supplicant@wlan0
          systemctl disable wpa_supplicant
          systemctl stop wpa_supplicant || :
          systemctl start wpa_supplicant@wlan0 || :
```
