### ISSUE TITLE
Vmware provider does not work

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1733]
vmware provider has several issues:

 - Does not build on linux. The go:build directive is wrong so it only builds the unsupported part.
 - It doesnt mention that its unsupported in the log or provider name so it looks like its running but its not.
 - Once it builds and runs, it parses teh data but returns a message with MIME stuff on it, which yip doesnt understand

data that passes as example:

```
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0

--MIMEBOUNDARY
Content-Transfer-Encoding: 7bit
Content-Type: text/cloud-config
Mime-Version: 1.0

#cloud-config
stages:
  initramfs:
    - name: "Setup hostname"
      hostname: "lpul-vault-dev-0"

--MIMEBOUNDARY--
```

While yip expects it to only pass the cloud config string.
