### ISSUE TITLE
[debian] User dir not created if not specified

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1741]
**Kairos version:**
debian + standard + master

**CPU architecture, OS, and Version:**
all

**Describe the bug**
Adding an user to the cloud-config with no homedir set, does not create a home dir in debian, which results in not being able to ssh with ssh keys if they are set as the only auth method as no home dir, nowhere to copy them keys.

**To Reproduce**
Use debian iso, use the following config to install

```
#cloud-config

install:
  auto: true
  reboot: true
  device: /dev/vda

stages:
  initramfs:
    - name: "Set hostname"
      hostname: kairos-{{ trunc 4 .Random }}
    - name: "Set user and password"
      users:
        itxaka:
          groups:
            - admin
          name: itxaka
          passwd: "itxaka"
          ssh_authorized_keys:
            - "YOUROFFLINEKEYHERE"
```

**Expected behavior**

The dir to be autocreated for new users.

**Logs**

**Additional context**

Other distros does not seem to have this issues, i.e. tested with opensuse-leap and no problems
