### ISSUE TITLE
kcrypt to handle the encryption/decryption within the host

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#184]
- [x] Integrate kcrypt into `kairos-agent` configuration (which partitions to encrypt after install)
- [x] Integrate kcrypt into the stack (initramfs/binary)

Ideally the config from kairos-agent should be something among the lines of:
```yaml
install:
  encrypt_partition:
  - LABEL1
  - LABEL2
```
which should be executed as a post-install hook. This goes together with customizing partitions during install which currently can be driven by cloud-init configuration.
