### ISSUE TITLE
rpi images -> login not possible

### ISSUE THREAD

**Issue by Ognian** [kairos-io/kairos#187]
**Kairos version:**

**CPU architecture, OS, and Version:**

**Describe the bug**

raspberry pi 4 8GB boot from USB HD
Even with no config.yaml provided login on the raspberry pi is not possible (local keyboard, and monitor)
the message printed is to use kairos/kairos but this doesn't work (tried also cos and c3cos...) 

**To Reproduce**

burn image , boot and try to login

**Expected behavior**

login possible
**Logs**

**Additional context**

**Comment by Ognian** [comment]
Hi @mudler thanks for the quick answer!
Yes, i tried this too, both user with password and ssh key, but the result is the same, the pi has no ip also, so access via ssh is also not possible... rpi boot time is also very very high, maybe hw params are not properly set...

**Comment by mudler** [comment]
Can you show the config redacting sensitive fields? another option is to edit the boot menu and add "rd.cos.disable", that should get you to default kairos user

**Comment by Ognian** [comment]
```
# config options: https://kairos.io/reference/configuration
# and https://rancher.github.io/elemental-toolkit/docs/reference/cloud_init/

stages:
  initramfs:
    - name: "User settings"
      hostname: "rpi4node"
      authorized_keys:
        kairos:
          - "ssh-rsa ...
        users:
          kairos:
            passwd: "kairos"
        dns:
          path: /etc/resolv.conf
          nameservers:
            - 8.8.8.8
k3s:
  enabled: true
```

**Comment by Ludea** [comment]
I just try on Rpi3, and get same issue with custom username
```
stages:
   initramfs:
     - name: "Set user and password"
       users:
        ludea:
          passwd: "mypassword"

k3s:
  enabled: true
```

flavor : alpine
