### ISSUE TITLE
kairos-agent render templates using config as data source

### ISSUE THREAD

**Issue by wyvernzora** [kairos-io/kairos#1907]
**Is your feature request related to a problem? Please describe.**

When creating bundles, having to do shell-script based substitutions limits the templating that can be done. One the other hand, bundling a standalone templating engine into the bundle images results in bloat. It would be very nice if I could use a built-in command in `kairos-agent` to render Golang template files using config as data source.

**Describe the solution you'd like**

Imagine I can have a template file like this:
```yaml
# test-namespace.yaml
apiVersion: v1
kind: Namespace
spec:
    name: "{{ .config.testNamespace.name }}"
```
And CloudConfig like this:
```yaml
# snip

testNamespace:
    name: "Baaaa!"

# snip
```

In the bundle script, I could just do something like this:
```shell
$ kairos-agent config render --template assets/test-namespace.yaml > /var/lib/rancher/k3s/server/manifests/test-namespace.yaml
```

**Describe alternatives you've considered**

I considered the option of bundling a standalone templating utility like Gomplate into kairos, but I don't think that is the best way forward for the following reasons:
 - Gomplate comes with a lot of unnecessary features that only increase the size of images without being useful
 - Using standalone executable makes it more complicated as config now needs to be passed around

**Additional context**

None
