### ISSUE TITLE
UID/GIDs are inconsistent across reboots, causing incorrect file ownership

### ISSUE THREAD

**Issue by clanktron** [kairos-io/kairos#1920]
When rebooting my kairos system my users are regenerated with inconsistent uid/gids. This will often "shuffle" file ownership, meaning the files owned by user `foo` are now owned by `bar` and vice versa. This often locks me out of ssh since the authorized_keys file is now owned by the wrong person. I'm using a system based on `quay.io/kairos/core-ubuntu-22-lts:v2.4.1` with a few extra packages.

The cloud config file instantiates the users at the top level like so:
```
users:
 - name: clayton
   groups:
     - admin
     - docker
   lock_passwd: true
   shell: /usr/bin/fish
   ssh_authorized_keys:
     - <keys>
 - name: test
   groups:
     - admin
     - docker
   lock_passwd: true
   shell: /usr/bin/fish
   ssh_authorized_keys:
     - <keys>
 - name: git
   lock_passwd: true
   shell: /usr/bin/git-shell
   ssh_authorized_keys:
     - <keys>
```
**Before reboot**
`/etc/passwd`:
```/etc/passwd
kairos:x:65535:65535:Created by entities:/home/kairos:/bin/bash
test:x:65536:65536:Created by entities:/home/test:/usr/bin/fish
git:x:65537:65537:Created by entities:/home/git:/usr/bin/git-shell
clayton:x:65538:65538:Created by entities:/home/clayton:/usr/bin/fish
```
clayton's home dir:
```bash
$ ls -la
total 40
drwxr-xr-x  8 clayton clayton 4096 Oct 13 16:14 .
drwxr-xr-x  8 root    root    4096 Apr 18  2022 ..
-rw-r--r--  1 clayton clayton 1681 Oct 12 04:43 .bashrc
drwx------  3 clayton clayton 4096 Oct 12 04:02 .cache
drwx------ 12 clayton clayton 4096 Oct 12 04:43 .config
drwx------  4 clayton clayton 4096 Oct 12 03:50 .local
drwx------  2 clayton clayton 4096 Oct 12 03:46 .ssh
drwxr-xr-x  3 clayton clayton 4096 Oct 12 04:39 .vim
$ ls -la .ssh
total 12
drwx------ 2 clayton clayton 4096 Oct 12 03:46 ./
drwxr-xr-x 8 clayton clayton 4096 Oct 13 16:14 ../
-rw------- 1 clayton clayton  295 Oct 12 03:46 authorized_keys
```
**After reboot**
`/etc/passwd`:
```/etc/passwd
kairos:x:65535:65535:Created by entities:/home/kairos:/bin/bash
git:x:65536:65536:Created by entities:/home/git:/usr/bin/git-shell
clayton:x:65537:65537:Created by entities:/home/clayton:/usr/bin/fish
test:x:65538:65538:Created by entities:/home/test:/usr/bin/fish
```
clayton's home dir:
```bash
$ ls -la
total 40K
drwxr-xr-x  8 clayton clayton 4.0K Oct 13 16:14 .
drwxr-xr-x  8 root    root    4.0K Apr 18  2022 ..
-rw-r--r--  1 test    test    1.7K Oct 12 04:43 .bashrc
drwx------  3 test    test    4.0K Oct 12 04:02 .cache
drwx------ 12 test    test    4.0K Oct 12 04:43 .config
drwx------  4 test    test    4.0K Oct 12 03:50 .local
drwx------  2 clayton clayton 4.0K Oct 12 03:46 .ssh
drwxr-xr-x  3 test    test    4.0K Oct 12 04:39 .vim
$ ls -la .ssh
total 12
drwx------ 2 clayton clayton 4096 Oct 12 03:46 ./
drwxr-xr-x 8 clayton clayton 4096 Oct 13 16:14 ../
-rw------- 1 test    test     295 Oct 12 03:46 authorized_keys
```
After a second reboot they're shuffled again and I found my files being owned by the "git" user. Rebooted again and they're owned by the "test" user yet again...and so on.

**Comment by Itxaka** [comment]
@clanktron yes, this seems like an issue as we generate them during boot.

Maybe you can workaround by manually setting the UID of the user?
like so:

```
users:
 - name: clayton
   uid: 1001
   groups:
     - admin
     - docker
   lock_passwd: true
   shell: /usr/bin/fish
   ssh_authorized_keys:
     - <keys>
 - name: test
   usid: 1002
   groups:
     - admin
     - docker
   lock_passwd: true
   shell: /usr/bin/fish
   ssh_authorized_keys:
     - <keys>
 - name: git
   uid: 1003
   lock_passwd: true
   shell: /usr/bin/git-shell
   ssh_authorized_keys:
     - <keys>
```
