### ISSUE TITLE
[ci] kairos get-kubeconfig empty on alpine (edgevpn not working?)

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1974]
From alpine master.

os-release:
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.4
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
KAIROS_NAME="kairos-standard-alpine-3.18"
KAIROS_VERSION="v2.4.1-42-g3287a5a5-k3sv1.28.2+k3s1"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-standard-alpine-3.18"
KAIROS_VERSION_ID="v2.4.1-42-g3287a5a5-k3sv1.28.2+k3s1"
KAIROS_PRETTY_NAME="kairos-standard-alpine-3.18 v2.4.1-42-g3287a5a5-k3sv1.28.2+k3s1"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/alpine"
KAIROS_IMAGE_LABEL="v2.4.1-42-g3287a5a5-k3sv1.28.2+k3s1"
KAIROS_GITHUB_REPO="kairos-io/provider-kairos"
KAIROS_VARIANT="standard"
KAIROS_FLAVOR="alpine"
```

cloud-config:
```
#cloud-config

install:
    device: /dev/vda
k3s:
    enabled: true
name: Config generated by the installer
stages:
    initramfs:
        - users:
            kairos:
                groups:
                    - admin
                name: kairos
                passwd: kairos
```

k3s deployed correctly:

```
localhost:~$ sudo k3s kubectl get nodes
NAME        STATUS   ROLES                  AGE     VERSION
localhost   Ready    control-plane,master   9m42s   v1.28.2+k3s1
```

kairos get-kubeconfig returns empty:
```
localhost:~$ kairos get-kubeconfig

localhost:~$ 
```

role list is also empty:
```
localhost:~$ kairos role list
Node	Role
localhost:~$ 
```

**Comment by Itxaka** [comment]
umm, If Im reading this correctly we need edgevpn deployed to use that comand as it uses the edgevpn api to get it...

redeploying...

**Comment by Itxaka** [comment]
job that triggered this is: https://github.com/kairos-io/kairos/actions/runs/6671146711/job/18134131817

But that is a read hearring, its not that https is not working, its that the get-kubeconfig is empty probably becuase edgevpn is not working properly under alpine

**Comment by Itxaka** [comment]
new cloud config:

```
#cloud-config

install:
  grub_options:
    extra_cmdline: "rd.immucore.debug"

p2p:
  network_token: "b3RwOgogIGRodDoKICAgIGludGVydmFsOiA5MDAwCiAgICBrZXk6IGx4V0x6ZGZyZnJRSzVSMEU0VzhtMHdaZEtjQkoyTGVLNXdlMXJXUVByOUwKICAgIGxlbmd0aDogNDMKICBjcnlwdG86CiAgICBpbnRlcnZhbDogOTAwMAogICAga2V5OiB0a05GdUM0clFRNTM0OWdNSVliaE9RNHFHRXd4Sk5oSlc1RWQ2SFRqRzNGCiAgICBsZW5ndGg6IDQzCnJvb206IHptS3dtRHFwTXhxMnB2aGlXTmxxVEUwMmdJRmh2dFRFeHpHbENqZXNFZXMKcmVuZGV6dm91czogY0haYUF0SjYzeGNOTHZPdUcyM1dEd0s0bGkycVA1SVZaU1hGbWpSQ05vaAptZG5zOiA5dVZpUEFnd1puQ1duQ0hPVEVqVmNNb01PSGhwTDJTa1h1cXE2eklTRDY0Cm1heF9tZXNzYWdlX3NpemU6IDIwOTcxNTIwCg=="
  dns: true

stages:
  initramfs:
    - name: "Set user and password"
      users:
        kairos:
          passwd: "kairos"
    - name: "Set hostname"
      hostname: kairos-{{ trunc 4 .Random }}
```


Installed two nodes with `kairos-agent manual-install --device /dev/vda /tmp/config.yaml` nothing fancy.

Could not reproduce...... so maybe the CI is doing something different???
