### ISSUE TITLE
Allow deploying `kubevip` as a static pod

### ISSUE THREAD

**Issue by onedr0p** [kairos-io/kairos#1993]
**Is your feature request related to a problem? Please describe.**

I would like to install Cilium with eBPF however that requires kubevip to be deployed as a static pod. This is because as a static pod kubevip doesn't need a CNI to function which means Cilium can talk directly to kubevip in eBPF mode.

**Describe the solution you'd like**

Add an option in the config file to allow deploying kubevip as a static pod which would deploy kubevip as a static pod instead of a daemonset. Another option is to make kubevip a static pod by default instead of being deployed as a daemonset.

```go
type KubeVIP struct {
	Args        []string `yaml:"args,omitempty"`
	EIP         string   `yaml:"eip,omitempty"`
	ManifestURL string   `yaml:"manifest_url,omitempty"`
	Interface   string   `yaml:"interface,omitempty"`
	Enable      *bool    `yaml:"enable,omitempty"`
	StaticPod   *bool    `yaml:"enable,omitempty"`
}
```

**Describe alternatives you've considered**

I could deploy kubevip out-of-band but having this supported would be excellent.

**Additional context**

With k3s static pods can be deployed via dropping a YAML file here `/var/lib/rancher/k3s/agent/pod-manifests` with the following content...

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: kube-vip
    app.kubernetes.io/name: kube-vip
spec:
  containers:
    - name: kube-vip
      image: ghcr.io/kube-vip/kube-vip:v0.6.3
      imagePullPolicy: IfNotPresent
      args: ["manager"]
      env:
        - name: address
          value: "{{ .KubeVIP.EIP }}" # EIP choosen form config
        - name: vip_arp
          value: "true"
        - name: lb_enable
          value: "true"
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "false"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "15"
        - name: vip_renewdeadline
          value: "10"
        - name: vip_retryperiod
          value: "2"
        - name: prometheus_server
          value: :2112
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "NET_RAW"]
      volumeMounts:
        - mountPath: /etc/kubernetes/admin.conf
          name: kubeconfig
  hostAliases:
    - hostnames:
        - kubernetes
      ip: 127.0.0.1
  hostNetwork: true
  volumes:
    - name: kubeconfig
      hostPath:
        path: /etc/rancher/k3s/k3s.yaml
```
