### ISSUE TITLE
Kairos 2.4.2 doesn't seem to work with p2p

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2005]
Using this image: `kairos-opensuse-leap-15.5-standard-amd64-generic-v2.4.2-k3sv1.28.2+k3s1.iso`
with this config:

```
#cloud-config

install:
    grub_options:
        extra_cmdline: rd.immucore.debug
p2p:
    dns: true
    network_token: <token_here>
stages:
    initramfs:
        - name: Set user and password
          users:
            kairos:
                passwd: kairos
        - hostname: kairos-{{ trunc 4 .Random }}
          name: Set hostname
```

results in a system where edgevpn seems to work (I can see other edgevpn nodes when started with the same config in the edgevpn web interface) but k3s service doesn't start at all. It's not enabled.

This is the config we use in the decentralized test (which is broken but was supposedly passing locally - @jimmykarily checked before we release).

We also tried a config like this but with the same results:

```
#cloud-config

install:
 auto: true
 device: "auto"
 reboot: true

hostname: edgevpntest-{{ trunc 4 .MachineID }}
users:
- name: kairos
  passwd: kairos
  ssh_authorized_keys:
  - github:mudler
  - github:jimmykarily
p2p:
 disable_dht: false
 network_token: <token_here>
```
