### ISSUE TITLE
example Kubernetes osbuilder failed

### ISSUE THREAD

**Issue by fafarun** [kairos-io/kairos#2006]
**Kairos version:**
osartifacts                             build.kairos.io/v1alpha2       

**Describe the bug**

I try to build an iso with Kubernetes : [documentation](https://kairos.io/docs/installation/automated/)

The example is not working with the version of the CRD osartifacts. 

i change the `apiVersion: build.kairos.io/v1alpha1`to `apiVersion: build.kairos.io/v1alpha2` 

```
 cat <<'EOF' | kubectl apply -f -
apiVersion: build.kairos.io/v1alpha2
kind: OSArtifact
metadata:
  name: hello-kairos
spec:
  imageName: "quay.io/kairos/opensuse-leap-15.5-core-amd64-generic-v2.4.2"
  iso: true
  bundles:
  # Bundles available at: https://packages.kairos.io/Kairos/
  - quay.io/kairos/packages:helm-utils-3.10.1
  cloudConfig: |
            #cloud-config
            users:
            - name: "kairos"
              passwd: "kairos"
            install:
              device: "auto"
              reboot: true
              poweroff: false
              auto: true # Required, for automated installations
EOF

```

In the configuration, something change in the api and the example failed : 

```
Error from server (BadRequest): error when creating "iso.yaml": OSArtifact in version "v1alpha2" cannot be handled as a OSArtifact: strict decoding error: unknown field "spec.cloudConfig"
```

**To Reproduce**
Play the documentation automated and change the apiVersion to match with the last helm chart.

**Comment by jimmykarily** [comment]
`cloudConfig` was changed to `cloudConfigRef` here: https://github.com/kairos-io/helm-charts/commit/e9288137#diff-0a130fe29403f2c1e6b1380fe66a1f34cf1f61a60a5c8a9939735b41a9e2008bL45

I'll check how that works now and adapt the documentation accordingly. Good catch @fafarun !

**Comment by jimmykarily** [comment]
It seems that this is the right way now:

```
apiVersion: v1
kind: Secret
metadata:
  name: kairos-config
  namespace: default
type: Opaque
stringData:
  config.yaml: |
    #cloud-config
    users:
    - name: "kairos"
      passwd: "kairos"
    install:
      device: "auto"
      reboot: true
      poweroff: false
      auto: true # Required, for automated installations

---
apiVersion: build.kairos.io/v1alpha2
kind: OSArtifact
metadata:
  name: hello-kairos
  namespace: default
spec:
  imageName: "quay.io/kairos/opensuse:leap-15.5-core-amd64-generic-v2.4.2"
  iso: true
  bundles:
  # Bundles available at: https://packages.kairos.io/Kairos/
  - quay.io/kairos/packages:helm-utils-3.10.1
  cloudConfigRef:
    name: kairos-config
    key: config.yaml
```
