### ISSUE TITLE
`fail_on_bundles_errors: true` breaks Kairos installation on 2.4.2

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2012]
Simply enabling fail_on_bundles_errors: true makes kairos installation fail with:

```
fork/exec rsync -aqAX /var/lib/extensions /usr/local/.state/var-lib-extensions.bind: no such file or directory
```

coming from here: https://github.com/kairos-io/kairos-agent/blob/944ce8ce741adc24bb4ebbc5a5fba460c1e83e53/internal/agent/hooks/bundles.go#L39

My config:

```
#cloud-config

fail_on_bundles_errors: true

users:
  - name: kairos
    passwd: kairos
```

my version:

```
kairos-opensuse-leap-15.5-standard-amd64-generic-v2.4.2-k3sv1.28.2+k3s1
```

This maybe affects the installation of bundles in  general, not sure yet. I was debugging my test bundle and enabled the option above and found this
