### ISSUE TITLE
Custom partitioning

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#209]
**Is your feature request related to a problem? Please describe.**
A way to configure partitions via config file

**Describe the solution you'd like**
A simple and detailed way in the config to declare the partitions after install. Ideally should just enlarge the elemental config so it just exposes the underlying configuration

**Describe alternatives you've considered**
Dropping the config file manually, but the solution is more a workaround. It can be achieved by adding an initramfs stage which overwrites the elemental-config

**Additional context**

**Comment by jimmykarily** [comment]
When the config is mounted as a datasource iso (as [suggested here](https://github.com/kairos-io/kairos/issues/391#issuecomment-1456313786)), it partly works:

```
localhost:~ # cat /oem/userdata.yaml 
#cloud-config

users:
- name: "kairos"
  passwd: "kairos"

# Tell elemental to not create partitions
options:
  no-format: "true"

# User has to copy this file inside /oem
# because elemental will try to find stage steps there. Won't repect it here.
# Then the user has to install with
# `kairos-agent manual-install` with this file.
# Netbooting doesn't work for the same reason (elemental ignores the stages).
stages:
  before-install:
  - name: "Create a file"
    commands:
      - |
        touch /tmp/touched-before-install
  boot:
  # TODO: check which device exists
  - if:  '[ -e /dev/vda ] && (kairos-agent state get boot | grep -q unknown)'
    name: "Create partitions"
    commands:
      - |
        touch /tmp/touched-boot
    layout:
      device:
        path: /dev/vda
      add_partitions:
        - fsLabel: COS_STATE
          size: 16240 # At least 16gb
          pLabel: state
```

```
localhost:~ # ls /tmp/touched-*
/tmp/touched-boot
kairos-agent state get boot; echo
unknown
```

- before-install didn't run (maybe I need more config to enable auto-install?)
- the partition was not created:

```
localhost:~ # lsblk
NAME  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
fd0     2:0    1     4K  0 disk 
loop0   7:0    0 812.9M  1 loop /run/rootfsbase
sr0    11:0    1   364K  0 rom  
sr1    11:1    1  1024M  0 rom  
vda   253:0    0    30G  0 disk 
```

**Comment by jimmykarily** [comment]
I commented out the `options.no-format` section and at least it tries now (but fails):


```
$ journalctl
...
kd[1397]: eth0: DHCPv6 address 2a0d:3344:1a93:a010::3e9/128 (valid for 15min 49>
]: INFO[2023-03-07T12:36:58Z] Creating COS_STATE partition
]: ERRO[2023-03-07T12:36:58Z] Failed analyzing disk: exit status 1
]: ERRO[2023-03-07T12:36:58Z] Failed creating partitions: exit status 1
...
```

**Comment by jimmykarily** [comment]
The error seems to originate here: https://github.com/kairos-io/elemental-cli/blob/main/pkg/partitioner/parted.go#L155

I created this PR to improve the error message: https://github.com/kairos-io/elemental-cli/pull/45/files
In the meantime, running that command on the VM manually shows this:

```
localhost:~ # parted --script --machine -- /dev/vda unit s print
Error: /dev/vda: unrecognised disk label
BYT;
/dev/vda:62914560s:virtblk:512:512:unknown:Virtio Block Device:;
```

**Comment by jimmykarily** [comment]
Currently working on a refactoring of the kairos config here: https://github.com/kairos-io/kairos/tree/209-custom-partitioning-refactor-config

We are extracting the code that collects configuration from 3 different sources:

- local files in given directories
- config from the kernel cmdline
- remote files specified with `config_url` in any of the above (recursively)

When this is done, we will use this package to parse configuration in kairos-agent, elemental-cli, kcrypt and whatever consumer needs access to kairos-configuration. The consumers will unmarshal the merged Yamls into whatever Config object they mainain and they can do their own validations on that too.

**Comment by jimmykarily** [comment]
Currently blocked by #1225

**Comment by jimmykarily** [comment]
We have planned [a refactoring that will make elemental-cli a kairos-agent subcommand](https://github.com/kairos-io/kairos/issues/1210). When that happens, #1225 will be easier to implement (config will probably be available in memory).

We came up with an alternative fix for this issue for now, which is to write down the kairos config to `/oem` before we call `elemental install`. This is our WIP branch: https://github.com/kairos-io/kairos/tree/209-pass-config-to-elemental

**Comment by jimmykarily** [comment]
I'm trying the config above with a kairos-agent I've built from this: https://github.com/kairos-io/kairos-agent/pull/32

I had to change the stage from `boot` to `kairos-install.pre.before` which runs before partitioning happens (TODO: Document this stage) because `before-install` runs before the installation of the OS but after partitioning has happened. It seems to be working for one partition. I'll try to do the full partitioning manually and see.

**Comment by jimmykarily** [comment]
This is the config that works with the PR branch:

```
#cloud-config

install:
  no-format: true

stages:
  kairos-install.pre.before:
  # TODO: check which device exists
  - if:  '[ -e /dev/vda ] && (kairos-agent state get boot | grep -q livecd_boot)'
    name: "Create partitions"
    commands:
      - |
        parted --script --machine -- /dev/vda mklabel msdos
    layout:
      device:
        path: /dev/vda
      expand_partition:
        size: 0 # All available space
      add_partitions:
        - fsLabel: COS_OEM
          size: 64
          pLabel: oem
        - fsLabel: COS_RECOVERY
          size: 8500
          pLabel: recovery
        - fsLabel: COS_STATE
          size: 18000
          pLabel: state
        - fsLabel: COS_PERSISTENT
          pLabel: persistent
          size: 25000
          filesystem: "ext4"

users:
- name: "kairos"
  passwd: "kairos"
```

I had to make some fixes so that all partitions are created and "expand" happens after creation.
