### ISSUE TITLE
:seedling: Custom mounts

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#210]
**Is your feature request related to a problem? Please describe.**
Actually the persistent configuration is static and it cannot be extended. In order to configure additional mounts or bind mounts it is required to provide a cloud-config including directives as : https://github.com/kairos-io/kairos/blob/master/overlay/files/system/oem/11_persistency.yaml which replaces the system ones

**Describe the solution you'd like**
A way to extend what was declared by the base image - via the Kairos config file

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by oz123** [comment]
The following cloud init should work with the linked commit:
```
#cloud-config
users:
 - name: kairos 
   passwd: "kairos"
   ssh_authorized_keys:
     - github:oz123
   groups:
     - admin

additional_persistent_mounts:
  - /data/bla
  - /foo/bar
```

However, it seems that my build-kairos agent isn't surving a reboot. Hence, I have no clue if my code works, yet.
