### ISSUE TITLE
Custom config does not literally match the original cloud config

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2150]
Depending on the cloud config, you will notice that some attributes don't get copied verbatim to the `90_custom.yaml` but instead it gets scrambled a bit. Despite producing the desired results, this is not the best in terms of UX.

Issues:

1. The order of the items gets scrambled. I assume this is because of the marshalling and unmarshalling, and it's the least of the issues, but still can be confusing.
2. The permissions of a file are presented with different numbers. This I think is the main issue because when reading 511, I might think that the permission is a lot more secure, while the actual permission of the file on disk is 777
3. The content of the file removes the pipe operator, and puts the full content in a single line. While this might not be a huge issue for small files, it will make bigger files unreadable.

Here's an example:

```
kairos@localhost:~$ cat /oem/90_custom.yaml 
#cloud-config

install:
    device: auto
    poweroff: false
    reboot: true
stages:
    boot:
        - files:
            - content: "#!/bin/sh\necho \"test\"                    \n"
              group: 100
              owner: 1000
              path: /tmp/bar
              permissions: 511
users:
    - name: kairos
      passwd: kairos
```

This is how the permissions look on disk:

```
kairos@localhost:~$ ls -las /tmp/bar 
4 -rwxrwxrwx 1 ubuntu users 42 Jan 16 11:02 /tmp/bar
```
