### ISSUE TITLE
:bug: Usage of `install.partitioning` not working

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2151]
According to the docs:

a) https://kairos.io/docs/reference/configuration/
b) https://kairos.io/docs/advanced/configuring_partitions/

I should be able to resize partitions using:

```
#cloud-config

install:
  device: "/dev/sda"
  auto: true
  partitions:
    oem:
      size: 512
      fs: ext4
    recovery:
      size: 10000
      fs: ext4
```

However, this didn't work, what ended up working was something like this:

```
#cloud-config
install:
    auto: true
    device: auto
    poweroff: false
    reboot: true
    system:
          size: 5000
    recovery-system:
          size: 12000
```

I'm not sure if the `install.partitions` section is not used any longer, or if it affects a different functionality. For what I can tell the code is not really being called except for tests, so maybe it's just legacy and can be removed?

https://github.com/kairos-io/elemental-cli/blob/6b92df9b6b1af42bb7d7f6ae97961d4da930a715/pkg/types/v1/config.go#L302

If it's not used then we should also remove the code to avoid further confusion in the future
