### ISSUE TITLE
Login with custom username 

### ISSUE THREAD

**Issue by Ludea** [kairos-io/kairos#224]
**Kairos version:**

1.0.0 alpine flavor 
https://github.com/kairos-io/provider-kairos/releases/download/v1.0.0/kairos-alpine-arm-rpi-v1.0.0-k3sv1.24.3+k3s1.img
**CPU architecture, OS, and Version:**

Rpi3 aarch64 
**Describe the bug**

I can't login with my created user 

**To Reproduce**

I follow https://kairos.io/installation/raspberry to install Kairos on Rpi3 
I created a cloud config file to create user :
`cloud-config.yaml`
```
stages:
   initramfs:
     - name: "Set user and password"
       users:
        ludea:
          passwd: "mypassword"

k3s:
  enabled: true
```
Copy paste into COS_PERSISTENT partition. 
Boot the Rpi 
Try to login with `ludea` username and `mypassword`
**Expected behavior**

Successfull login into Kairos with my created user

**Logs**

**Additional context**

I also try
```
name: "Default user"
stages:
   initramfs:
     - name: "Setup groups"
       ensure_entities:
       - entity: |
            kind: "group"
            group_name: "admin"
            password: "x"
            gid: 900
     - name: "Setup users"
       users:
        ludea:
          passwd: "!"
          shell: /bin/bash
          homedir: "/home/ludea"
          groups:
          - "admin"
     - name: "Set user password if running in live"
       if: "[ -e /run/cos/live_mode ]"
       users:
        ludea:
          passwd: "mypassword"
     - name: "Setup sudo"
       files:
       - path: "/etc/sudoers"
         owner: 0
         group: 0
         permsisions: 0600
         content: |
            Defaults always_set_home
            Defaults secure_path="/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin"
            Defaults env_reset
            Defaults env_keep = "LANG LC_ADDRESS LC_CTYPE LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE LC_ATIME LC_ALL LANGUAGE LINGUAS XDG_SESSION_COOKIE"
            Defaults !insults
            root ALL=(ALL) ALL
            %admin ALL=(ALL) NOPASSWD: ALL
            #includedir /etc/sudoers.d
       commands:
       - passwd -l root
```

**Comment by mudler** [comment]
Hi Ludea, and thanks for bringing this up, it definitely is lacking as a use-case in the docs

I think you need to specify the shell and the home directory as well but I'm not sure and I should try it out, something among the lines of:

```yaml
stages:
   initramfs:
     - name: "Set user and password"
       users:
        ludea:
          groups:
          - "admin"
          passwd: "mypassword"
          shell: /bin/bash
          homedir: "/home/ludea"
k3s:
  enabled: true
```

can you try it out?

**Comment by mudler** [comment]
I've tried adding a user to a deployment of mine and I was successful with the following configs:

```yaml
stages:
   initramfs:
     - name: "Set user and password"
       users:
        ludea:
          groups:
          - "admin"
          passwd: "mypassword"
          shell: /bin/bash
          homedir: "/home/ludea"
```

Written as `/oem/user.yaml` in the system. I'll update the docs accordingly
