### ISSUE TITLE
SSH can only login with password, authorized_keys are completely ignored

### ISSUE THREAD

**Issue by firstdorsal** [kairos-io/kairos#2247]
**Kairos version:**

```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
KAIROS_PRETTY_NAME="kairos-standard-debian-bookworm v2.5.0-v1.29.0-k3s1"
KAIROS_VARIANT="standard"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_SOFTWARE_VERSION="v1.29.0+k3s1"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
KAIROS_VERSION="v2.5.0-v1.29.0-k3s1"
KAIROS_ID_LIKE="kairos-standard-debian-bookworm"
KAIROS_RELEASE="v2.5.0"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_VERSION_ID="v2.5.0-v1.29.0-k3s1"
KAIROS_ARTIFACT="kairos-debian-bookworm-standard-amd64-generic-v2.5.0-k3sv1.29.0+k3s1"
KAIROS_FLAVOR="debian"
KAIROS_FLAVOR_RELEASE="bookworm"
KAIROS_MODEL="generic"
KAIROS_ID="kairos"
KAIROS_IMAGE_LABEL="bookworm-standard-amd64-generic-v2.5.0-k3sv1.29.0-k3s1"
KAIROS_TARGETARCH="amd64"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_NAME="kairos-standard-debian-bookworm"
KAIROS_IMAGE_REPO="quay.io/kairos/debian:bookworm-standard-amd64-generic-v2.5.0-k3sv1.29.0-k3s1"
```
Did also happen with `opensuse-tumbleweed`

**CPU architecture, OS, and Version:**

```
Linux mows-GmpdECeo 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
```
**Describe the bug**

Using a public key to login to kairos with ssh does not work. When forcing it with `ssh kairos@192.168.122.99 -o Preferredauthentications=publickey -i ~/.ssh/mows-GmpdECeoy6vfkrgsGB4ZfpeZSsKmprivate` it terminates directly: `kairos@192.168.122.99: Permission denied (publickey,password).`

The key is set at `~/.ssh/authorized_keys`, but the default config does not enable key only login as there is none.
```
kairos@mows-GmpdECeo:~$ cat ~/.ssh/authorized_keys 
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ6LkjmImFC2cFpI2ryh25CTmTjjnCmBe6VE1/F0pwwK root@f04f750ec43a
```

**To Reproduce**

**Expected behavior**

It should make a difference whether you use a pubkey or not.
Even if it was password + key combined the key would be ignored.

**Logs**

**Additional context**

There is no default sshd config present, but even when I tried adding 
```
PubkeyAuthentication yes
AuthorizedKeysFile	.ssh/authorized_keys
PasswordAuthentication no
```
to `/etc/ssh/sshd_config` and restarted sshd it wont let me in with the pubkey. (But it applied it as password login didn't work anymore)

Something else I think happened
Adding a github key as well as a "real" key does only add the "real" key.

```yaml
users:
    - name: "kairos" # The username for the user.
      passwd: "Vqt6UPuCFbJr6lsA5cM55_JfGErgrFWhrMsAmpluHSOOlnpS5sF1RdgMjusv99-eJbwNjxKVZrHfUwRv3_it2d-G-13eKIQ1MToZ" # The password for the user.
      ssh_authorized_keys: # A list of SSH keys to add to the user's authorized keys.
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ6LkjmImFC2cFpI2ryh25CTmTjjnCmBe6VE1/F0pwwK root@f04f750ec43a
          - github:firstdorsal
```
