### ISSUE TITLE
User passwd should be encrypted in cloud-config

### ISSUE THREAD

**Issue by liyimeng** [kairos-io/kairos#2255]
**Kairos version:**

2.5.0
**CPU architecture, OS, and Version:**

x64
**Describe the bug**

kairos have user password stored in plain text, e.g. 

```
kairos@localhost:/oem$ cat 90_custom.yaml 
#cloud-config

install:
    device: /dev/sda
k3s:
    enabled: true
name: Config generated by the installer
stages:
    network:
        - users:
            kairos:
                groups:
                    - admin
                name: kairos
                passwd: liyimeng
                ssh_authorized_keys:
                    - github:liyimeng

```

I think this is a bad idea.  Suggest it to be encrypted. As I remember, k3os do it in encrypted, lets borrow the idea from there. 

**To Reproduce**

- login node 
- cat  oem/90_custom.yaml  
**Expected behavior**

password should be encrypted. 

**Logs**

**Additional context**

Right now, I have limited knowledge on kairos, not sure where its cloud-config applied, otherwise, I can draft a PR based on k3os idea.
