### ISSUE TITLE
Raw image not booting

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2273]
Originally reported [in Slack](https://spectrocloudcommunity.slack.com/archives/C04B1833NEA/p1708421440441469).

Creating a "cloud" image with these yamls, results in an image that doesn't boot neither in qemu or openstack:

```
kind: Secret
apiVersion: v1
metadata:
  name: cloud-config
  namespace: default
stringData:
  userdata: |
    #cloud-config
    install:
      device: "/dev/vda"
      auto: true
    users:
    - name: "kairos"
      passwd: "kairos"
    name: "Default deployment"
    stages:
      boot:
      - name: "Repart image"
        layout:
          device:
            label: COS_RECOVERY
          add_partitions:
            - fsLabel: COS_STATE
              size: 16240 # At least 16gb
              pLabel: state
      - name: "Repart image"
        layout:
          device:
            label: COS_RECOVERY
          add_partitions:
            - fsLabel: COS_PERSISTENT
              pLabel: persistent
              size: 0 # all space
      - if: '[ -f "/run/cos/recovery_mode" ] && [ ! -e /usr/local/.deployed ]'
        name: "Deploy kairos"
        commands:
          - kairos-agent --debug reset --unattended
          - touch /usr/local/.deployed
          - reboot    
---
apiVersion: build.kairos.io/v1alpha2
kind: OSArtifact
metadata:
  name: hello-kairos
  namespace: default
spec:
  imageName: "quay.io/kairos/opensuse:leap-15.5-core-amd64-generic-v2.5.0"
  cloudImage: true
  cloudConfigRef:
    name: cloud-config
    key: userdata
  exporters:
    - template:
        spec:
            restartPolicy: Never
            containers:
            - name: upload
              image: quay.io/curl/curl
              command:
              - /bin/sh
              args:
              - -c
              - |
                  for f in $(ls /artifacts)
                  do
                  curl -T /artifacts/$f http://osartifactbuilder-operator-osbuilder-nginx/upload/$f
                  done                    
              volumeMounts:
              - name: artifacts
                mountPath: /artifacts
---
apiVersion: build.kairos.io/v1alpha2
kind: OSArtifact
metadata:
  name: kairos-fedora-v2
  namespace: default
spec:
  imageName: "quay.io/kairos/fedora:38-standard-amd64-generic-v2.4.3-k3sv1.28.2-k3s1"
  cloudImage: true
  cloudConfigRef:
    name: cloud-config
    key: userdata
  exporters:
    - template:
        spec:
            restartPolicy: Never
            containers:
            - name: upload
              image: quay.io/curl/curl
              command:
              - /bin/sh
              args:
              - -c
              - |
                  for f in $(ls /artifacts)
                  do
                  curl -T /artifacts/$f http://osartifactbuilder-operator-osbuilder-nginx/upload/$f
                  done                    
              volumeMounts:
              - name: artifacts
                mountPath: /artifacts
```

Result with qemu:

![image](https://github.com/kairos-io/kairos/assets/2794419/fcf63eeb-02ad-4b45-a6e9-221da739f788)

Observations differ but could be related to this: https://github.com/kairos-io/kairos/issues/2025
