### ISSUE TITLE
Explore ways to use the persistent partition for data that shouldn't be "reset"

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#2304]
Because of the limitations in size when booting UKI images, we are considering putting a big chunk of the data (e.g. big binaries, cached container images etc) on the persistent partition. The problem with this approach is that on reset, we format the persistent partition.

To work around this issue, we could use an additional partition where the data will also be written. After reset a cloud-config will be responsible to write the data back to the persistent partition.

An altetnative would be to use the additional partition as a non-resettable  persistent partition and avoid any copies but this needs immucore to know about that partition and mount it properly on the final booted system. We could even use the oem partition for that (which doesn't get reset).

Let's try the first approach above which need less coding and if that doesn't work we consider the other options.

**Comment by jimmykarily** [comment]
Here is an example of how to copy the files after installation to the additional partition:

```
#cloud-config
users:
- name: kairos
  passwd: kairos

stages:
  after-install:
      - commands:
        - echo "Copying files to persistent path"
        - /usr/lib/systemd/systemd-cryptsetup attach persistent $(findfs PARTLABEL=persistent) - tpm2-device=auto
        - mount /dev/mapper/persistent /usr/local
        - mkdir /usr/local/.state/opt.bind
        - cp -rfv /run/initramfs/live/data/* /usr/local/.state/opt.bind
```
