### ISSUE TITLE
`kairos-agent config get` is broken

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#2315]
**Kairos version:**
master

**CPU architecture, OS, and Version:**

**Describe the bug**

`kairos-agent config get` doesnt work as expected as its not finding anything

**To Reproduce**

use `kairos-agent config get SOMETHING`
```
kairos@localhost:~$ kairos-agent config get kairos 
2024-03-07T14:14:59Z INF Kairos Agent version=v2.7.16
2024-03-07T14:14:59Z INF Kairos System version=v3.0.0-beta1-4-gd046b56
null
```

**Expected behavior**

`kairos-agent config get SOMETHING` returns that SOMETHING object if its in the config

**Logs**

**Additional context**

**Comment by jimmykarily** [comment]
Also relevant: https://github.com/kairos-io/kairos/issues/2342

**Comment by mauromorales** [comment]
I cannot reproduce the issue, at least if I use it with the default config, I seem to be getting the right output:

```
[kairos@fedora ~]$ cat /oem/90_custom.yaml
#cloud-config

install:
    device: /dev/vda
k3s:
    enabled: true
name: Config generated by the installer
stages:
    initramfs:
        - users:
            kairos:
                groups:
                    - admin
                name: kairos
                passwd: kairos
[kairos@fedora ~]$ kairos-agent config get install
device: /dev/vda
[kairos@fedora ~]$ kairos-agent config get install.device
/dev/vda
[kairos@fedora ~]$ kairos-agent config get k3s
enabled: true
[kairos@fedora ~]$ kairos-agent config get k3s.enabled
true
[kairos@fedora ~]$ kairos-agent config get stages
initramfs:
    - users:
        kairos:
            groups:
                - admin
            name: kairos
            passwd: kairos
rootfs.after:
    - if: '[ ! -f /run/cos/recovery_mode ] && [ ! -f /run/cos/live_mode ] && [ -f "/sys/firmware/devicetree/base/model" ] && grep -i "Raspberry Pi 4" "/sys/firmware/devicetree/base/model"'
      layout:
        device:
            label: COS_PERSISTENT
        expand_partition:
            size: 0
      name: Grow persistent
[kairos@fedora ~]$ kairos-agent config get stages.initramfs
- users:
    kairos:
        groups:
            - admin
        name: kairos
        passwd: kairos
```

**Comment by Itxaka** [comment]
oh shit, could it be that the sdk parsing bug fixed it also fixed this?

**Comment by mauromorales** [comment]
Converting to json seems to work properly too

```
[kairos@fedora ~]$ kairos-agent config get "stages.initramfs |@json"
'[{"users":{"kairos":{"groups":["admin"],"name":"kairos","passwd":"kairos"}}}]'
```

**Comment by Itxaka** [comment]
```
root@edge-1fefe67570ac44398111bd143dac7350:~# kairos-agent  --version
kairos-agent version v2.8.8
root@edge-1fefe67570ac44398111bd143dac7350:~# kairos-agent config get kairos
null

```

**Comment by Itxaka** [comment]
why `kairos-agent config` shows the state instead?

```
root@edge-1fefe67570ac44398111bd143dac7350:~# kairos-agent config
uuid: 59ddca887a56d84cb1894e4b6613c6e1-edge-1fefe67570ac44398111bd143dac7350
persistent:
    mounted: false
    name: ""
    label: ""
    filesystemlabel: ""
    mount_point: ""
    size_bytes: 0
    type: ""
    read_only: false
    found: false
    uuid: ""
recovery:
    mounted: false
    name: ""
    label: ""
    filesystemlabel: ""
    mount_point: ""
    size_bytes: 0
    type: ""
    read_only: false
    found: false
    uuid: ""
oem:
    mounted: true
    name: /dev/mapper/vda2
    label: ""
    filesystemlabel: COS_OEM
    mount_point: /oem
    size_bytes: 0
    type: ext4
    read_only: false
    found: true
    uuid: ""
state:
    mounted: false
    name: ""
    label: ""
    filesystemlabel: ""
    mount_point: ""
    size_bytes: 0
    type: ""
    read_only: false
    found: false
    uuid: ""
boot: unknown
system:
    meta:
        version: 1.0.1
        timestamp: 2024-04-08T13:32:39.57017155Z
    node:
        hostname: edge-1fefe67570ac44398111bd143dac7350
        machineid: 59ddca887a56d84cb1894e4b6613c6e1
        hypervisor: kvm
        timezone: Etc/UTC
    os:
        name: Ubuntu 23.10
        vendor: ubuntu
        version: "23.10"
        release: "23.10"
        architecture: amd64
    kernel:
        release: 6.5.0-26-generic
        version: '#26-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar  5 21:19:28 UTC 2024'
        architecture: x86_64
    product:
        name: Standard PC (Q35 + ICH9, 2009)
        vendor: QEMU
        version: pc-q35-8.2
        serial: ""
    board:
        name: ""
        vendor: ""
        version: ""
        serial: ""
        assettag: ""
    chassis:
        type: 1
        vendor: QEMU
        version: pc-q35-8.2
        serial: ""
        assettag: ""
    bios:
        vendor: EFI Development Kit II / OVMF
        version: 0.0.0
        date: 02/06/2015
    cpu:
        vendor: GenuineIntel
        model: 12th Gen Intel(R) Core(TM) i9-12900K
        speed: 2000
        cache: 16384
        cpus: 0
        cores: 0
        threads: 12
    memory:
        type: RAM
        speed: 0
        size: 16000
    storage:
        - name: vda
          driver: virtio_blk
          vendor: ""
          model: ""
          serial: ""
          size: 53
    network:
        - name: enp1s0
          driver: virtio_net
          macaddress: 52:54:00:a1:29:e2
          port: ""
          speed: 0
        - name: enp8s0
          driver: e1000e
          macaddress: 52:54:00:76:b7:a3
          port: tp
          speed: 1000
kairos:
    flavor: ubuntu
    version: v3.0.4
    init: systemd

```
