### ISSUE TITLE
Auroraboot: server returned 404 Not Found, looks like URLs generated are incorrect

### ISSUE THREAD

**Issue by ankycooper** [kairos-io/kairos#2378]
**Kairos version:**
3.0.1

**CPU architecture, OS, and Version:**
intel Mac also tried on Linux VM
**Describe the bug**
server returned 404 Not Found, looks like URLs generated are incorrect
**To Reproduce**
`docker run -v "$PWD"/storage/config.yaml:/config.yaml -v "$PWD"/storage/:/storage --rm -ti --net host quay.io/kairos/auroraboot \
        --cloud-config /config.yaml
`
Config.yaml

`state_dir: "/storage"
artifact_version: "v3.0.1-k3sv1.29.0+k3s1"
release_version: "v3.0.1"
flavor: rockylinux
repository: kairos-io/kairos 
cloud_config: |
  #cloud-config
...<my config here>...
`

**Expected behavior**
Generate a custom ISO

**Logs**
`11:15AM INF Downloading https://github.com//releases/download//core--.iso...
11:15AM INF Downloading https://github.com//releases/download//core---initrd...
11:15AM INF Downloading https://github.com//releases/download//core--.squashfs...
11:15AM INF Downloading https://github.com//releases/download//core---kernel...
7 errors occurred:
        * server returned 404 Not Found
        * server returned 404 Not Found
        * server returned 404 Not Found
        * server returned 404 Not Found
        * 'inject-cloud-config' deps download-iso failed
        * 'start-netboot' deps download-kernel failed
        * 'start-httpserver' deps inject-cloud-config failed`
**Additional context**

**Comment by jimmykarily** [comment]
The `config.yaml` you are passing is a config file for auroraboot, not Kairos. You should be passing it as the first parameter, not with `--cloud-config`

You also miss some settings in that config. Something like this works better:

```
state_dir: "/storage"
artifact_version: "v3.0.1-k3sv1.29.0+k3s1"
release_version: "v3.0.1"
flavor: rockylinux
flavor_release: 9
repository: kairos-io/kairos
platform: amd64
cloud_config: |
  #cloud-config
  users:
    - name: kairos
      passwd: kairos
```

Used like this:

```
docker run -v "$PWD"/storage/config.yaml:/config.yaml -v "$PWD"/storage/:/storage --rm -ti --net host quay.io/kairos/auroraboot /config.yaml
```
