### ISSUE TITLE
Reboot hangs for UKI images 

### ISSUE THREAD

**Issue by vipsharm** [kairos-io/kairos#2384]
**Kairos version:**
3.0.1

**CPU architecture, OS, and Version:**
Ubuntu 23.10

After cluster is setup, rebooting the OS hangs in QEMU VM.

https://github.com/kairos-io/kairos/assets/13304280/d2ce43e7-5ab8-44f6-a922-05c745036aec

https://github.com/kairos-io/kairos/assets/13304280/7634db09-029a-47f9-80f5-920798ac7b98

**Comment by Itxaka** [comment]
With longhorn installed and rebooting:

![image](https://github.com/kairos-io/kairos/assets/1447686/7e42fadf-fb78-47d7-8da2-439c906bd7d8)

**Comment by Itxaka** [comment]
took a while but it restarted and then everything came up properly after a few minutes


![image](https://github.com/kairos-io/kairos/assets/1447686/a980f980-fa02-4923-9ea8-fd50be8402d0)

**Comment by mudler** [comment]
@vipsharm as we can't reproduce this, can you share the ISO you are using so we can try to reproduce with that one? Also, did you give to the machine enough RAM/CPU resources?

**Comment by jimmykarily** [comment]
it turns out the state partition gets filled up.  In my case it was even full after the upgrade before kubernetes even started"

![image](https://github.com/kairos-io/kairos/assets/2794419/7a976fdd-17db-4fa7-9333-6095f3691022)

 I increased the size of the state partition with:

```
#cloud-config
stylus:
  site:
    name: dimitris-edge-host-9
    edgeHostToken: <reducted>
    paletteEndpoint: api.dev.spectrocloud.com

install:
  device: "/dev/vda"
  auto: true
  partitions:
    state:
      size: 5000
      fs: ext4
stages:
  initramfs:
    - users:
        kairos:
          groups:
            - sudo
          passwd: kairos

```

and this allowed me to boot and see the Pods coming up. After everything was running, I did a cold `reboot` and waited until it reboots. Then the space issue came back:

![image](https://github.com/kairos-io/kairos/assets/2794419/4166bc50-fe6c-46fd-80bc-693345205511)

I think somehow containerd ends up writing the container filesystems on the state partition and it gets that filled up. Maybe there is some directory we should be mounting elsewhere and we don't?
