### ISSUE TITLE
EdgeVPN environment variables are incorrectly validated

### ISSUE THREAD

**Issue by 6ixfalls** [kairos-io/kairos#2454]
**Kairos version:**
quay.io/kairos/debian:bookworm-standard-amd64-generic-v3.0.4-k3sv1.29.3-k3s1

**Describe the bug**
The generated json schema by kairos validates /p2p/vpn/env as an array while it should be an object.

**To Reproduce**
```yml
#cloud-config
users:
  - name: kairos
p2p:
  vpn:
    env:
      DHCP: "true"
```

Using `- DHCP: "true"` or any other format removes the error, but as it's not properly parsed in the code it causes kairos to not work at all.

**Expected behavior**
A warning/error isn't produced and the schema should be valid.
