### ISSUE TITLE
Uki: installer does not reboot the system after installation is done

### ISSUE THREAD

**Issue by nianyush** [kairos-io/kairos#2506]
kairos version 3.0.6
having cloudconfig looks like this
```
#cloud-config
install:
  device: auto
  reboot: true
  poweroff: false
```
After installation is done, i do see the log msg that installer is going to reboot the system. But nothing happens after that.
![image](https://github.com/kairos-io/kairos/assets/5505684/ba007fb5-23ba-44db-8cc1-68e8e02675e4)
