### ISSUE TITLE
Code Executed During the Boot Stage Runs After the Network & runcmd Stages

### ISSUE THREAD

**Issue by ElectroshockGuy** [kairos-io/kairos#2571]
**Kairos version:**

```
# kairos version
version: 2.6.4, compiled with: go1.21.7
```

**CPU architecture, OS, and Version:**

arch: amd64
os: ubuntu 22.04
**Describe the bug**

I encountered a strange issue where I found that the command code executed during the boot stage always runs after the runcmd and network stages.

**To Reproduce**

Here are my experiment results:
cloud-config:
```yaml
runcmd:
    - echo "runCmd" >> /etc/tmp
stages:
    initramfs:
        - commands:
          - echo "initCmd" >> /etc/tmp
          name: "Init Stage"
    boot:
        - commands:
          - echo "bootCmd" >> /etc/tmp
          name: "Boot Stage"
    network:
        - commands:
          - echo "networkCmd" >> /etc/tmp
          name: "Network Stage"
```

After the system starts, the /tmp/tmp file looks like this:
```shell
# cat /etc/tmp
initCmd
networkCmd
runCmd
bootCmd
```
**Expected behavior**

**Logs**

**Additional context**
