### ISSUE TITLE
Invalid entry in `install.encrypted_partitions` causes partially installed system

### ISSUE THREAD

**Issue by kreeuwijk** [kairos-io/kairos#2578]
**Kairos version:**
Kairos 3.0.11

**CPU architecture, OS, and Version:**
```
Linux 0727e700-76d4-11e8-8be2-548351533800 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the bug**
I tried the following today to encrypt a secondary disk with Trusted Boot:
```
install:
  encrypted_partitions:
  - COS_SECONDARY

stages:
  kairos-install.pre.before:
  - if:  '[ -e "/dev/sda" ]'
    name: "Prepare secondary SSD"
    commands:
      - |
        parted --script --machine -- "/dev/sda" mklabel gpt
    layout:
      device:
        path: "/dev/sda"
      add_partitions:
        - fsLabel: COS_SECONDARY
          size: 0
          pLabel: secondary
          filesystem: "ext4"
```

This would not work since the correct stage name is actually `kairos-uki-install.pre.before`, not `kairos-install.pre.before` (might want to note that in the documentation for trusted boot). As a result, the commands in the stage above didn’t run and the encryption stage showed an error that it could not find the label (no further description but it was obvious this was for the secondary disk).
The regular partitions on the primary disk encrypted normally though. However I noticed that after rebooting the device, my userdata was not on the device. I flashed it again and canceled the shutdown, then checked the contents of the COS_OEM partition: the `/oem/90_custom.yaml` was indeed not there.

It seems that when `install.encrypted_partitions` contains an entry for a partition that it can't find, this isn't handled properly and the userdata does not get copied over to the device.

**To Reproduce**
Add a bogus entry to `install.encrypted_partitions` and flash a device. Notice that none of your userdata makes it to `/oem`

**Expected behavior**
The installation should either:
1. Abort on the non-present partition
2. Continue and complete all other steps normally, but show a warning after installation (and probably pause there for user confirmation to ensure this message is seen)
