### ISSUE TITLE
suc-script needs to mount /sys for UKI upgrades

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2586]
Seems we have a discrepancy in the docs: https://kairos.io/docs/upgrade/trustedboot/

We create a separate suc-script, and seems also it is needed to mount /sys as well before performing the upgrade.

This card is about unifying the suc-script so it works with both UKI and non-UKI environment, or alternatively have two separate scripts that are documented, installed in the system and in the packages repository.

**Comment by ci-robbot** [comment]
Hello, I'm an experimental bot assisting with issue triage in the kairos repository. I've noticed that you've opened an issue titled "suc-script needs to mount /sys for UKI upgrades". Unfortunately, the issue is missing a few important details to meet the project's requirements.

In order to help you better, please provide a description of the issue and, if it's a bug, include steps to reproduce. It would also be helpful if you mention the versions of the relevant artifacts being used. Once you add this information, we'll be able to better understand and address the issue.

Thank you for your cooperation, and remember that I am a bot created as an experiment by @mudler and @jimmykarily.

**Comment by nianyush** [comment]
Sure I can help to add an example

**Comment by nianyush** [comment]
For uki, we built an image based on ubuntu and addded efi files into it. So basically its an ubuntu image + /trusted-boot folder which looks like
```
/trusted-boot
├── EFI
│   ├── BOOT
│   │   └── BOOTX64.EFI
│   └── kairos
│       └── norole.efi
└── loader
    ├── entries
    │   └── norole.conf
    ├── keys
    │   └── auto
    │       ├── db.auth
    │       ├── db.der
    │       ├── KEK.auth
    │       ├── KEK.der
    │       ├── PK.auth
    │       └── PK.der
    └── loader.conf
```
SUC plan to work with this
```
---
apiVersion: v1
kind: Secret
metadata:
  name: upgrade
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    rm -rf /host/usr/local/trusted-boot
    mkdir -p /host/usr/local/trusted-boot
    mount --rbind /trusted-boot /host/usr/local/trusted-boot
    chroot /host kairos-agent --debug upgrade --source dir:/usr/local/trusted-boot
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: os-upgrade
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  version: "<CONTAINER_IMAGE_TAG>"
  nodeSelector:
    matchExpressions:
      - {key: kubernetes.io/hostname, operator: Exists}
  serviceAccountName: system-upgrade
  secrets:
    - name: upgrade
      path: /host/run/system-upgrade/secrets/upgrade
  cordon: false
  drain:
    force: false
    disableEviction: true
  upgrade:
    image: "<CONTAINER_IMAGE>"
    command: ["/bin/bash"]
    args: ["/run/system-upgrade/secrets/upgrade/upgrade.sh"]
```

**Comment by nianyush** [comment]
And for non uki, we just use the kairos rootfs image as the plan image instead of using ubuntu image like how kairos docs is doing nowadays. The benefit would be that we can leverage k8s functionalities to manage registry secrets and containerd for caching.
```
---
apiVersion: v1
kind: Secret
metadata:
  name: upgrade
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    mount --rbind /host/dev /dev
    mount --rbind /host/run /run
    mkdir -p /etc/rancher/k3s # remove if you are not using k3s
    mount --rbind /host/etc/rancher/k3s /etc/rancher/k3s # remove if you are not using k3s
    kairos-agent --debug upgrade --source dir:/
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: os-upgrade
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  version: "<CONTAINER_IMAGE_TAG>"
  nodeSelector:
    matchExpressions:
      - {key: kubernetes.io/hostname, operator: Exists}
  serviceAccountName: system-upgrade
  secrets:
    - name: upgrade
      path: /host/run/system-upgrade/secrets/upgrade
  cordon: false
  drain:
    force: false
    disableEviction: true
  upgrade:
    image: "<CONTAINER_IMAGE>"
    command: ["/bin/bash"]
    args: ["/run/system-upgrade/secrets/upgrade/upgrade.sh"]
```
