### ISSUE TITLE
typo in docs about creating extra partitions

### ISSUE THREAD

**Issue by nianyush** [kairos-io/kairos#2753]
https://kairos.io/docs/reference/configuration/
```
  extra-partitions:
    - Name: myPartition
      size: 100
      fs: ext4
      label: ONE_PARTITION
    - Name: myOtherPartition
      size: 200
      fs: ext4
      label: TWO_PARTITION
```
`Name` should be `name` according to [schema](https://github.com/kairos-io/kairos-sdk/blob/main/schema/install_schema.go#L38)
![image](https://github.com/user-attachments/assets/c4b70667-e419-4b52-b01a-8aa37a03cfb1)
