### ISSUE TITLE
Kairos 3.x Alpine - P2P k3s HA cluster creation failed

### ISSUE THREAD

**Issue by dan1el-k** [kairos-io/kairos#2789]
**Kairos version:**
<img width="998" alt="grafik" src="https://github.com/user-attachments/assets/6aef03c0-8897-4c33-8a32-f3321fe36131">

**CPU architecture, OS, and Version:**
amd64

**Describe the bug**

I have tried installing a k3s HA cluster with 3 Masters and 2 Workers using latest Kairos with Alpine.
It seems that the P2P functionality is not working using Alpine base images. After Kairos installation and reboot of the VM, the agent is running but gives following error in `/var/log/kairos/agent.log`

```bash
...
edgevpn: unrecognized option: enable-healthchecks
...
```

`sudo kairos role list`: gives not output

k3s service is also not running.

**To Reproduce**

```yaml
#cloud-config

hostname: homeserver-k3s-{{ trunc 4 .MachineID }}

users:
- name: "kairos"
  passwd: "kairos"
  groups: 
    - "admin"
  ssh_authorized_keys:
    - ssh-rsa xxx

install:
  # Device for automated installs
  device: "/dev/sda"
  # Reboot after installation
  reboot: false
  # Power off after installation
  poweroff: true
  # Set to true to enable automated installations
  auto: true

kubevip:
  eip: "10.43.3.100"

p2p:
  # Disabling DHT makes co-ordination to discover nodes only in the local network
  disable_dht: true #Enabled by default

  # to run multiple clustes in the same network
  network_id: homeserver

  vpn:
    create: false # defaults to true
    use: false # defaults to true
  # network_token is the shared secret used by the nodes to co-ordinate with p2p.
  # Setting a network token implies auto.enable = true.
  # To disable, just set auto.enable = false
  network_token: ""

  # Automatic cluster deployment configuration
  auto:
    # Enables Automatic node configuration (self-coordination)
    # for role assignment
    enable: true
    # HA enables automatic HA roles assignment.
    # A master cluster init is always required,
    # Any additional master_node is configured as part of the 
    # HA control plane.
    # If auto is disabled, HA has no effect.
    ha:
      # Enables HA control-plane
      enable: true
      # Number of HA additional master nodes.
      # A master node is always required for creating the cluster and is implied.
      # The setting below adds 2 additional master nodes, for a total of 3.
      master_nodes: 2

k3s:
  args:
  - --cluster-cidr 10.42.0.0/16
  - --cluster-dns "10.100.0.10"
  - --service-cidr 10.100.0.0/16
  - --disable=servicelb
  - --disable=traefik
  - --tls-san 10.43.3.100
  etcd-arg:
  - --snapshot-count 5000

# Additional manifests that are applied by k3s on boot
write_files:
...

```

**Expected behavior**

P2P HA k3s cluster creation works for Alpine base images, together with custom k3s args.

**Logs**
<img width="1275" alt="grafik" src="https://github.com/user-attachments/assets/ee617911-c81c-4789-8bdb-583807f5d80b">

**Additional context**

I was already able to setup a k3s cluster in HA mode with kairos 2.x using a similar kairos-config yaml, but with Fedora as a base image
