### ISSUE TITLE
Wrong config reference to `install.source`

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2810]
There are a few pages that make reference to:

```
install:
  source: ...
```

But this is no longer supported. Update the docs to show the valid configuration

https://kairos.io/docs/examples/core/
https://kairos.io/docs/reference/configuration/

**Comment by jimmykarily** [comment]
Actually, `install.source` is the correct config ([check the annotation here](https://github.com/kairos-io/kairos-agent/blob/d4076796774f609b425d993067d4d9481b9bc320/pkg/config/config.go#L47))

I used this config and it works as expected:

```yaml
#cloud-config
users:
  - name: kairos
    passwd: kairos

install:
  source: quay.io/kairos/ubuntu:24.04-core-amd64-generic-v3.1.3
```

Maybe the ticket means the `install.image` instead? (as deprecated)
