### ISSUE TITLE
layout  plugin doesn't work with nvme disks if match by label

### ISSUE THREAD

**Issue by dnugmanov** [kairos-io/kairos#2834]
**Kairos version:** 3.1.0

**Describe the bug**

1. NVMe devices are typically named as `/dev/nvme0n1p1`, where `n1` and `p1` indicate different namespaces and partitions on the NVMe drive. Each partition can be accessed individually, and they may appear as separate devices.
2. https://github.com/mudler/yip/blob/3eeeb15bc6b921a977c1f44cf30e77c81dcd4dc6/pkg/plugins/layout.go#L140 yip uses `blkid -l --match-token LABEL=%s -o device` which returns  for example: `/dev/nvme0n1p4`   instead of `/dev/nvme0n1`
3.  As a consequence following construction doesn't work for case with nvme disks.

```
    - name: "Repart image"
      layout:
        device:
          label: COS_RECOVERY
        add_partitions:
          - fsLabel: COS_STATE
            size: 50000
            pLabel: state
```
**To Reproduce**
see above

**Expected behavior**
yip matches disk, not partition and can catch following case

**Logs**
```
root@ed-b16-95-187-176:/home/ubuntu# ls -la /dev/disk/by-label/
total 0
drwxr-xr-x 2 root root 100 Jun 13 08:22 .
drwxr-xr-x 8 root root 160 Jun 13 08:22 ..
lrwxrwxrwx 1 root root  15 Jun 13 08:22 config-2 -> ../../nvme0n1p4


root@ed-b16-95-187-176:/home/ubuntu# blkid -l --match-token LABEL=config-2 -o device
/dev/nvme0n1p4
```
