### ISSUE TITLE
`/var/lib/longhorn` is not bind mounted

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#292]
**Kairos version:**
1.1.3

**CPU architecture, OS, and Version:**

**Describe the bug**
`/var/lib/longhorn` is listed in the persistency files for being bind mounted during initramfs stage, however the path is missing from the rootfs so the initramfs will fail bind mounting it

**To Reproduce**
The current workaround fixes it:
```yaml
fs:
    - name: "Preparing /var/lib/longhorn"
      if: '[ ! -f "/run/cos/recovery_mode" ]'
      commands:
      - |
          mkdir -p /usr/local/longhorn-config /var/lib/longhorn
          mount --bind /usr/local/longhorn-config /var/lib/longhorn
```

**Expected behavior**

**Logs**

**Additional context**
Thanks to @jbalonso for noticing this out!
We might need to create the dir beforeahead as its not present in the rootfs of the image before the initramfs sets up the mounts
