### ISSUE TITLE
Document how to run commands on different shells than sh

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2946]
The following config

```
stages:
  boot.after:
    - name: "do something"
      commands:
        - /path/to/script.sh
```

where `script.sh` is

```
#!/bin/bash

if [[ "foo" == "bar" ]]
...
```

throws the following error

```
[[: not found
```
