### ISSUE TITLE
Immucore unable to locate COS_STATE partition after installation of image larger than 5Gb on Kairos v3.1.3

### ISSUE THREAD

**Issue by robin-ny** [kairos-io/kairos#2950]
**Kairos version:**

```
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
KAIROS_VERSION_ID="v3.1.3"
KAIROS_ARTIFACT="kairos-ubuntu-24.04-core-amd64-generic-v3.1.3"
KAIROS_VARIANT="core"
KAIROS_VERSION="v3.1.3"
KAIROS_PRETTY_NAME="kairos-core-ubuntu-24.04 v3.1.3"
KAIROS_MODEL="generic"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_FLAVOR_RELEASE="24.04"
KAIROS_TARGETARCH="amd64"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_FLAVOR="ubuntu"
KAIROS_FAMILY="ubuntu"
KAIROS_RELEASE="v3.1.3"
KAIROS_ID="kairos"
KAIROS_NAME="kairos-core-ubuntu-24.04"
KAIROS_ID_LIKE="kairos-core-ubuntu-24.04"
KAIROS_IMAGE_REPO="quay.io/kairos/ubuntu:24.04-core-amd64-generic-v3.1.3"
KAIROS_IMAGE_LABEL="24.04-core-amd64-generic-v3.1.3"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
```

**CPU architecture, OS, and Version:**

`Linux live 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Describe the bug**

I build two images based on the Kairos version shown above (quay.io/kairos/ubuntu:24.04-core-amd64-generic-v3.1.3), which contain additional software:

```
REPOSITORY                                         TAG                               IMAGE ID             CREATED         SIZE
internal.registry.net/kairos/ubuntu                24.04-core-amd64-small-v3.1.3       661bdd139b33   19 hours ago    3.8GB
internal.registry.net/kairos/ubuntu                24.04-core-amd64-large-v3.1.3       5d2ca0fa0e9e     19 hours ago    5.1GB
``` 

The image `24.04-core-amd64-small-v3.1.3` can be installed and booted without any issues. 
The image `24.04-core-amd64-large-v3.1.3` can also be installed without any errors, however on boot the partition COS_STATE can't seem to be found by immucore, which leads to reboot cycling:
![image](https://github.com/user-attachments/assets/95481ee5-3ef3-47dc-8779-dabcf99facb7)

The install section in the cloud config looks as following:
```
#cloud-config
install:
  grub_options:
    extra_cmdline: "rd.immucore.debug"
  device: "auto"
  reboot: false
  poweroff: true
  auto: true
  source: oci:internal.registry.net/kairos/ubuntu:24.04-core-amd64-large-v3.1.3
  partitions:
    oem:
      size: 512
      fs: ext4
    recovery:
      size: 20000
      fs: ext4
    state:
      size: 40000
      fs: ext4
    persistent:
      size: 0
  system:
    size: 8000
  passive:
    size: 8000
  recovery-system:
    size: 8000
  ```

An Image with the same software installed but using Kairos version v3.1.2 (quay.io/kairos/ubuntu:24.04-core-amd64-generic-v3.1.2) boots normally.
```
REPOSITORY                                         TAG                               IMAGE ID             CREATED         SIZE
internal.registry.net/kairos/ubuntu                24.04-core-amd64-large-v3.1.2       f0a42a621130   24 hours ago    5.14GB
```
**To Reproduce**
1. Build a Kairos Image >5GB based on quay.io/kairos/ubuntu:24.04-core-amd64-generic-v3.1.3
2. Install the image
3. Boot and see errors

**Expected behavior**

Images using Kairos v3.1.3 >5Gb should boot normally.

**Additional context**
Installation has been tested both on a physical machine and on a vm, with the same results.
