### ISSUE TITLE
Node won't reset after web install despite being requested in config

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#2951]
I'm trying to apply the following config via the webUI

```
#cloud-config

# Sources:
# - reader
# - reader
# - reader
# - cmdline

install:
    device: auto
    poweroff: false
    reboot: true
k3s:
    enabled: true
name: Config generated by the installer
p2p:
    network_token: TOKEN_GOES_HERE
stages:
    network:
        - users:
            kairos:
                groups:
                    - admin
                name: kairos
                passwd: kairos
                ssh_authorized_keys:
                    - github:mauromorales
```

but it will not auto reboot.

If the option is selected on the checkbox to reboot, then it does work

using:

```
kairos@localhost:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
KAIROS_ID_LIKE="kairos-standard-ubuntu-24.04"
KAIROS_IMAGE_LABEL="24.04-standard-amd64-generic-v3.2.1-k3sv1.31.1-k3s1"
KAIROS_ARTIFACT="kairos-ubuntu-24.04-standard-amd64-generic-v3.2.1-k3sv1.31.1+k3s1"
KAIROS_FLAVOR="ubuntu"
KAIROS_FLAVOR_RELEASE="24.04"
KAIROS_FAMILY="ubuntu"
KAIROS_MODEL="generic"
KAIROS_NAME="kairos-standard-ubuntu-24.04"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_SOFTWARE_VERSION="v1.31.1+k3s1"
KAIROS_TARGETARCH="amd64"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_VERSION="v3.2.1-v1.31.1-k3s1"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_ID="kairos"
KAIROS_PRETTY_NAME="kairos-standard-ubuntu-24.04 v3.2.1-v1.31.1-k3s1"
KAIROS_IMAGE_REPO="quay.io/kairos/ubuntu:24.04-standard-amd64-generic-v3.2.1-k3sv1.31.1-k3s1"
KAIROS_VARIANT="standard"
KAIROS_RELEASE="v3.2.1"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
KAIROS_VERSION_ID="v3.2.1-v1.31.1-k3s1"
```

**Comment by jimmykarily** [comment]
This happens because we pass it as a cli argument which takes precedence over the user config: https://github.com/kairos-io/kairos-agent/blob/f24511b2dd49876e05c16b33a22423df3f3b693f/internal/webui/webui.go#L208

If the user doesn't check the UI checkbox, we should then check the cloud config. If it's checked in the UI, it should win over the cloud config setting. In other words, explicit actions (like checking a checkbox) should be respected always. Non explicit actions (like not checking something) should be ignored if there is another settings that sets to true.

**Comment by mauromorales** [comment]
I get this issue also when provisioning via auroraboot

config is pretty much the same

```
#cloud-config

install:
 auto: true
 device: "auto"
 reboot: true
...
```

The machine does shutdown, but it doesn't reboot, I wonder if it can be related to my libvirt setup?
