### ISSUE TITLE
Image loopback size discrepancy after upgrade

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#2985]
**Kairos version:**
To be verified

**Agent version**
v2.13.9 https://github.com/kairos-io/kairos-agent/releases/tag/v2.13.9

**CPU architecture, OS, and Version:**
N/A

**Describe the bug**
Seems that there is an image discrepancy after upgrading after instdallation. For example:

Before upgrade:

```
edge-c7945f6acbd0bd499d0d619826ec35ce:~ # ls -al /run/initramfs/cos-state/cOS/
total 10070152
drwxr-xr-x 2 root root       4096 Nov  5 11:27 .
drwxr-xr-x 5 root root       4096 Nov  5 11:38 ..
-rw-r--r-- 1 root root 8589934592 Nov  5 11:27 active.img
-rw-r--r-- 1 root root 8589934592 Nov  5 11:27 passive.img
```

After upgrade:

```
edge-c7945f6acbd0bd499d0d619826ec35ce:~ # ls -al /run/initramfs/cos-state/cOS/
total 3824760
drwxr-xr-x 2 root root       4096 Nov  3 14:15 .
drwxr-xr-x 5 root root       4096 Nov  3 14:08 ..
-rw-r--r-- 1 root root 2249195520 Nov  3 14:15 active.img
-rw-r--r-- 1 root root 8589934592 Nov  3 14:15 passive.img
```

**To Reproduce**
Do a standard kairos installation, and attempt to upgrade. Check the size of the loopback images in ` /run/initramfs/cos-state/cOS/`

**Expected behavior**
The image that is used for upgrade is having the same size - somehow it looks like there is a miscalculation either doing during creation of the ISO which contains the loopback images, or during upgrade.

**Logs**

**Additional context**
SUS-569 
SCS-2104

**Comment by Itxaka** [comment]
happens on master

```
2024-11-05T14:43:45Z DBG Finish Lifecycle hook
root@kairos-2vsg:~# ls /run/initramfs/cos-state/cOS/ -lh
total 3.0G
-rw-r--r-- 1 root root 3.0G Nov  5 14:43 active.img
-rw-r--r-- 1 root root 8.0G Nov  5 14:43 passive.img
```

```
  Active: v1.Image{
    File: "/run/initramfs/cos-state/cOS/transition.img",
    Label: "COS_ACTIVE",
    Size: 3016,
    FS: "ext2",
    Source: &v1.ImageSource{
      source: "ttl.sh/upgradeitxaka:latest",
      srcType: "oci",
    },
    MountPoint: "/run/cos/transition",
    LoopDevice: "",
  },
```

**Comment by Itxaka** [comment]
notice that this is with the values of 8Gbs per image in the config file:


```
#cloud-config

install:
  grub-entry-name: "Wiki Woko"
  system:
    size: 8192
  passive:
    size: 8192
  recovery-system:
    size: 8192
upgrade:
  grub-entry-name: "Wiki Woko"
  passive:
    size: 8192
  system:
    size: 8192
  recovery-system:
    size: 8192
reset:
  grub-entry-name: "Wiki Woko"
  passive:
    size: 8192
  system:
    size: 8192
  recovery-system:
    size: 8192


stages:
  initramfs:
    - name: "Set user and password"
      users:
        kairos:
          passwd: "kairos"
          groups:
            - "admin"
    - name: "Set hostname"
      hostname: kairos-{{ trunc 4 .Random }}
```


And this is the config when running the upgrade:

```
2024-11-05T14:42:36Z DBG Loaded config: &config.Config{
  Install: &config.Install{
    Auto: false,
    Reboot: false,
    NoFormat: false,
    Device: "",
    Poweroff: false,
    GrubOptions: map[string]string(nil), // p0
    Bundles: nil,
    Encrypt: nil,
    SkipEncryptCopyPlugins: false,
    Env: nil,
    Source: "",
    EphemeralMounts: nil,
    BindMounts: nil,
    Partitions: v1.ElementalPartitions{
      BIOS: nil,
      EFI: nil,
      OEM: nil,
      Recovery: nil,
      State: nil,
      Persistent: nil,
    },
    Active: v1.Image{
      File: "",
      Label: "",
      Size: 8192,
      FS: "",
      Source: nil,
      MountPoint: "",
      LoopDevice: "",
    },
    Recovery: v1.Image{
      File: "",
      Label: "",
      Size: 8192,
      FS: "",
      Source: nil,
      MountPoint: "",
      LoopDevice: "",
    },
    Passive: v1.Image{
      File: "",
      Label: "",
      Size: 8192,
      FS: "",
      Source: nil,
      MountPoint: "",
      LoopDevice: "",
    },
    GrubDefEntry: "Wiki Woko",
    ExtraPartitions: nil,
    ExtraDirsRootfs: nil,
    Force: false,
    NoUsers: false,
```


but then on the spec build it generates the smaller image instead of overriding with the user value:

```
2024-11-05T14:42:37Z INF Setting image size to 3016Mb
2024-11-05T14:42:37Z DBG Loaded upgrade spec: &v1.UpgradeSpec{
  Entry: "",
  Active: v1.Image{
    File: "/run/initramfs/cos-state/cOS/transition.img",
    Label: "COS_ACTIVE",
    Size: 3016,
    FS: "ext2",
    Source: &v1.ImageSource{
      source: "ttl.sh/upgradeitxaka:latest",
      srcType: "oci",
    },
    MountPoint: "/run/cos/transition",
    LoopDevice: "",
  },

```
