### ISSUE TITLE
Reset fails on raw images

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#3025]
Reset fails in arm images because it cant find the state partition. But on RAW images we only ship the recovery and oem partition so this doesnt work.

![image](https://github.com/user-attachments/assets/fc662400-a76a-467b-969b-60d5aa3f4581)

**Comment by dnugmanov** [comment]
You need to create partition before resetting, your disk should have enough free space in the end of the disk where `COS_RECOVERY` is located or separate disk. 

I am using:
```
    - name: "Repart image"
      layout:
        device:
          label: COS_RECOVERY
        add_partitions:
          - fsLabel: COS_STATE
            size: 50000 <-- adjust this.
            pLabel: state
          - fsLabel: COS_PERSISTENT
            pLabel: persistent
            size: 0
            filesystem: "ext4"
    - name: "Deploy kairos"
      commands:
      - kairos-agent --debug reset --unattended
      - touch /usr/local/.deployed
      - reboot
      if: '[ -f "/run/cos/recovery_mode" ] && [ ! -e /usr/local/.deployed ]'

```
