### ISSUE TITLE
Supply a valid config.yaml for raw images if users dont

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#3026]
If you create a raw image and dont provide a config file it will generate a raw image thaqt its fully invalid., You cant loging into it, you cant reset, etc..

We should probably provide a default config that at least sets stuff.

example provided by @dnugmanov
```
#cloud-config
name: "Default user"
stages:
  initramfs:
    - name: "Set default user/pass"
      users:
        kairos:
          passwd: "kairos"
          groups:
            - "admin"
    - name: "Repart image"
      layout:
        device:
          label: COS_RECOVERY
        add_partitions:
          - fsLabel: COS_STATE
            size: 8000
            pLabel: state
          - fsLabel: COS_PERSISTENT
            pLabel: persistent
            size: 0
            filesystem: "ext4"
    - name: "Deploy kairos"
      commands:
      - kairos-agent --debug reset --unattended
      - touch /usr/local/.deployed
      - reboot
      if: '[ -f "/run/cos/recovery_mode" ] && [ ! -e /usr/local/.deployed ]'
```
