### ISSUE TITLE
Partition autogrowing is not functioning on Alpine ARM images

### ISSUE THREAD

**Issue by DevOpsFu** [kairos-io/kairos#306]
Image:  kairos-alpine-arm-rpi-v1.1.4-k3sv1.25.2+k3s1.img.xz 
Hardware: Raspberry Pi 4 model B  with 64Gb SD card

cloud-config:

```
#cloud-config

users:
- name: "kairos"
  passwd: "kairos"
  lock_passwd: true
  groups: "admins"
  ssh_authorized_keys:
  - github:devopsfu

stages:
  initramfs:
    - name: "Set hostname"
      hostname: kairos
    - name: "Set up Ethernet interface"
      files:
        - path: /var/lib/connman/default.config
          permission: 0644
          content: |
            [service_eth0]
            Type = ethernet
            IPv4 = 172.16.0.5/24/172.16.0.254
            IPv6 = off
            Nameservers = 1.1.1.1
            Timeservers = uk.pool.ntp.org

k3s:
  enabled: true
```

The `k3s` service appears to start, but if I do a `k3s kubectl get nodes` I see the following:

```
INFO[0000] Acquiring lock file /var/lib/rancher/k3s/data/.lock
INFO[0001] Preparing data dir /var/lib/rancher/k3s/data/a6de074690df59f81a5341041635a72720bd8ab6f08a15e362dfe33b896b4de9
INFO[0002] error extracting tarball into /var/lib/rancher/k3s/data/a6de074690df59f81a5341041635a72720bd8ab6f08a15e362dfe33b896b4de9-tmp after 14 files, 2 dirs, 1.589860258s: error writing to /var/lib/rancher/k3s/data/a6de074690df59f81a5341041635a72720bd8ab6f08a15e362dfe33b896b4de9-tmp/bin/k3s: write /var/lib/rancher/k3s/data/a6de074690df59f81a5341041635a72720bd8ab6f08a15e362dfe33b896b4de9-tmp/bin/k3s: no space left on device
FATA[0003] extracting data: error writing to /var/lib/rancher/k3s/data/a6de074690df59f81a5341041635a72720bd8ab6f08a15e362dfe33b896b4de9-tmp/bin/k3s: write /var/lib/rancher/k3s/data/a6de074690df59f81a5341041635a72720bd8ab6f08a15e362dfe33b896b4de9-tmp/bin/k3s: no space left on device
```

Output of `df -h`:

```
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         10M     0   10M   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           764M  8.4M  756M   2% /run
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/mmcblk0p2  5.9G  2.1G  3.5G  38% /run/initramfs/cos-state
/dev/loop0      2.0G  1.1G  816M  57% /
tmpfs           955M  136K  955M   1% /run/overlay
overlay         955M  136K  955M   1% /etc
overlay         955M  136K  955M   1% /srv
/dev/mmcblk0p4   55M  1.3M   50M   3% /usr/local
overlay         955M  136K  955M   1% /var
tmpfs           1.9G     0  1.9G   0% /tmp
```

**Comment by mudler** [comment]
Hi @DevOpsFu ! thanks for opening the issue.

I think the automatic grow partitioning isn't functioning correctly - however it should be enough to grow the partition labeled "COS_PERSISTENT" and the underlying fs after flashing the image. I'll update the docs with a workaround until this is fixed

**Comment by DevOpsFu** [comment]
Thanks @mudler  - resizing the partition did indeed resolve the issue!

I now have a separate issue which is that DNS resolution isn't working for some reason despite specifying a nameserver in my connman config. I will dig into that next. 

I think the quickstart documentation, particularly around the cloud-config and yip vs cloud-init syntax could do with some improvement, as it has taken a lot of time for me to understand what's going on, mostly by piecing together information from various search results. I would be happy to help if the project is open to documentation contributions.

**Comment by mudler** [comment]
> Thanks @mudler - resizing the partition did indeed resolve the issue!

Awesome, glad to hear that!

> 
> I now have a separate issue which is that DNS resolution isn't working for some reason despite specifying a nameserver in my connman config. I will dig into that next.

Did you tried the DNS setting from cloud config?

> 
> I think the quickstart documentation, particularly around the cloud-config and yip vs cloud-init syntax could do with some improvement, as it has taken a lot of time for me to understand what's going on, mostly by piecing together information from various search results. I would be happy to help if the project is open to documentation contributions.

Definitely it does, docs needs some love, please feel free to open up a PR, thanks :bow: !

**Comment by DevOpsFu** [comment]
> > I now have a separate issue which is that DNS resolution isn't working for some reason despite specifying a nameserver in my connman config. I will dig into that next.
> 
> Did you tried the DNS setting from cloud config?

I've tried that just now, and it doesn't seem to work (I'm probably doing something wrong here though!) I removed the `Nameservers` from the connman config and added a `dns` key. Here's the complete networking config:

```
stages:
  initramfs:
    - name: "Set hostname"
      hostname: kairos
    - name: "Set up Ethernet interface"
      files:
        - path: /var/lib/connman/default.config
          permission: 0644
          content: |
            [service_eth0]
            Type = ethernet
            IPv4 = 172.16.0.5/24/172.16.0.254
            IPv6 = off
            Timeservers = uk.pool.ntp.org
    - name: "Set DNS servers"
      dns:
        nameservers:
        - 1.1.1.1
        - 8.8.8.8
```

This had no effect. I also added `path: "/etc/resolv.conf"` to the `dns` section, but that did not write any changes to the file. My head is spinning!

While I'm here, can I ask if the OpenSUSE image has been switched to `systemd-networkd` or if it still uses `wicked`? I would, overall, prefer a `systemd` based distribution (maybe that will also work better with cloud-init's native config rather than having to write out config files directly?

> > I think the quickstart documentation, particularly around the cloud-config and yip vs cloud-init syntax could do with some improvement, as it has taken a lot of time for me to understand what's going on, mostly by piecing together information from various search results. I would be happy to help if the project is open to documentation contributions.
> 
> Definitely it does, docs needs some love, please feel free to open up a PR, thanks 🙇 !

I'll see if I can do something to help on this! My journey into kairos has been a little tricky to say the least, and making the path easier for new users will definitely help.

Sorry for dragging this thread on with issues unrelated to the original report - let me know if you'd prefer me to file a separate issue for the DNS problem.
