### ISSUE TITLE
feat: Update existing k3s config

### ISSUE THREAD

**Issue by gnoejuan** [kairos-io/kairos#3390]
**Is your feature request related to a problem? Please describe.**

Problem: Attempting to update kube-api args to add OIDC login capabilities.

**Describe the solution you'd like**

Either:

- Documentation on the "proper" way to update k3s and k3s-agent config blocks
- Accept updates to k3s and k3s-agent config blocks ( example: `sudo nano /usr/local/cloud-config/config.yaml` and reboot / reload somehow ) 

**Describe alternatives you've considered**

- Flashing SD card again with updated config.
- Upgrade-Controller?

**Additional context**

I'm not immediately aware of any additional context that would be useful.

**Comment by jimmykarily** [comment]
@gnoejuan thanks for reporing this.

I looked in to our documentation and there [is only a warning](https://kairos.io/docs/reference/configuration/#k3s-settings):

```
The K3s args are only applied when the K3s service is created, which is during installation. Changing the args key after installation won’t have any effect.
```

but no explanation on how to change k3s settings after installation. I suspect it's possible by editing the relevant files in some stage but needs investigation and documentations.

**Comment by jimmykarily** [comment]
The k3s installer (https://get.k3s.io) is writing things mainly to `/etc/init.d/`, `/etc/systemd` and `/etc/rancher`, all of which are mounted on the persistent partition: https://github.com/kairos-io/kairos-init/blob/a96a4bdf3806d571da7da1128222a4ba18531e58/pkg/bundled/cloudconfigs/00_rootfs.yaml#L18

It should be just a matter of "patching" the appropriate file in order to make changes post-install.

**Comment by sdwilsh** [comment]
I ended up writing an ansible play to try and keep the systemd files in sync with the config, which has been working great for me for a while now (not that I've changed it too often).  I can provide more details if that's helpful.

**Comment by gnoejuan** [comment]
> I ended up writing an ansible play to try and keep the systemd files in sync with the config, which has been working great for me for a while now (not that I've changed it too often). I can provide more details if that's helpful.

Yes, please!

**Comment by gnoejuan** [comment]
@jimmykarily 

```bash
rpi4:~$ cat /etc/init.d/k3s
#!/sbin/openrc-run

depend() {
    after network-online
    want cgroups
}

start_pre() {
    rm -f /tmp/k3s.*
}

supervisor=supervise-daemon
name=k3s
command="/usr/bin/k3s"
command_args="server \
    >>/var/log/k3s.log 2>&1"

output_log=/var/log/k3s.log
error_log=/var/log/k3s.log

pidfile="/var/run/k3s.pid"
respawn_delay=5
respawn_max=0

set -o allexport
if [ -f /etc/environment ]; then . /etc/environment; fi
if [ -f /etc/rancher/k3s/k3s.env ]; then . /etc/rancher/k3s/k3s.env; fi
set +o allexport
```

This appears to be the file I'm looking for. 

I'm going to try to update `command_args="server \` to `command_args="server --kube-apiserver-arg=oidc-issuer-url=https://website.com  [rest of arguments here] \` 

( Although, I think I can also use the k3s.env to set the arguments [docs](https://docs.k3s.io/reference/env-variables) )

and in a normal installation, I would systemctl restart k3s.service, but in this context I believe I will have to restart the machine. 

( I'm still unable to use oidc, however, I think this is the right track )

**Comment by gnoejuan** [comment]
> The k3s installer (https://get.k3s.io) is writing things mainly to `/etc/init.d/`, `/etc/systemd` and `/etc/rancher`, all of which are mounted on the persistent partition: https://github.com/kairos-io/kairos-init/blob/a96a4bdf3806d571da7da1128222a4ba18531e58/pkg/bundled/cloudconfigs/00_rootfs.yaml#L18
> 
> It should be just a matter of "patching" the appropriate file in order to make changes post-install.

@jimmykarily Ah oidc didn't work, because the changes weren't permanent. Which would line up with the documentation

https://kairos.io/docs/architecture/immutable/   `/etc - ephemeral`

```bash
rpi4:~$ sudo nano /etc/init.d/k3s
rpi4:~$ sudo reboot
###
 rpi4:~$ sudo cat /etc/init.d/k3s
###
command_args="server \
    >>/var/log/k3s.log 2>&1"
###

```

**Comment by gnoejuan** [comment]
Updated the k3s file using the boot stage.

`/usr/local/cloud-config/001_oidc.yaml`

```yaml

stages:
  boot:
    - name: "OIDC Setup"
      environment:
        OIDC_ISSUER_URL: "https://gitlab.com"
        OIDC_CLIENT_ID: "xxxxxxxxxxx"
        OIDC_USERNAME_CLAIM: "preferred_username"
        OIDC_USERNAME_PREFIX: "gitlab:"
        OIDC_GROUPS_CLAIM: "groups_direct"
        OIDC_GROUPS_PREFIX: "xxxxx:"
      commands:
        - sed -i "s|command_args=\"server \\\\|command_args=\"server  --kube-apiserver-arg oidc-issuer-url=${OIDC_ISSUER_URL} --kube-apiserver-arg oidc-client-id=${OIDC_CLIENT_ID} --kube-apiserver-arg oidc-username-claim=${OIDC_USERNAME_CLAIM} --kube-apiserver-arg oidc-username-prefix=${OIDC_USERNAME_PREFIX} --kube-apiserver-arg oidc-groups-claim=${OIDC_GROUPS_CLAIM} --kube-apiserver-arg oidc-groups-prefix=${OIDC_GROUPS_PREFIX} \\\\|" /etc/init.d/k3s
name: "OIDC Setup"

```

However, the environment variables are rendered empty. After multiple tries with different syntax, I have a feeling the environment variables aren't available for the commands block.

@jimmykarily Would this be an appropriate way to update the kube-api file in the Kairos environment?
