### ISSUE TITLE
Accept kubernetes config style as input

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#34]
cloud config and c3os blocks should be ideally configurable as standard kubernetes resources. To follow the same API-style, a configuration similar to kubernetes API is wanted for consistency, example taken from kind:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:$KUBE_VERSION
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
```
