### ISSUE TITLE
Traceback label with disk partition

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#380]
Currently https://github.com/kairos-io/kcrypt-challenger is the component that sits on Kubernetes and gives out the passwords. It also contains the TPM client side.

the https://github.com/kairos-io/kcrypt is the low level part of the stack, which sits into the initramfs and decrypts the fs.

```yaml
apiVersion: keyserver.kairos.io/v1alpha1
kind: SealedVolume
metadata:
    name: test2
    namespace: default
spec:
  TPMHash: "fff"
  partitionSecrets:
    COS_PERSISTENT:
      name: mysecret
      path: pass
    unknown:
      name: mysecret
      path: pass
  quarantined: **false
```

This card is about the issue that "unknown" would decrypt "COS_PERSISTENT" because the client doesn't know which labels the partitions are since they are encrypted during boot. this is a workaround, so the card is about to make the state saved somewhere so we can pick it up later and avoid supplying the same information twice.
