### ISSUE TITLE
undefined system source to install

### ISSUE THREAD

**Issue by felixmw** [kairos-io/kairos#413]
I get the following error message when I try to run the manual installation procedure: "undefined system source to install"

That's what I did:
- I flashed the following image to an SD-card an booted my raspberry pi4: [kairos-alpine-arm-rpi-v1.1.6-k3sv1.25.3+k3s1.img.xz](https://github.com/kairos-io/provider-kairos/releases/download/v1.1.6/kairos-alpine-arm-rpi-v1.1.6-k3sv1.25.3+k3s1.img.xz)
- The pi boots up fine and I am able to login in via ssh (kairos/kairos)
- However, when I try to start the manual installation procedure with the following command, I get the error message mentioned above: sudo kairos-agent manual-install /tmp/cloud-init.yml

The cloud-init.yml file has the following content (the j2 variables have been replaced with actual values):

```
---
hostname: "kube-test1"

# The install block is to drive automatic installations without user interaction.
install:
  # Device for automated installs
  device: "auto"
  # Reboot after installation
  reboot: true
  # Power off after installation
  poweroff: true
  # Set to true when installing without Pairing
  auto: true

k3s:
  enabled: true
  env:
    K3S_TOKEN: "{{ k3s_token }}"
  args:
    - --cluster-init
    - --write-kubeconfig-mode 644 
    - --disable=local-storage 
    - --disable=metrics-server 
    - --disable servicelb 
    - --tls-san={{ apiserver_endpoint }} 
    - --node-taint node-role.kubernetes.io/master=true:NoSchedule 
    - --kube-apiserver-arg default-not-ready-toleration-seconds=30 
    - --kube-apiserver-arg default-unreachable-toleration-seconds=30 
    - --kube-controller-arg node-monitor-period=20s 
    - --kube-controller-arg node-monitor-grace-period=20s 
    - --kubelet-arg node-status-update-frequency=5s

users:
  - name: "kairos"
    passwd: "kairos"
    lock_passwd: true
    groups: "admins"
    ssh_authorized_keys:
      - github:{{ github_user }}
```

But even if I replace the file's content with the example hosted [here](https://github.com/kairos-io/kairos/blob/master/examples/k3s-server.yaml), the error message remains the same.

Google has not come up with any helpful information on this error. Can anybody here point me into the right direction? Any kind of help is highly appreciated.

Thanks!

**Comment by mudler** [comment]
Hi @felixmw ! 

Thanks for raising this up - our docs are not entirely clear in that regard. The image doesn't need any installation, once the flashing is done the system is ready to use. To configure it, just put your config file under /usr/local/cloud-config and reboot

**Comment by felixmw** [comment]
Hi @mudler,

thanks a lot for your quick response. That helped a lot!

I did as you said and added two additional cloud-config files into the /usr/local/cloud-config folder.

The first one sets the hostname and sets a ssh-key for the kairos user. This worked like charm.

The second file ist meant to configure k3s. However the k3s-service does not come up.

Do you have another hint on what I should do differently?

This is the cloud-config file that's not working (again the j2 variables have been replaced with actual values):

```
#cloud-config
k3s:
  enabled: true
  env:
    K3S_NODE_NAME: "{{ hostname }}"
    K3S_TOKEN: "{{ k3s_token }}"
  args:
    - --cluster-init
    - --write-kubeconfig-mode 644 
    - --disable=local-storage 
    - --disable=metrics-server 
    - --disable servicelb 
    - --tls-san={{ apiserver_endpoint }} 
    - --node-taint node-role.kubernetes.io/master=true:NoSchedule 
    - --kube-apiserver-arg default-not-ready-toleration-seconds=30 
    - --kube-apiserver-arg default-unreachable-toleration-seconds=30 
    - --kube-controller-arg node-monitor-period=20s 
    - --kube-controller-arg node-monitor-grace-period=20s 
    - --kubelet-arg node-status-update-frequency=5s
    ```

**Comment by Ognian** [comment]
use this in the `initramfs` section:
```
- name: "Set DNS servers" # fix for https://github.com/kairos-io/kairos/issues/335
      dns:
        nameservers:
        - 1.1.1.1
        - 8.8.8.8   
```
Since I'm trying this too, a question about the kairos user: when configuring it the way you do, are you able to login via ssh with the ssh key and does the locking via password work (so that you are not able to login via password), since I tried different ways to disable the password login but either I locked the user (no login via password and no login via ssh key) or both logins work (ssh and password)...
