### ISSUE TITLE
config_url not working?

### ISSUE THREAD

**Issue by stelb** [kairos-io/kairos#461]
**Kairos version:**
1.1.6-1.2.0 at least

**CPU architecture, OS, and Version:**
x86-64

**Describe the bug**
I boot kairos via ipxe with config_url parameter: kairos-agent install is started, yaml file is accessed but agent stops, with 'no configuration, stopping installation'

**To Reproduce**

my config.yaml:
```
install:
  device: "/dev/sda"
  reboot: "true"
  auto: "true"

stages:
  initramfs:
    - name: "Setup hostname"
      hostname: "kairos-{{ trunc 4 .MachineID }}"
  network:
    - name: "Setup users"
      authorized_keys:
        kairos:
          - github:stelb

users:
- name: "kairos"
  passwd: "kairos"
  lock_passwd: true
  groups: "admins"
  ssh_authorized_keys:
  - github:stelb

kairos:
  network_token: b3RwOgogIGRodDoKICAgIGludGVydmFsOiA5MjIzMzcyMDM2ODU0Nzc1ODA3CiAgICBrZXk6IElaMzZMRkoyT05BTlpJUTdNSVQ2RjVHSExHRFBIN1VTN1hQV01PSUMyWkRVVUI3N0hEMkEKICAgIGxlbmd0aDogMzIKICBjcnlwdG86CiAgICBpbnRlcnZhbDogOTIyMzM3MjAzNjg1NDc3NTgwNwogICAga2V5OiBZNVZPQk5UTVFDNVdHV0dUWVNITVk3T1VFS0pXNUpDN1BVVTVCUjZEUzZMVEM2UzVCNE9RCiAgICBsZW5ndGg6IDMyCnJvb206IFZGT0tFU05NQklESFlMSlZUU0NVWU1EUzVIWlNYRkxEUjVCM1BFQjUzN1lPSllRUFlUNVEKcmVuZGV6dm91czogSkFqeFZOV09vRFF1dWNuem1CaGVWZ3BnQm9PeXlPbHMKbWRuczogSU96d2VERVJaTEhtR2ZhYXd1YWhVc3doQ2tzZWdvWnkKbWF4X21lc3NhZ2Vfc2l6ZTogMjA5NzE1MjAK
k3s-agent: {}
k3s: {}
```

**Expected behavior**

Starting installation as defined in config.yaml
**Logs**

192.168.42.184 - - [19/Nov/2022:16:47:45 +0000] "GET /cloudinit/kairos/config.yaml HTTP/1.1" 200 1010 "-" "Go-http-client/1.1"

**Additional context**

**Comment by mudler** [comment]
Hey @stelb :wave: 

Config looks wrong here, auto and reboot are bools, not strings:

```yaml
install:
  device: "/dev/sda"
  reboot: "true"
  auto: "true"
```

should be:

```yaml
install:
  device: "/dev/sda"
  reboot: true
  auto: true
```
