### ISSUE TITLE
Netbooting alpine falls into a loop

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#497]
Reproduce:

- `earthly -P +all --FLAVOR=alpine-ubuntu --ipxe_script=ipxe.script` ([ipxi.script](https://github.com/danderson/netboot/blob/master/pixiecore/boot.ipxe)) or just use https://github.com/kairos-io/ipxe-dhcp/releases/download/v0.1/ipxe-dhcp.iso if you have initrd, kernel and squashfs already
- Start on pixiecore on another VM:

```
dimitris@ubuntu-vm:~$ sudo docker run  --net=host -v $PWD/build:/files   quay.io/pixiecore/pixiecore   boot /files/kairos-core-alpine-ubuntu-kernel /files/kairos-core-alpine-ubuntu-initrd --cmdline='rd.neednet=1 ip=dhcp rd.cos.disable root=live:{{ ID "/files/kairos-core-alpine-ubuntu.squashfs" }} netboot nodepair.enable config_url={{ ID "/files/config.yaml" }} console=tty1 console=ttyS0 console=tty0'
```
(config.yaml is any cloud-config you want, it shouldn't matter for this issue)

Booted VM falls in a loop and installation never ends

**Comment by mudler** [comment]
I'm wondering if this is still present as of https://github.com/kairos-io/kairos/issues/52

**Comment by jimmykarily** [comment]
Same thing on alpine-opensuse

**Comment by jimmykarily** [comment]
looped with this config: 

```
install:                                                                                                                                                                                                                         
  # Device for automated installs
  device: "auto"                                                                                                                                                                                                                 
  # Reboot after installation                                                                                                                                                                                                    
  reboot: false                                                                                                                                                                                                                  
  # Power off after installation                                                                                                                                                                                                 
  poweroff: false                
  # Set to true to enable automated installations                                                                                                                                                                                
  auto: true 
```

setting `poweroff: true` also doesn't work. `reboot: true` breaks the loop.
