### ISSUE TITLE
:book: full P2P sample in docs

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#536]
On one nodethe config has:
```
kairos:
  network_token: "..."
  role: "master"
k3s:
  enabled: true
```
on the other:
```
kairos:
  network_token: "..."    

k3s-agent:
  enabled: true
```
but edgevpn service is not started on any of the nodes.
What am I doing wrong?

_Originally posted by @Ognian in https://github.com/kairos-io/kairos/discussions/533_
