### ISSUE TITLE
Alpine: set a higher limit for open files

### ISSUE THREAD

**Issue by christianprim** [kairos-io/kairos#537]
**Kairos version:** Alpine flavor

**CPU architecture, OS, and Version:** amd64

**Describe the bug**
The hard limit for open files is too low for many applications (ElasticSearch, TiDB, etc.). In the systemd-based flavor the limit is set via systemd to a much higher value.

**To Reproduce**
`ulimit -Hn` shows a value as low as 4096.

**Expected behavior**
`ulimit -Hn` should be much higher. k3s suggests 1048576 (see `/etc/systemd/system/k3s-agent.service`)

**Possible fix**
```
stages:
   initramfs.before:
     - name: "Setup higher limit for open files"
       if: '[ -e /sbin/rc-service ]'
       commands:
       - echo 'rc_ulimit="-n 1048576"' >> /etc/rc.conf
```

`ulimit` still shows the low value, since the login shell is not started as a service, but containerd has the correct high value and so does every command in a pod, which is good. (`sudo prlimit -p <PID of containerd for instance>`)
