### ISSUE TITLE
WebUI - bootstrapper (step 3)

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#801]
This is about the 3rd step from here: https://github.com/kairos-io/kairos/issues/772

**Comment by mudler** [comment]
Work happening in https://github.com/kairos-io/AuroraBoot.

Usage:  
 
 ``` yaml
artifact_version: "v1.5.0"
release_version: "v1.5.0"
flavor: "rockylinux"
repository: "kairos-io/kairos"
  
  cloud_config: |
```
Save as example.yaml, and run with docker:  
```
docker run -v $PWD/example.yaml:/example.yaml --rm -ti --net host quay.io/kairos/auroraboot /example.yaml
```
