### ISSUE TITLE
No DNS at initramfs stage

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#835]
At initramfs state, there is no DNS setup and it's not possible to resolve domains. Kairos config file may include things like the kcrypt challenger server, which may be served on a specific domain. No DNS means, those services won't be accessible resulting in a system that doesn't boot correctly.

Our documentation mentions some ways to configure DNS (https://kairos.io/docs/reference/configuration/#syntax) but this doesn't seem to work on systemd based systems at least on the initramfs stage.

Users have workarounds like this:

```
stages: 
  boot.before:
     - name: "DNS settings"
       commands:
       - echo "DNS=8.8.8.8 8.8.4.4" >> /etc/systemd/resolved.conf
       - echo -e "\n[DHCP]\nUseDNS=false" >> /etc/systemd/network/20-dhcp.network
       - systemctl restart systemd-networkd
       - systemctl restart systemd-resolved
```
(thanks @christianprim) 

but we should provide a simpler way to configure DNS on any system.
