### ISSUE TITLE
:bug: `hostname` does not work on debian

### ISSUE THREAD

**Issue by massimogallina** [kairos-io/kairos#887]
**Kairos version:** 1.5.1

**CPU architecture, OS, and Version:** amd64, kairos-debian-v1.5.1-k3sv1.26.1+k3s1

**Describe the bug**

I am having issues using the hostname configuration option as per [documentation](https://kairos.io/docs/reference/configuration/#hostname).
If I use this option the file `/etc/hosts` is not created.
I have tried also with:
```yaml
#cloud-config

hostname: "your_hostname_here"
```
It sets the hostname, but does not create the `/etc/hosts` file.

**To Reproduce**

Install kairos with the ISO **kairos-debian-v1.5.1-k3sv1.26.1+k3s1** and apply the a configuration like the following one:
```yaml
#cloud-config

hostname: test
# Define the user accounts on the node.
users:
- name: "kairos"
  passwd: "kairos"
  ssh_authorized_keys:
  - "ssh-rsa AAAA..."

# Enable K3s on the node.
k3s:
  enabled: true
  args:
  - --disable=traefik,servicelb

stages:
  initramfs:
    - files:
        - path: /etc/systemd/network/10-config.network
          permissions: 0644
          content: |
            [Match]
            Name=enp1s0

            [Network]
            Address=192.168.11.55/24
            Gateway=192.168.11.250
            DNS=192.168.1.181 8.8.8.8
  boot:
    - name: "Setup hostname"
      hostname: "test"
```

**Comment by mauromorales** [comment]
Looking into this. Did a first test using hostname at the root level and it works as expected. Will now test at boot stage

**Comment by mauromorales** [comment]
putting it under boot didn't work. Investigating

**Comment by mauromorales** [comment]
the problem is there for opensuse, so I'm wondering if this is something that can only be run at root level

@mudler @Itxaka do you guys know if setting the hostname is something is possible inside of the stages? from what I can see in cloud config documentation it doesn't say anything specific about that, but in our docs we do have a couple of examples were we do

**Comment by Itxaka** [comment]
I know that at least on the `boot` stage its possible, as recovery sets the hostname to cos-recovery https://github.com/kairos-io/packages/blob/main/packages/system/cloud-config/oem/06_recovery.yaml#L23

Also I get the proper hostname and /etc/hosts with the following install config:

```
#node-config

install:
  auto: true
  reboot: true
  device: /dev/vda

stages:
   initramfs:
     - name: "Set user and password"
       users:
        kairos:
          passwd: "kairos"
       hostname: kairos-{{ trunc 4 .Random }}
```

So it also works under initramfs.

This all under opensuse-leap. So maybe its a debian issue?
You can check the systemd-hostnamed logs to see if it was set or tried to set

`Feb 17 14:21:26 kairos-fq8g systemd-hostnamed[1858]: Hostname set to <kairos-fq8g> (static)`
