### ISSUE TITLE
:book: Document kcrypt TLS feature

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#890]
A follow up of: https://github.com/kairos-io/kcrypt-challenger/pull/12

Let's document how a cert can be pinned in the configuration.

**Comment by ci-robbot** [comment]
Triage: still valid after three and a half years. The feature shipped, the docs never followed, and the docs currently steer people to the unpinned path.

**The option exists.** `kcrypt.challenger.certificate` is parsed in `kcrypt/discovery/client/config.go:18`, and when set it is handed to the TPM client as the CA bundle in `kcrypt/discovery/client/client.go:215-218` (`tpm.WithCAs(...)`). There is also a `--certificate` CLI override (`kcrypt/discovery/discovery.go:168`), and the command's own `--help` text already documents the key:

```
kcrypt:
  challenger:
    challenger_server: "https://my-server.com:8082"  # Server URL
    mdns: true                                       # Enable mDNS discovery
    certificate: "/path/to/server-cert.pem"          # Server certificate
    tpm_device: "/dev/tpmrm0"                        # TPM device path
```
(`kcrypt/discovery/discovery.go:53-60`)

**The docs never mention it.** [Partition encryption](https://kairos.io/docs/advanced/partition_encryption/) documents `challenger_server`, `mdns`, `nv_index`, `c_index` and `tpm_device`. `certificate` is absent from both the example block and the options table. `tpm_device` is documented at the top level (`kcrypt.tpm_device`) while the client reads it under `kcrypt.challenger.` too, which is worth a second look while someone is in there.

**Why this matters more than a missing row.** Every KMS example in that page uses `challenger_server: "http://192.168.68.109:30000"`. Plain HTTP, and no pinning, so the passphrase exchange goes to whatever answers on that address. The one option that fixes it is the one we never wrote down. The original PR this issue follows up on (kcrypt-challenger#12) added pinning precisely so that would not be the default story.

Keeping open. Sending a docs PR that adds `certificate` to the example and the table, and shows the `https://` KMS variant next to it.
