### ISSUE TITLE
:bug: Users validation warning

### ISSUE THREAD

**Issue by mauromorales** [kairos-io/kairos#988]
The validator is currently warning about this config

```
#node-config

stages:
   initramfs:
     - name: "Set user and password"
       users:
        kairos:
          passwd: "kairos"
       hostname: kairos-{{ trunc 4 .Random }}
 ```
 
 With the message
 
 ```
 WARNING: jsonschema: '' does not validate with file:///home/kairos/schema.json#/required: missing properties: 'users'
 ```
 
 This is because the current schema expects users to be defined at the root level.
